package com.Ntranga.CLMS.vo;
// Generated 25 Jan, 2017 6:00:55 PM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Date
;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AssociatingDepartmentToLocationPlant generated by hbm2java
 */
@Entity
@Table(name="associating_department_to_location_plant"   
)
public class AssociatingDepartmentToLocationPlantVo  implements java.io.Serializable {


     private Integer associationDepartmentId;
     private Integer plantId;
     private Integer departmentId;
     private Integer customerId;
     private Integer companyId;
     private Integer locationId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     
     private List<DepartmentVo> departmentlist = new ArrayList();

    public AssociatingDepartmentToLocationPlantVo() {
    }

	public Integer getAssociationDepartmentId() {
		return associationDepartmentId;
	}

	public void setAssociationDepartmentId(Integer associationDepartmentId) {
		this.associationDepartmentId = associationDepartmentId;
	}

	public Integer getPlantId() {
		return plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

	public Integer getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Integer getCompanyId() {
		return companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public Integer getLocationId() {
		return locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	public int getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public int getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(int modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public List<DepartmentVo> getDepartmentlist() {
		return departmentlist;
	}

	public void setDepartmentlist(List<DepartmentVo> departmentlist) {
		this.departmentlist = departmentlist;
	}

	

    


}


