package com.Ntranga.CLMS.vo;
// Generated 20 Jul, 2016 1:01:39 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerEducationDetails generated by hbm2java
 */

public class WorkerEducationDetailsVo  implements java.io.Serializable {


     private Integer workerEducationId;  
     //private String skillType;
     private String educationLevel;
     private String degreeName;
     private String modeOfEducation;
     private String institutionName;
     private Integer yearOfPassing;
     private String percentageOrGrade;
     private byte[] certificate;
     private String fileName;
     private String filePath;
     
     
	public Integer getWorkerEducationId() {
		return workerEducationId;
	}
	public void setWorkerEducationId(Integer workerEducationId) {
		this.workerEducationId = workerEducationId;
	}
	/*public String getSkillType() {
		return skillType;
	}
	public void setSkillType(String skillType) {
		this.skillType = skillType;
	}*/
	public String getEducationLevel() {
		return educationLevel;
	}
	public void setEducationLevel(String educationLevel) {
		this.educationLevel = educationLevel;
	}
	public String getDegreeName() {
		return degreeName;
	}
	public void setDegreeName(String degreeName) {
		this.degreeName = degreeName;
	}
	public String getModeOfEducation() {
		return modeOfEducation;
	}
	public void setModeOfEducation(String modeOfEducation) {
		this.modeOfEducation = modeOfEducation;
	}
	public String getInstitutionName() {
		return institutionName;
	}
	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}
	public Integer getYearOfPassing() {
		return yearOfPassing;
	}
	public void setYearOfPassing(Integer yearOfPassing) {
		this.yearOfPassing = yearOfPassing;
	}
	public String getPercentageOrGrade() {
		return percentageOrGrade;
	}
	public void setPercentageOrGrade(String percentageOrGrade) {
		this.percentageOrGrade = percentageOrGrade;
	}
	public byte[] getCertificate() {
		return certificate;
	}
	public void setCertificate(byte[] certificate) {
		this.certificate = certificate;
	}
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	public String getFilePath() {
		return filePath;
	}
	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}
    


}


