package com.Ntranga.core.CLMS.entities;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplicationApprovalPath generated by hbm2java
 */
@Entity
@Table(name = "application_approval_path")
public class ApplicationApprovalPath implements java.io.Serializable {

	private Integer applicationApprovalPathId;
	private String pathCode;
	private String pathName;
	private Integer customerId;
	private Integer companyId;
	private Integer approvalPathModuleId;
	private Integer approvalPathTransactionId;
	private String noApprovalRequired;
	private Integer noOfApprovalLevels;
	private String isActive;
	private Integer createdBy;
	private Date createdDate;
	private Integer modifiedBy;
	private Date modifiedDate;
	private Set<ApplicationApprovalPathFlow> applicationApprovalPathFlows = new HashSet<ApplicationApprovalPathFlow>(0);

	public ApplicationApprovalPath() {
	}

	public ApplicationApprovalPath(String pathCode, String pathName, Integer customerId, Integer companyId,
			Integer approvalPathModuleId, Integer approvalPathTransactionId, String noApprovalRequired,
			Integer noOfApprovalLevels, String isActive, Integer createdBy, Date createdDate, Integer modifiedBy,
			Date modifiedDate, Set<ApplicationApprovalPathFlow> applicationApprovalPathFlows) {
		this.pathCode = pathCode;
		this.pathName = pathName;
		this.customerId = customerId;
		this.companyId = companyId;
		this.approvalPathModuleId = approvalPathModuleId;
		this.approvalPathTransactionId = approvalPathTransactionId;
		this.noApprovalRequired = noApprovalRequired;
		this.noOfApprovalLevels = noOfApprovalLevels;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.applicationApprovalPathFlows = applicationApprovalPathFlows;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "application_approval_path_id", unique = true, nullable = false)
	public Integer getApplicationApprovalPathId() {
		return this.applicationApprovalPathId;
	}

	public void setApplicationApprovalPathId(Integer applicationApprovalPathId) {
		this.applicationApprovalPathId = applicationApprovalPathId;
	}

	@Column(name = "path_code", length = 100)
	public String getPathCode() {
		return this.pathCode;
	}

	public void setPathCode(String pathCode) {
		this.pathCode = pathCode;
	}

	@Column(name = "path_name", length = 100)
	public String getPathName() {
		return this.pathName;
	}

	public void setPathName(String pathName) {
		this.pathName = pathName;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "approval_path_module_id")
	public Integer getApprovalPathModuleId() {
		return this.approvalPathModuleId;
	}

	public void setApprovalPathModuleId(Integer approvalPathModuleId) {
		this.approvalPathModuleId = approvalPathModuleId;
	}

	@Column(name = "approval_path_transaction_id")
	public Integer getApprovalPathTransactionId() {
		return this.approvalPathTransactionId;
	}

	public void setApprovalPathTransactionId(Integer approvalPathTransactionId) {
		this.approvalPathTransactionId = approvalPathTransactionId;
	}

	@Column(name = "no_approval_required", length = 2)
	public String getNoApprovalRequired() {
		return this.noApprovalRequired;
	}

	public void setNoApprovalRequired(String noApprovalRequired) {
		this.noApprovalRequired = noApprovalRequired;
	}

	@Column(name = "no_of_approval_levels")
	public Integer getNoOfApprovalLevels() {
		return this.noOfApprovalLevels;
	}

	public void setNoOfApprovalLevels(Integer noOfApprovalLevels) {
		this.noOfApprovalLevels = noOfApprovalLevels;
	}

	@Column(name = "is_active", length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applicationApprovalPath")
	public Set<ApplicationApprovalPathFlow> getApplicationApprovalPathFlows() {
		return this.applicationApprovalPathFlows;
	}

	public void setApplicationApprovalPathFlows(Set<ApplicationApprovalPathFlow> applicationApprovalPathFlows) {
		this.applicationApprovalPathFlows = applicationApprovalPathFlows;
	}

}
