package com.Ntranga.core.CLMS.entities;
// Generated Mar 6, 2017 5:28:55 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApplicationTracker generated by hbm2java
 */
@Entity
@Table(name = "application_tracker")
public class ApplicationTracker implements java.io.Serializable {

	private Integer applicationTrackerId;
	private String applicationTrackerCode;
	private String applicationType;
	private int applicationId;
	private Integer fromRoleId;
	private Integer fromUserId;
	private Integer toRoleId;
	private Integer toUserId;
	private String applicationStatus;
	private String remarks;

	public ApplicationTracker() {
	}

	public ApplicationTracker(String applicationTrackerCode, String applicationType, int applicationId) {
		this.applicationTrackerCode = applicationTrackerCode;
		this.applicationType = applicationType;
		this.applicationId = applicationId;
	}

	public ApplicationTracker(String applicationTrackerCode, String applicationType, int applicationId,
			Integer fromRoleId, Integer fromUserId, Integer toRoleId, Integer toUserId, String applicationStatus, String remarks) {
		this.applicationTrackerCode = applicationTrackerCode;
		this.applicationType = applicationType;
		this.applicationId = applicationId;
		this.fromRoleId = fromRoleId;
		this.fromUserId = fromUserId;
		this.toRoleId = toRoleId;
		this.toUserId = toUserId;
		this.applicationStatus = applicationStatus;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "application_tracker_id", unique = true, nullable = false)
	public Integer getApplicationTrackerId() {
		return this.applicationTrackerId;
	}

	public void setApplicationTrackerId(Integer applicationTrackerId) {
		this.applicationTrackerId = applicationTrackerId;
	}

	@Column(name = "application_tracker_code", nullable = false, length = 150)
	public String getApplicationTrackerCode() {
		return this.applicationTrackerCode;
	}

	public void setApplicationTrackerCode(String applicationTrackerCode) {
		this.applicationTrackerCode = applicationTrackerCode;
	}

	@Column(name = "application_type", nullable = false, length = 100)
	public String getApplicationType() {
		return this.applicationType;
	}

	public void setApplicationType(String applicationType) {
		this.applicationType = applicationType;
	}

	@Column(name = "application_id", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "from_role_id")
	public Integer getFromRoleId() {
		return this.fromRoleId;
	}

	public void setFromRoleId(Integer fromRoleId) {
		this.fromRoleId = fromRoleId;
	}

	@Column(name = "from_user_id")
	public Integer getFromUserId() {
		return this.fromUserId;
	}

	public void setFromUserId(Integer fromUserId) {
		this.fromUserId = fromUserId;
	}

	@Column(name = "to_role_id")
	public Integer getToRoleId() {
		return this.toRoleId;
	}

	public void setToRoleId(Integer toRoleId) {
		this.toRoleId = toRoleId;
	}

	@Column(name = "to_user_id")
	public Integer getToUserId() {
		return this.toUserId;
	}

	public void setToUserId(Integer toUserId) {
		this.toUserId = toUserId;
	}

	@Column(name = "application_status", length = 100)
	public String getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	@Column(name = "remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
