package com.Ntranga.core.CLMS.entities;
// default package
// Generated Feb 1, 2017 2:43:57 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApprovalPathTransactionInfo generated by hbm2java
 */
@Entity
@Table(name = "approval_path_transaction_info")
public class ApprovalPathTransactionInfo implements java.io.Serializable {

	private Integer approvalPathTransactionInfoId;
	private ApprovalPathTransaction approvalPathTransaction;
	private String transactionName;
	private Date effectiveDate;
	private Integer sequenceId;
	private Integer createdBy;
	private Date createdDate;
	private Integer modifiedBy;
	private Date modifiedDate;

	public ApprovalPathTransactionInfo() {
	}

	public ApprovalPathTransactionInfo(ApprovalPathTransaction approvalPathTransaction, String transactionName,
			Date effectiveDate, Integer sequenceId) {
		this.approvalPathTransaction = approvalPathTransaction;
		this.transactionName = transactionName;
		this.effectiveDate = effectiveDate;
		this.sequenceId = sequenceId;
	}

	public ApprovalPathTransactionInfo(ApprovalPathTransaction approvalPathTransaction, String transactionName,
			Date effectiveDate, Integer sequenceId, Integer createdBy, Date createdDate, Integer modifiedBy,
			Date modifiedDate) {
		this.approvalPathTransaction = approvalPathTransaction;
		this.transactionName = transactionName;
		this.effectiveDate = effectiveDate;
		this.sequenceId = sequenceId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "approval_path_transaction_info_id", unique = true, nullable = false)
	public Integer getApprovalPathTransactionInfoId() {
		return this.approvalPathTransactionInfoId;
	}

	public void setApprovalPathTransactionInfoId(Integer approvalPathTransactionInfoId) {
		this.approvalPathTransactionInfoId = approvalPathTransactionInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approval_path_transaction_id", nullable = false)
	public ApprovalPathTransaction getApprovalPathTransaction() {
		return this.approvalPathTransaction;
	}

	public void setApprovalPathTransaction(ApprovalPathTransaction approvalPathTransaction) {
		this.approvalPathTransaction = approvalPathTransaction;
	}

	@Column(name = "transaction_name", nullable = false, length = 100)
	public String getTransactionName() {
		return this.transactionName;
	}

	public void setTransactionName(String transactionName) {
		this.transactionName = transactionName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_date", nullable = false, length = 10)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "sequence_id", nullable = false)
	public Integer getSequenceId() {
		return this.sequenceId;
	}

	public void setSequenceId(Integer sequenceId) {
		this.sequenceId = sequenceId;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
