package com.Ntranga.core.CLMS.entities;
// default package
// Generated Feb 1, 2017 2:43:57 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApprovalPathTransaction generated by hbm2java
 */
@Entity
@Table(name = "approval_path_transaction")
public class ApprovalPathTransaction implements java.io.Serializable {

	private Integer approvalPathTransactionId;
	private ApprovalPathModule approvalPathModule;
	private String transactionCode;
	private Integer customerId;
	private Integer companyId;
	private String isActive;
	private Integer createdBy;
	private Date createdDate;
	private Integer modifiedBy;
	private Date modifiedDate;
	private Set<ApprovalPathTransactionInfo> approvalPathTransactionInfos = new HashSet<ApprovalPathTransactionInfo>(0);

	public ApprovalPathTransaction() {
	}

	public ApprovalPathTransaction(String transactionCode, String isActive) {
		this.transactionCode = transactionCode;
		this.isActive = isActive;
	}

	public ApprovalPathTransaction(ApprovalPathModule approvalPathModule, String transactionCode, Integer customerId,
			Integer companyId, String isActive, Integer createdBy, Date createdDate, Integer modifiedBy,
			Date modifiedDate, Set<ApprovalPathTransactionInfo> approvalPathTransactionInfos) {
		this.approvalPathModule = approvalPathModule;
		this.transactionCode = transactionCode;
		this.customerId = customerId;
		this.companyId = companyId;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.approvalPathTransactionInfos = approvalPathTransactionInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "approval_path_transaction_id", unique = true, nullable = false)
	public Integer getApprovalPathTransactionId() {
		return this.approvalPathTransactionId;
	}

	public void setApprovalPathTransactionId(Integer approvalPathTransactionId) {
		this.approvalPathTransactionId = approvalPathTransactionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approval_path_module_id")
	public ApprovalPathModule getApprovalPathModule() {
		return this.approvalPathModule;
	}

	public void setApprovalPathModule(ApprovalPathModule approvalPathModule) {
		this.approvalPathModule = approvalPathModule;
	}

	@Column(name = "transaction_code", nullable = false, length = 250)
	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "is_active", nullable = false, length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvalPathTransaction")
	public Set<ApprovalPathTransactionInfo> getApprovalPathTransactionInfos() {
		return this.approvalPathTransactionInfos;
	}

	public void setApprovalPathTransactionInfos(Set<ApprovalPathTransactionInfo> approvalPathTransactionInfos) {
		this.approvalPathTransactionInfos = approvalPathTransactionInfos;
	}

}
