package com.Ntranga.core.CLMS.entities;
// default package
// Generated Feb 1, 2017 2:43:57 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApprovalPathModule generated by hbm2java
 */
@Entity
@Table(name = "approval_path_module")
public class ApprovalPathModule implements java.io.Serializable {

	private Integer approvalPathModuleId;
	private String moduleCode;
	private String moduleName;
	private Integer customerId;
	private Integer companyId;
	private String isActive;
	private Integer createdBy;
	private Date createdDate;
	private Integer modifiedBy;
	private Date modifiedDate;
	private Set<ApprovalPathTransaction> approvalPathTransactions = new HashSet<ApprovalPathTransaction>(0);

	public ApprovalPathModule() {
	}
	
	public ApprovalPathModule(Integer approvalPathModuleId) {
		this.approvalPathModuleId = approvalPathModuleId;
	}

	public ApprovalPathModule(String moduleCode, String moduleName, String isActive) {
		this.moduleCode = moduleCode;
		this.moduleName = moduleName;
		this.isActive = isActive;
	}

	public ApprovalPathModule(String moduleCode, String moduleName, Integer customerId, Integer companyId,
			String isActive, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate,
			Set<ApprovalPathTransaction> approvalPathTransactions) {
		this.moduleCode = moduleCode;
		this.moduleName = moduleName;
		this.customerId = customerId;
		this.companyId = companyId;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.approvalPathTransactions = approvalPathTransactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "approval_path_module_id", unique = true, nullable = false)
	public Integer getApprovalPathModuleId() {
		return this.approvalPathModuleId;
	}

	public void setApprovalPathModuleId(Integer approvalPathModuleId) {
		this.approvalPathModuleId = approvalPathModuleId;
	}

	@Column(name = "module_code", nullable = false, length = 250)
	public String getModuleCode() {
		return this.moduleCode;
	}

	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode;
	}

	@Column(name = "module_name", nullable = false, length = 250)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "is_active", nullable = false, length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "approvalPathModule")
	public Set<ApprovalPathTransaction> getApprovalPathTransactions() {
		return this.approvalPathTransactions;
	}

	public void setApprovalPathTransactions(Set<ApprovalPathTransaction> approvalPathTransactions) {
		this.approvalPathTransactions = approvalPathTransactions;
	}

}
