package com.Ntranga.core.CLMS.entities;
// Generated Aug 18, 2016 1:10:14 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssignShiftPattern generated by hbm2java
 */
@Entity
@Table(name="Assign_Shift_Pattern")
public class AssignShiftPattern  implements java.io.Serializable {


     private Integer assignShiftPatternId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private VendorDetails vendorDetails; 
     private WorkrorderDetail workrorderDetail;
     private LocationDetails locationDetails;
     private DepartmentDetails departmentDetails;
     private PlantDetails plantDetails;
     private SectionDetails sectionDetails;
     private WorkAreaDetails workAreaDetails;
     private String shiftPatternCode;
     private WorkerDetails workerDetails;
     private Date patternStartDate;     
     private String isActive;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public AssignShiftPattern() {
    }

    
	   
   
     @Id @GeneratedValue(strategy=IDENTITY)
 	
 	 @Column(name="Assign_Shift_Pattern_Id", unique=true, nullable=false)
 	public Integer getAssignShiftPatternId() {
		return assignShiftPatternId;
	}
	public void setAssignShiftPatternId(Integer assignShiftPatternId) {
		this.assignShiftPatternId = assignShiftPatternId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }


@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }
    
    @Column(name="Is_Active")
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WorkOrder_id")
    public WorkrorderDetail getWorkrorderDetail() {
        return this.workrorderDetail;
    }
    
    public void setWorkrorderDetail(WorkrorderDetail workrorderDetail) {
        this.workrorderDetail = workrorderDetail;
    }

    @ManyToOne(fetch= FetchType.LAZY)
	@JoinColumn(name="Location_Id")
	public LocationDetails getLocationDetails() {
		return locationDetails;
	}

	public void setLocationDetails(LocationDetails locationDetails) {
		this.locationDetails = locationDetails;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	 @JoinColumn(name="Department_Id")
	public DepartmentDetails getDepartmentDetails() {
		return departmentDetails;
	}

	public void setDepartmentDetails(DepartmentDetails departmentId) {
		this.departmentDetails = departmentId;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="Plant_Id")	
	public PlantDetails getPlantDetails() {
		return plantDetails;
	}

	public void setPlantDetails(PlantDetails privateDetails) {
		this.plantDetails = privateDetails;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="Work_Area_Id")	
	public WorkAreaDetails getWorkAreaDetails() {
		return workAreaDetails;
	}

	public void setWorkAreaDetails(WorkAreaDetails workAreaDetails) {
		this.workAreaDetails = workAreaDetails;
	}

	 @Column(name="Shift_Pattern_Code", nullable=false, length=45)
	public String getShiftPatternCode() {
		return shiftPatternCode;
	}
	public void setShiftPatternCode(String shiftPatternCode) {
		this.shiftPatternCode = shiftPatternCode;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="Pattern_Start_Date", nullable=false, length=19)
	public Date getPatternStartDate() {
		return patternStartDate;
	}
	public void setPatternStartDate(Date patternStartDate) {
		this.patternStartDate = patternStartDate;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_id")
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="Section_Id")	
	public SectionDetails getSectionDetails() {
		return sectionDetails;
	}
	
	
	public void setSectionDetails(SectionDetails sectionDetails) {
		this.sectionDetails = sectionDetails;
	}
	
	
}


