package com.Ntranga.core.CLMS.entities;
// Generated 22 Jul, 2016 6:02:08 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditModeControl generated by hbm2java
 */
@Entity
@Table(name="audit_mode_control"

)
public class AuditModeControl  implements java.io.Serializable {


     private Integer auditId;
     private int customerId;
     private int companyId;
     private int locationId;
     private int countryId;
     private String auditStatus;
     private Date startDate;
     private Date endDate;
     private String comments;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public AuditModeControl() {
    }

	
    public AuditModeControl(int customerId, int companyId, int locationId, int countryId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.customerId = customerId;
        this.companyId = companyId;
        this.locationId = locationId;
        this.countryId = countryId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public AuditModeControl(int customerId, int companyId, int locationId, int countryId, String auditStatus, Date startDate, Date endDate, String comments, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.customerId = customerId;
       this.companyId = companyId;
       this.locationId = locationId;
       this.countryId = countryId;
       this.auditStatus = auditStatus;
       this.startDate = startDate;
       this.endDate = endDate;
       this.comments = comments;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Audit_Id", unique=true, nullable=false)
    public Integer getAuditId() {
        return this.auditId;
    }
    
    public void setAuditId(Integer auditId) {
        this.auditId = auditId;
    }

    
    @Column(name="Customer_Id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Company_Id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="Location_Id", nullable=false)
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="Audit_Status", length=45)
    public String getAuditStatus() {
        return this.auditStatus;
    }
    
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Start_Date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="End_Date", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="Comments", length=45)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


