package com.Ntranga.core.CLMS.entities;
// Generated Jun 22, 2016 6:05:32 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyProfile generated by hbm2java
 */
@Entity
@Table(name="company_profile")


public class CompanyProfile  implements java.io.Serializable {
	
	 private Integer companyProfileId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private Integer sequenceId;
     private String isActive;
     private Integer defaultCurrencyId;
     private Integer officialLanguageId;
     private Character isMultiLanguage;
     private Character isMultiCurrency;
     private Integer minAge;
     private Integer maxAge;
     private Integer retireAge;
     private Integer workWeekStartId;
     private Integer workWeekEndId;
     private Integer numberOfWorkingDays;
     private Integer bussinessHoursPerDay;
     private Integer standarHoursPerWeek;
     private String bussinessStartTime;
     private String bussinessEndTime;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;
     private Set<CompanyCurrency> companyCurrencies = new HashSet<CompanyCurrency>(0);
     private Set<CompanyLanguages> companyLanguageses = new HashSet<CompanyLanguages>(0);

    public CompanyProfile() {
    }

    public CompanyProfile(Integer companyProfileId) {
        this.companyProfileId = companyProfileId;
    }
	
    public CompanyProfile(CustomerDetails customerDetails, CompanyDetails companyDetails, Integer sequenceId, Integer defaultCurrencyId, Integer officialLanguageId, Integer minAge, Integer maxAge, Integer retireAge, Integer workWeekStartId, Integer workWeekEndId, Integer numberOfWorkingDays, Integer bussinessHoursPerDay, Integer standarHoursPerWeek, String bussinessStartTime, String bussinessEndTime) {
        this.customerDetails = customerDetails;
        this.companyDetails = companyDetails;
        this.sequenceId = sequenceId;
        this.defaultCurrencyId = defaultCurrencyId;
        this.officialLanguageId = officialLanguageId;
        this.minAge = minAge;
        this.maxAge = maxAge;
        this.retireAge = retireAge;
        this.workWeekStartId = workWeekStartId;
        this.workWeekEndId = workWeekEndId;
        this.numberOfWorkingDays = numberOfWorkingDays;
        this.bussinessHoursPerDay = bussinessHoursPerDay;
        this.standarHoursPerWeek = standarHoursPerWeek;
        this.bussinessStartTime = bussinessStartTime;
        this.bussinessEndTime = bussinessEndTime;
    }
    public CompanyProfile(CustomerDetails customerDetails, CompanyDetails companyDetails, Integer sequenceId, String isActive, Integer defaultCurrencyId, Integer officialLanguageId, Character isMultiLanguage, Character isMultiCurrency, Integer minAge, Integer maxAge, Integer retireAge, Integer workWeekStartId, Integer workWeekEndId, Integer numberOfWorkingDays, Integer bussinessHoursPerDay, Integer standarHoursPerWeek, String bussinessStartTime, String bussinessEndTime, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate, Set<CompanyCurrency> companyCurrencies, Set<CompanyLanguages> companyLanguageses) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.sequenceId = sequenceId;
       this.isActive = isActive;
       this.defaultCurrencyId = defaultCurrencyId;
       this.officialLanguageId = officialLanguageId;
       this.isMultiLanguage = isMultiLanguage;
       this.isMultiCurrency = isMultiCurrency;
       this.minAge = minAge;
       this.maxAge = maxAge;
       this.retireAge = retireAge;
       this.workWeekStartId = workWeekStartId;
       this.workWeekEndId = workWeekEndId;
       this.numberOfWorkingDays = numberOfWorkingDays;
       this.bussinessHoursPerDay = bussinessHoursPerDay;
       this.standarHoursPerWeek = standarHoursPerWeek;
       this.bussinessStartTime = bussinessStartTime;
       this.bussinessEndTime = bussinessEndTime;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.companyCurrencies = companyCurrencies;
       this.companyLanguageses = companyLanguageses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Company_Profile_Id", unique=true, nullable=false)
    public Integer getCompanyProfileId() {
        return this.companyProfileId;
    }
    
    public void setCompanyProfileId(Integer companyProfileId) {
        this.companyProfileId = companyProfileId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public Integer getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Is_Active", length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Default_Currency_Id", nullable=false)
    public Integer getDefaultCurrencyId() {
        return this.defaultCurrencyId;
    }
    
    public void setDefaultCurrencyId(Integer defaultCurrencyId) {
        this.defaultCurrencyId = defaultCurrencyId;
    }

    
    @Column(name="Official_Language_Id", nullable=false)
    public Integer getOfficialLanguageId() {
        return this.officialLanguageId;
    }
    
    public void setOfficialLanguageId(Integer officialLanguageId) {
        this.officialLanguageId = officialLanguageId;
    }

    
    @Column(name="Is_Multi_Language", length=1)
    public Character getIsMultiLanguage() {
        return this.isMultiLanguage;
    }
    
    public void setIsMultiLanguage(Character isMultiLanguage) {
        this.isMultiLanguage = isMultiLanguage;
    }

    
    @Column(name="Is_Multi_Currency", length=1)
    public Character getIsMultiCurrency() {
        return this.isMultiCurrency;
    }
    
    public void setIsMultiCurrency(Character isMultiCurrency) {
        this.isMultiCurrency = isMultiCurrency;
    }

    
    @Column(name="Min_age", nullable=false)
    public Integer getMinAge() {
        return this.minAge;
    }
    
    public void setMinAge(Integer minAge) {
        this.minAge = minAge;
    }

    
    @Column(name="Max_Age", nullable=false)
    public Integer getMaxAge() {
        return this.maxAge;
    }
    
    public void setMaxAge(Integer maxAge) {
        this.maxAge = maxAge;
    }

    
    @Column(name="Retire_Age", nullable=false)
    public Integer getRetireAge() {
        return this.retireAge;
    }
    
    public void setRetireAge(Integer retireAge) {
        this.retireAge = retireAge;
    }

    
    @Column(name="Work_Week_Start_Id", nullable=false)
    public Integer getWorkWeekStartId() {
        return this.workWeekStartId;
    }
    
    public void setWorkWeekStartId(Integer workWeekStartId) {
        this.workWeekStartId = workWeekStartId;
    }

    
    @Column(name="Work_Week_End_Id", nullable=false)
    public Integer getWorkWeekEndId() {
        return this.workWeekEndId;
    }
    
    public void setWorkWeekEndId(Integer workWeekEndId) {
        this.workWeekEndId = workWeekEndId;
    }

    
    @Column(name="Number_Of_Working_Days", nullable=false)
    public Integer getNumberOfWorkingDays() {
        return this.numberOfWorkingDays;
    }
    
    public void setNumberOfWorkingDays(Integer numberOfWorkingDays) {
        this.numberOfWorkingDays = numberOfWorkingDays;
    }

    
    @Column(name="Bussiness_Hours_Per_Day", nullable=false)
    public Integer getBussinessHoursPerDay() {
        return this.bussinessHoursPerDay;
    }
    
    public void setBussinessHoursPerDay(Integer bussinessHoursPerDay) {
        this.bussinessHoursPerDay = bussinessHoursPerDay;
    }

    
    @Column(name="Standar_Hours_Per_Week", nullable=false)
    public Integer getStandarHoursPerWeek() {
        return this.standarHoursPerWeek;
    }
    
    public void setStandarHoursPerWeek(Integer standarHoursPerWeek) {
        this.standarHoursPerWeek = standarHoursPerWeek;
    }

    
    @Column(name="Bussiness_Start_Time", nullable=false, length=10)
    public String getBussinessStartTime() {
        return this.bussinessStartTime;
    }
    
    public void setBussinessStartTime(String bussinessStartTime) {
        this.bussinessStartTime = bussinessStartTime;
    }

    
    @Column(name="Bussiness_End_Time", nullable=false, length=10)
    public String getBussinessEndTime() {
        return this.bussinessEndTime;
    }
    
    public void setBussinessEndTime(String bussinessEndTime) {
        this.bussinessEndTime = bussinessEndTime;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companyProfile")
    public Set<CompanyCurrency> getCompanyCurrencies() {
        return this.companyCurrencies;
    }
    
    public void setCompanyCurrencies(Set<CompanyCurrency> companyCurrencies) {
        this.companyCurrencies = companyCurrencies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companyProfile")
    public Set<CompanyLanguages> getCompanyLanguageses() {
        return this.companyLanguageses;
    }
    
    public void setCompanyLanguageses(Set<CompanyLanguages> companyLanguageses) {
        this.companyLanguageses = companyLanguageses;
    }



}


