package com.Ntranga.core.CLMS.entities;
// Generated Jun 17, 2016 10:42:43 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyLanguages generated by hbm2java
 */
@Entity
@Table(name="company_languages"
    
)
public class CompanyLanguages  implements java.io.Serializable {


     private Integer companyLanaguageId;
     private CompanyProfile companyProfile;
     private int languageId;
     private int sequenceId;
     private String isActive;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public CompanyLanguages() {
    }

	
    public CompanyLanguages(CompanyProfile companyProfile, int languageId, int sequenceId) {
        this.companyProfile = companyProfile;
        this.languageId = languageId;
        this.sequenceId = sequenceId;
    }
    public CompanyLanguages(CompanyProfile companyProfile, int languageId, int sequenceId, String isActive, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.companyProfile = companyProfile;
       this.languageId = languageId;
       this.sequenceId = sequenceId;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Company_Lanaguage_Id", unique=true, nullable=false)
    public Integer getCompanyLanaguageId() {
        return this.companyLanaguageId;
    }
    
    public void setCompanyLanaguageId(Integer companyLanaguageId) {
        this.companyLanaguageId = companyLanaguageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Profile_Id", nullable=false)
    public CompanyProfile getCompanyProfile() {
        return this.companyProfile;
    }
    
    public void setCompanyProfile(CompanyProfile companyProfile) {
        this.companyProfile = companyProfile;
    }

    
    @Column(name="Language_Id", nullable=false)
    public int getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(int languageId) {
        this.languageId = languageId;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Is_Active", length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }



}


