package com.Ntranga.core.CLMS.entities;
// Generated Jun 17, 2016 10:42:43 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyCurrency generated by hbm2java
 */
@Entity
@Table(name="company_currency"
    
)
public class CompanyCurrency  implements java.io.Serializable {


     private Integer companyCurrencyId;
     private CompanyProfile companyProfile;
     private int currencyId;
     private int sequenceId;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public CompanyCurrency() {
    }

	
    public CompanyCurrency(CompanyProfile companyProfile, int currencyId, int sequenceId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.companyProfile = companyProfile;
        this.currencyId = currencyId;
        this.sequenceId = sequenceId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public CompanyCurrency(CompanyProfile companyProfile, int currencyId, int sequenceId, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.companyProfile = companyProfile;
       this.currencyId = currencyId;
       this.sequenceId = sequenceId;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Company_Currency_Id", unique=true, nullable=false)
    public Integer getCompanyCurrencyId() {
        return this.companyCurrencyId;
    }
    
    public void setCompanyCurrencyId(Integer companyCurrencyId) {
        this.companyCurrencyId = companyCurrencyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Profile_Id", nullable=false)
    public CompanyProfile getCompanyProfile() {
        return this.companyProfile;
    }
    
    public void setCompanyProfile(CompanyProfile companyProfile) {
        this.companyProfile = companyProfile;
    }

    
    @Column(name="Currency_Id", nullable=false)
    public int getCurrencyId() {
        return this.currencyId;
    }
    
    public void setCurrencyId(int currencyId) {
        this.currencyId = currencyId;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Is_Active", length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }


}


