package com.Ntranga.core.CLMS.entities;
// Generated Jun 16, 2016 7:00:29 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerDetailsInfo generated by hbm2java
 */
@Entity
@Table(name="customer_details_info"
    
)
public class CustomerDetailsInfo  implements java.io.Serializable {


     private Integer customerInfoId;
     private CustomerDetails customerDetails;
     private String customerName;
     private int customerSequenceId;
     private String customerNameOtherLanguage;
     private String entityType;
     private String isMultinaional;
     private Integer numberOfCompanies;
     private Date transactionDate;
     private String legacyName;
     private Integer countryId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private String isActive;

    public CustomerDetailsInfo() {
    }

	
    public CustomerDetailsInfo(CustomerDetails customerDetails, String customerName, int customerSequenceId, String entityType, String isMultinaional, Date transactionDate, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, String isActive) {
        this.customerDetails = customerDetails;
        this.customerName = customerName;
        this.customerSequenceId = customerSequenceId;
        this.entityType = entityType;
        this.isMultinaional = isMultinaional;
        this.transactionDate = transactionDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.isActive = isActive;
    }
    public CustomerDetailsInfo(CustomerDetails customerDetails, String customerName, int customerSequenceId, String customerNameOtherLanguage, String entityType, String isMultinaional, Integer numberOfCompanies, Date transactionDate, String legacyName, Integer countryId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, String isActive) {
       this.customerDetails = customerDetails;
       this.customerName = customerName;
       this.customerSequenceId = customerSequenceId;
       this.customerNameOtherLanguage = customerNameOtherLanguage;
       this.entityType = entityType;
       this.isMultinaional = isMultinaional;
       this.numberOfCompanies = numberOfCompanies;
       this.transactionDate = transactionDate;
       this.legacyName = legacyName;
       this.countryId = countryId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Customer_Info_Id", unique=true, nullable=false)
    public Integer getCustomerInfoId() {
        return this.customerInfoId;
    }
    
    public void setCustomerInfoId(Integer customerInfoId) {
        this.customerInfoId = customerInfoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

    
    @Column(name="Customer_Name", nullable=false, length=50)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="Customer_Sequence_Id", nullable=false)
    public int getCustomerSequenceId() {
        return this.customerSequenceId;
    }
    
    public void setCustomerSequenceId(int customerSequenceId) {
        this.customerSequenceId = customerSequenceId;
    }

    
    @Column(name="Customer_Name_Other_Language", length=45)
    public String getCustomerNameOtherLanguage() {
        return this.customerNameOtherLanguage;
    }
    
    public void setCustomerNameOtherLanguage(String customerNameOtherLanguage) {
        this.customerNameOtherLanguage = customerNameOtherLanguage;
    }

    
    @Column(name="Entity_Type", nullable=false, length=45)
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    
    @Column(name="Is_Multinaional", length=45)
    public String getIsMultinaional() {
        return this.isMultinaional;
    }
    
    public void setIsMultinaional(String isMultinaional) {
        this.isMultinaional = isMultinaional;
    }

    
    @Column(name="Number_Of_Companies")
    public Integer getNumberOfCompanies() {
        return this.numberOfCompanies;
    }
    
    public void setNumberOfCompanies(Integer numberOfCompanies) {
        this.numberOfCompanies = numberOfCompanies;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Legacy_Name", length=45)
    public String getLegacyName() {
        return this.legacyName;
    }
    
    public void setLegacyName(String legacyName) {
        this.legacyName = legacyName;
    }

    
    @Column(name="Country_Id")
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }




}


