package com.Ntranga.core.CLMS.entities;
// Generated Jun 6, 2016 10:44:14 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerIndustrySectorDetails generated by hbm2java
 */
@Entity
@Table(name="customer_industry_sector_details"
    
)
public class CustomerIndustrySectorDetails  implements java.io.Serializable {


     private Integer industrySectorId;
     private CustomerDetails customerDetails;
     private int customerIndustrySequenceId;
     private int industryId;
     private int sectorId;
     private Date transactionDate;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public CustomerIndustrySectorDetails() {
    }

    public CustomerIndustrySectorDetails(CustomerDetails customerDetails, int customerIndustrySequenceId, int industryId, int sectorId, Date transactionDate, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.customerDetails = customerDetails;
       this.customerIndustrySequenceId = customerIndustrySequenceId;
       this.industryId = industryId;
       this.sectorId = sectorId;
       this.transactionDate = transactionDate;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
    public CustomerIndustrySectorDetails(CustomerDetails customerDetails, int industryId, int sectorId, Date transactionDate, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate,String isActive,int customerIndustrySequenceId) {
        this.customerDetails = customerDetails;        
        this.industryId = industryId;
        this.sectorId = sectorId;
        this.transactionDate = transactionDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.isActive = isActive;
        this.customerIndustrySequenceId=customerIndustrySequenceId;
     }
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Industry_Sector_Id", unique=true, nullable=false)
    public Integer getIndustrySectorId() {
        return this.industrySectorId;
    }
    
    public void setIndustrySectorId(Integer industrySectorId) {
        this.industrySectorId = industrySectorId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

    
    @Column(name="CustomerIndustry_Sequence_Id", nullable=false)
    public int getCustomerIndustrySequenceId() {
        return this.customerIndustrySequenceId;
    }
    
    public void setCustomerIndustrySequenceId(int customerIndustrySequenceId) {
        this.customerIndustrySequenceId = customerIndustrySequenceId;
    }

    
    @Column(name="Industry_Id", nullable=false)
    public int getIndustryId() {
        return this.industryId;
    }
    
    public void setIndustryId(int industryId) {
        this.industryId = industryId;
    }

    
    @Column(name="Sector_Id", nullable=false)
    public int getSectorId() {
        return this.sectorId;
    }
    
    public void setSectorId(int sectorId) {
        this.sectorId = sectorId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }



}


