package com.Ntranga.core.CLMS.entities;
// Generated 13 Jun, 2016 1:21:47 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerCountries generated by hbm2java
 */
@Entity
@Table(name="customer_countries"
    
)
public class CustomerCountries  implements java.io.Serializable {


     private Integer customerCountriesId;
     private CustomerDetails customerDetails;
     private Integer countryId;
     private int customerCountriesSequenceId;
     private Date transactionDate;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Integer languageId;
     private Integer currencyId;
     private String baseCompanyName;
     private String noOfCompanies;

    public CustomerCountries() {
    }

	
    public CustomerCountries(CustomerDetails customerDetails, int customerCountriesSequenceId, Date transactionDate, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.customerDetails = customerDetails;
        this.customerCountriesSequenceId = customerCountriesSequenceId;
        this.transactionDate = transactionDate;
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public CustomerCountries(CustomerDetails customerDetails, Integer countryId, int customerCountriesSequenceId, Date transactionDate, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Integer languageId, Integer currencyId, String baseCompanyName, String noOfCompanies) {
       this.customerDetails = customerDetails;
       this.countryId = countryId;
       this.customerCountriesSequenceId = customerCountriesSequenceId;
       this.transactionDate = transactionDate;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.languageId = languageId;
       this.currencyId = currencyId;
       this.baseCompanyName = baseCompanyName;
       this.noOfCompanies = noOfCompanies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Customer_Countries_Id", unique=true, nullable=false)
    public Integer getCustomerCountriesId() {
        return this.customerCountriesId;
    }
    
    public void setCustomerCountriesId(Integer customerCountriesId) {
        this.customerCountriesId = customerCountriesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

    
    @Column(name="Country_Id")
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="Customer_Countries_Sequence_Id", nullable=false)
    public int getCustomerCountriesSequenceId() {
        return this.customerCountriesSequenceId;
    }
    
    public void setCustomerCountriesSequenceId(int customerCountriesSequenceId) {
        this.customerCountriesSequenceId = customerCountriesSequenceId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="Language_Id")
    public Integer getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    
    @Column(name="Currency_Id")
    public Integer getCurrencyId() {
        return this.currencyId;
    }
    
    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    
    @Column(name="Base_Company_Name", length=45)
    public String getBaseCompanyName() {
        return this.baseCompanyName;
    }
    
    public void setBaseCompanyName(String baseCompanyName) {
        this.baseCompanyName = baseCompanyName;
    }

    
    @Column(name="No_Of_Companies", length=45)
    public String getNoOfCompanies() {
        return this.noOfCompanies;
    }
    
    public void setNoOfCompanies(String noOfCompanies) {
        this.noOfCompanies = noOfCompanies;
    }



}


