package com.Ntranga.core.CLMS.entities;
// Generated Jun 17, 2016 10:42:43 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerAddress generated by hbm2java
 */
@Entity
@Table(name="customer_address"
    
)
public class CustomerAddress  implements java.io.Serializable {


     private Integer addressId;
     private MAddressType MAddressType;
     private CustomerDetails customerDetails;
     private int addressUniqueId;
     private int addressSequenceId;
     private String address1;
     private String address2;
     private String address3;
     private int country;
     private int state;
     private String city;
     private int pincode;
     private String isActive;
     private Date transactionDate;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public CustomerAddress() {
    }

	
    public CustomerAddress(MAddressType MAddressType, CustomerDetails customerDetails, int addressUniqueId, int addressSequenceId, String address1, int country, int state, String city, int pincode, String isActive, Date transactionDate, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.MAddressType = MAddressType;
        this.customerDetails = customerDetails;
        this.addressUniqueId = addressUniqueId;
        this.addressSequenceId = addressSequenceId;
        this.address1 = address1;
        this.country = country;
        this.state = state;
        this.city = city;
        this.pincode = pincode;
        this.isActive = isActive;
        this.transactionDate = transactionDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public CustomerAddress(MAddressType MAddressType, CustomerDetails customerDetails, int addressUniqueId, int addressSequenceId, String address1, String address2, String address3, int country, int state, String city, int pincode, String isActive, Date transactionDate, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.MAddressType = MAddressType;
       this.customerDetails = customerDetails;
       this.addressUniqueId = addressUniqueId;
       this.addressSequenceId = addressSequenceId;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.country = country;
       this.state = state;
       this.city = city;
       this.pincode = pincode;
       this.isActive = isActive;
       this.transactionDate = transactionDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Address_Id", unique=true, nullable=false)
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Address_Type_Id", nullable=false)
    public MAddressType getMAddressType() {
        return this.MAddressType;
    }
    
    public void setMAddressType(MAddressType MAddressType) {
        this.MAddressType = MAddressType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

    
    @Column(name="Address_Unique_Id", nullable=false)
    public int getAddressUniqueId() {
        return this.addressUniqueId;
    }
    
    public void setAddressUniqueId(int addressUniqueId) {
        this.addressUniqueId = addressUniqueId;
    }

    
    @Column(name="Address_Sequence_Id", nullable=false)
    public int getAddressSequenceId() {
        return this.addressSequenceId;
    }
    
    public void setAddressSequenceId(int addressSequenceId) {
        this.addressSequenceId = addressSequenceId;
    }

    
    @Column(name="Address_1", nullable=false, length=45)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="Address_2", length=45)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="Address_3", length=45)
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    
    @Column(name="Country", nullable=false)
    public int getCountry() {
        return this.country;
    }
    
    public void setCountry(int country) {
        this.country = country;
    }

    
    @Column(name="State", nullable=false)
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }

    
    @Column(name="City", nullable=false)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Pincode", nullable=false)
    public int getPincode() {
        return this.pincode;
    }
    
    public void setPincode(int pincode) {
        this.pincode = pincode;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }



}


