package com.Ntranga.core.CLMS.entities;
// Generated 12 Aug, 2016 11:37:16 AM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WageDeduction generated by hbm2java
 */
@Entity
@Table(name="Define_Pfrules")
public class DefinePfrules  implements java.io.Serializable {


     private Integer pfrulesId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private int countryId;  
     private Date transactionDate;   
     private String fixedAmountOrPercentage;
     private String employerAmount;
     private String employerAmountType;
     private String employeeAmount;
     private String employeeAmountType;
     private String employerPercentage;
     private String employerPercentageType;
     private String employeePercentage;
     private String employeePercentageType;
     private int sequenceId;
     private String isActive;
     private Date createdDate;
     private int createdBy;
     private Date modifiedDate;
     private int modifiedBy;

    public DefinePfrules() {
    }

	
    public DefinePfrules(CustomerDetails customerDetails, CompanyDetails companyDetails, int countryId, Date transactionDate, int sequenceId, String isActive, Date createdDate, int createdBy, Date modifiedDate, int modifiedBy) {
        this.customerDetails = customerDetails;
        this.companyDetails = companyDetails;
        this.countryId = countryId;      
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.isActive = isActive;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.modifiedDate = modifiedDate;
        this.modifiedBy = modifiedBy;
    }
    public DefinePfrules(CustomerDetails customerDetails, CompanyDetails companyDetails, int countryId, Date transactionDate, String fixedAmountOrPercentage, String employerAmount, String employerAmountType, String employeeAmount, String employeeAmountType, String employerPercentage, String employerPercentageType, String employeePercentage, String employeePercentageType, int sequenceId, String isActive, Date createdDate, int createdBy, Date modifiedDate, int modifiedBy) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.countryId = countryId;      
       this.transactionDate = transactionDate;    
       this.fixedAmountOrPercentage = fixedAmountOrPercentage;
       this.employerAmount = employerAmount;
       this.employerAmountType = employerAmountType;
       this.employeeAmount = employeeAmount;
       this.employeeAmountType = employeeAmountType;
       this.employerPercentage = employerPercentage;
       this.employerPercentageType = employerPercentageType;
       this.employeePercentage = employeePercentage;
       this.employeePercentageType = employeePercentageType;
       this.sequenceId = sequenceId;
       this.isActive = isActive;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.modifiedDate = modifiedDate;
       this.modifiedBy = modifiedBy;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)   
    @Column(name="Pfrules_Id", unique=true, nullable=false)   
     public Integer getPfrulesId() {
		return pfrulesId;
	}


	public void setPfrulesId(Integer pfrulesId) {
		this.pfrulesId = pfrulesId;
	}


@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    
    @Column(name="Fixed_Amount_Or_Percentage", length=45)
    public String getFixedAmountOrPercentage() {
        return this.fixedAmountOrPercentage;
    }
    
    public void setFixedAmountOrPercentage(String fixedAmountOrPercentage) {
        this.fixedAmountOrPercentage = fixedAmountOrPercentage;
    }

    
    @Column(name="Employer_Amount", length=10)
    public String getEmployerAmount() {
        return this.employerAmount;
    }
    
    public void setEmployerAmount(String employerAmount) {
        this.employerAmount = employerAmount;
    }

    
    @Column(name="Employer_Amount_Type", length=10)
    public String getEmployerAmountType() {
        return this.employerAmountType;
    }
    
    public void setEmployerAmountType(String employerAmountType) {
        this.employerAmountType = employerAmountType;
    }

    
    @Column(name="Employee_Amount", length=10)
    public String getEmployeeAmount() {
        return this.employeeAmount;
    }
    
    public void setEmployeeAmount(String employeeAmount) {
        this.employeeAmount = employeeAmount;
    }

    
    @Column(name="Employee_Amount_Type", length=10)
    public String getEmployeeAmountType() {
        return this.employeeAmountType;
    }
    
    public void setEmployeeAmountType(String employeeAmountType) {
        this.employeeAmountType = employeeAmountType;
    }

    
    @Column(name="Employer_Percentage", length=10)
    public String getEmployerPercentage() {
        return this.employerPercentage;
    }
    
    public void setEmployerPercentage(String employerPercentage) {
        this.employerPercentage = employerPercentage;
    }

    
    @Column(name="Employer_Percentage_Type", length=10)
    public String getEmployerPercentageType() {
        return this.employerPercentageType;
    }
    
    public void setEmployerPercentageType(String employerPercentageType) {
        this.employerPercentageType = employerPercentageType;
    }

    
    @Column(name="Employee_Percentage", length=10)
    public String getEmployeePercentage() {
        return this.employeePercentage;
    }
    
    public void setEmployeePercentage(String employeePercentage) {
        this.employeePercentage = employeePercentage;
    }

    
    @Column(name="Employee_Percentage_Type", length=10)
    public String getEmployeePercentageType() {
        return this.employeePercentageType;
    }
    
    public void setEmployeePercentageType(String employeePercentageType) {
        this.employeePercentageType = employeePercentageType;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }




}


