package com.Ntranga.core.CLMS.entities;
// Generated 22 Dec, 2016 12:44:03 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DepartmentwiseWorkerAllocationDetails generated by hbm2java
 */
@Entity
@Table(name="departmentwise_worker_allocation_details"   
)
public class DepartmentwiseWorkerAllocationDetails  implements java.io.Serializable {


     private Integer workerAllocationId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private int transactionId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Set<DepartmentwiseWorkerAllocationDetailsInfo> departmentwiseWorkerAllocationDetailsInfos = new HashSet<DepartmentwiseWorkerAllocationDetailsInfo>(0);
     private Set<DepartmentwiseWorkerAllocationRequirementDetails> departmentwiseWorkerAllocationRequirementDetailses = new HashSet<DepartmentwiseWorkerAllocationRequirementDetails>(0);

    public DepartmentwiseWorkerAllocationDetails() {
    }

	
    public DepartmentwiseWorkerAllocationDetails(int transactionId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.transactionId = transactionId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public DepartmentwiseWorkerAllocationDetails(CustomerDetails customerDetails, CompanyDetails companyDetails, int transactionId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<DepartmentwiseWorkerAllocationDetailsInfo> departmentwiseWorkerAllocationDetailsInfos, Set<DepartmentwiseWorkerAllocationRequirementDetails> departmentwiseWorkerAllocationRequirementDetailses) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.transactionId = transactionId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.departmentwiseWorkerAllocationDetailsInfos = departmentwiseWorkerAllocationDetailsInfos;
       this.departmentwiseWorkerAllocationRequirementDetailses = departmentwiseWorkerAllocationRequirementDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Worker_Allocation_Id", unique=true, nullable=false)
    public Integer getWorkerAllocationId() {
        return this.workerAllocationId;
    }
    
    public void setWorkerAllocationId(Integer workerAllocationId) {
        this.workerAllocationId = workerAllocationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id")
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id")
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Transaction_Id", nullable=false)
    public int getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departmentwiseWorkerAllocationDetails")
    public Set<DepartmentwiseWorkerAllocationDetailsInfo> getDepartmentwiseWorkerAllocationDetailsInfos() {
        return this.departmentwiseWorkerAllocationDetailsInfos;
    }
    
    public void setDepartmentwiseWorkerAllocationDetailsInfos(Set<DepartmentwiseWorkerAllocationDetailsInfo> departmentwiseWorkerAllocationDetailsInfos) {
        this.departmentwiseWorkerAllocationDetailsInfos = departmentwiseWorkerAllocationDetailsInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departmentwiseWorkerAllocationDetails")
    public Set<DepartmentwiseWorkerAllocationRequirementDetails> getDepartmentwiseWorkerAllocationRequirementDetailses() {
        return this.departmentwiseWorkerAllocationRequirementDetailses;
    }
    
    public void setDepartmentwiseWorkerAllocationRequirementDetailses(Set<DepartmentwiseWorkerAllocationRequirementDetails> departmentwiseWorkerAllocationRequirementDetailses) {
        this.departmentwiseWorkerAllocationRequirementDetailses = departmentwiseWorkerAllocationRequirementDetailses;
    }




}


