package com.Ntranga.core.CLMS.entities;
// Generated 22 Dec, 2016 12:44:03 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DepartmentwiseWorkerAllocationRequirementDetails generated by hbm2java
 */
@Entity
@Table(name="departmentwise_worker_allocation_requirement_details"    
)
public class DepartmentwiseWorkerAllocationRequirementDetails  implements java.io.Serializable {


     private Integer workerAllocationRequirementId;
     private CustomerDetails customerDetails;
     private DepartmentwiseWorkerAllocationDetails departmentwiseWorkerAllocationDetails;
     private CompanyDetails companyDetails;
     private String workSkill;
     private Date fromDate;
     private Date toDate;
     private Integer noOfWorkers;
     private Integer rateOrDay;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public DepartmentwiseWorkerAllocationRequirementDetails() {
    }

	
    public DepartmentwiseWorkerAllocationRequirementDetails(DepartmentwiseWorkerAllocationDetails departmentwiseWorkerAllocationDetails) {
        this.departmentwiseWorkerAllocationDetails = departmentwiseWorkerAllocationDetails;
    }
    public DepartmentwiseWorkerAllocationRequirementDetails(CustomerDetails customerDetails, DepartmentwiseWorkerAllocationDetails departmentwiseWorkerAllocationDetails, CompanyDetails companyDetails, String workSkill, Date fromDate, Date toDate, Integer noOfWorkers, Integer rateOrDay, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.customerDetails = customerDetails;
       this.departmentwiseWorkerAllocationDetails = departmentwiseWorkerAllocationDetails;
       this.companyDetails = companyDetails;
       this.workSkill = workSkill;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.noOfWorkers = noOfWorkers;
       this.rateOrDay = rateOrDay;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Worker_Allocation_Requirement_Id", unique=true, nullable=false)
    public Integer getWorkerAllocationRequirementId() {
        return this.workerAllocationRequirementId;
    }
    
    public void setWorkerAllocationRequirementId(Integer workerAllocationRequirementId) {
        this.workerAllocationRequirementId = workerAllocationRequirementId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id")
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_Allocation_Id", nullable=false)
    public DepartmentwiseWorkerAllocationDetails getDepartmentwiseWorkerAllocationDetails() {
        return this.departmentwiseWorkerAllocationDetails;
    }
    
    public void setDepartmentwiseWorkerAllocationDetails(DepartmentwiseWorkerAllocationDetails departmentwiseWorkerAllocationDetails) {
        this.departmentwiseWorkerAllocationDetails = departmentwiseWorkerAllocationDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id")
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Work_Skill", length=45)
    public String getWorkSkill() {
        return this.workSkill;
    }
    
    public void setWorkSkill(String workSkill) {
        this.workSkill = workSkill;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="From_Date", length=10)
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="To_Date", length=10)
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    
    @Column(name="No_Of_Workers")
    public Integer getNoOfWorkers() {
        return this.noOfWorkers;
    }
    
    public void setNoOfWorkers(Integer noOfWorkers) {
        this.noOfWorkers = noOfWorkers;
    }

    
    @Column(name="Rate_Or_Day")
    public Integer getRateOrDay() {
        return this.rateOrDay;
    }
    
    public void setRateOrDay(Integer rateOrDay) {
        this.rateOrDay = rateOrDay;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


