package com.Ntranga.core.CLMS.entities;
// Generated 12 Jul, 2016 6:10:30 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeInformation generated by hbm2java
 */
@Entity
@Table(name="employee_information"   
)
public class EmployeeInformation  implements java.io.Serializable {


     private Integer employeeId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private LocationDetails locationDetails;
     private PlantDetails plantDetails;
     private DepartmentDetails departmentDetails;
     private SectionDetails sectionDetails;
     private WorkAreaDetails workAreaDetails;
     
     private String employeeCode;
     private Date transactionDate;
     private int sequenceId;
     private int uniqueId;
     private String firstName;
     private String middleName;
     private String lastName;
     private String fatherOrSpouse;
     private String fatherOrSpouseName;
     private String panNumber;
     private Date dateOfBirth;
     private String gender;
     private String maritalStatus;
     private String bloodGroup;
     private String phoneNumber;
     private String email;
     private String address1;
     private String address2;
     private String address3;
     private int country;
     private int state;
     private String city;
     private int pincode;
     private String isActive;
     private Integer jobId;  
     private Integer reportingMangerId;
     private Date startDate;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private byte[] photo;
     private Integer employeeCountry;
     private Integer jobTypeId;
     private Integer jobStatusId;

    public EmployeeInformation() {
    }

    public EmployeeInformation(Integer employeeId) {
    	this.employeeId = employeeId;
    }
	
    public EmployeeInformation(CustomerDetails customerDetails, CompanyDetails companyDetails, Date transactionDate, int sequenceId, int uniqueId, String address1, int country, int state, String city, int pincode, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.customerDetails = customerDetails;
        this.companyDetails = companyDetails;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.uniqueId = uniqueId;
        this.address1 = address1;
        this.country = country;
        this.state = state;
        this.city = city;
        this.pincode = pincode;
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public EmployeeInformation(CustomerDetails customerDetails, CompanyDetails companyDetails, LocationDetails locationDetails, String employeeCode, Date transactionDate, int sequenceId, int uniqueId, String firstName, String middleName, String lastName, String fatherOrSpouse, String fatherOrSpouseName, String panNumber, Date dateOfBirth, String gender, String maritalStatus, String bloodGroup, String phoneNumber, String email, String address1, String address2, String address3, int country, int state, String city, int pincode, String isActive, Integer jobId, Integer reportingMangerId, Date startDate, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, byte[] photo, Integer employeeCountry, Integer jobTypeId, Integer jobStatusId) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.locationDetails = locationDetails;
       this.employeeCode = employeeCode;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.uniqueId = uniqueId;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.fatherOrSpouse = fatherOrSpouse;
       this.fatherOrSpouseName = fatherOrSpouseName;
       this.panNumber = panNumber;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.maritalStatus = maritalStatus;
       this.bloodGroup = bloodGroup;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.country = country;
       this.state = state;
       this.city = city;
       this.pincode = pincode;
       this.isActive = isActive;
       this.jobId = jobId;
    
       this.reportingMangerId = reportingMangerId;
       this.startDate = startDate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.photo = photo;
       this.employeeCountry = employeeCountry;
       this.jobTypeId = jobTypeId;
       this.jobStatusId = jobStatusId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Employee_Id", unique=true, nullable=false)
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Location_Id")
    public LocationDetails getLocationDetails() {
        return this.locationDetails;
    }
    
    public void setLocationDetails(LocationDetails locationDetails) {
        this.locationDetails = locationDetails;
    }

    
    @Column(name="Employee_Code", length=45)
    public String getEmployeeCode() {
        return this.employeeCode;
    }
    
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Unique_Id", nullable=false)
    public int getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(int uniqueId) {
        this.uniqueId = uniqueId;
    }

    
    @Column(name="First_Name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="Middle_Name", length=45)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="Last_Name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="Father_Or_Spouse", length=45)
    public String getFatherOrSpouse() {
        return this.fatherOrSpouse;
    }
    
    public void setFatherOrSpouse(String fatherOrSpouse) {
        this.fatherOrSpouse = fatherOrSpouse;
    }

    
    @Column(name="Father_Or_Spouse_Name", length=45)
    public String getFatherOrSpouseName() {
        return this.fatherOrSpouseName;
    }
    
    public void setFatherOrSpouseName(String fatherOrSpouseName) {
        this.fatherOrSpouseName = fatherOrSpouseName;
    }

    
    @Column(name="PAN_Number", length=45)
    public String getPanNumber() {
        return this.panNumber;
    }
    
    public void setPanNumber(String panNumber) {
        this.panNumber = panNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_Of_Birth", length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="Gender", length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="Marital_Status", length=45)
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    
    @Column(name="Blood_Group", length=45)
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    
    @Column(name="Phone_Number", length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="Email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Address_1", nullable=false, length=45)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="Address_2", length=45)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="Address_3", length=45)
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    
    @Column(name="Country")
    public int getCountry() {
        return this.country;
    }
    
    public void setCountry(int country) {
        this.country = country;
    }

    
    @Column(name="State")
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }

    
    @Column(name="City", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Pincode")
    public int getPincode() {
        return this.pincode;
    }
    
    public void setPincode(int pincode) {
        this.pincode = pincode;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Job_Id")
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

   
    @Column(name="Reporting_Manger_id")
    public Integer getReportingMangerId() {
        return this.reportingMangerId;
    }
    
    public void setReportingMangerId(Integer reportingMangerId) {
        this.reportingMangerId = reportingMangerId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Start_Date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="Photo")
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    
    @Column(name="Employee_Country")
    public Integer getEmployeeCountry() {
        return this.employeeCountry;
    }
    
    public void setEmployeeCountry(Integer employeeCountry) {
        this.employeeCountry = employeeCountry;
    }

    
    @Column(name="Job_Type_Id")
    public Integer getJobTypeId() {
        return this.jobTypeId;
    }
    
    public void setJobTypeId(Integer jobTypeId) {
        this.jobTypeId = jobTypeId;
    }

    
    @Column(name="Job_Status_Id")
    public Integer getJobStatusId() {
        return this.jobStatusId;
    }
    
    public void setJobStatusId(Integer jobStatusId) {
        this.jobStatusId = jobStatusId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Plant_Id")
	public PlantDetails getPlantDetails() {
		return plantDetails;
	}

	public void setPlantDetails(PlantDetails plantDetails) {
		this.plantDetails = plantDetails;
	}

	  @ManyToOne(fetch=FetchType.LAZY)
	    @JoinColumn(name="Department_Id")
	public DepartmentDetails getDepartmentDetails() {
		return departmentDetails;
	}

	public void setDepartmentDetails(DepartmentDetails departmentDetails) {
		this.departmentDetails = departmentDetails;
	}

	 @ManyToOne(fetch=FetchType.LAZY)
	    @JoinColumn(name="Section_Id")
	public SectionDetails getSectionDetails() {
		return sectionDetails;
	}

	public void setSectionDetails(SectionDetails sectionDetails) {
		this.sectionDetails = sectionDetails;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Work_Area_Id")
	public WorkAreaDetails getWorkAreaDetails() {
		return workAreaDetails;
	}

	public void setWorkAreaDetails(WorkAreaDetails workAreaDetails) {
		this.workAreaDetails = workAreaDetails;
	}




}


