package com.Ntranga.core.CLMS.entities;
// Generated 3 Nov, 2016 11:49:50 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EsiDetails generated by hbm2java
 */
@Entity
@Table(name="esi_details"
)
public class EsiDetails  implements java.io.Serializable {


     private Integer esiId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private int countryId;
     private Date transactionDate;
     private int sequenceId;
     private int uniqueId;
     private String isActive;
     private String earningSalaryLimit;
     private String employeeContribution;
     private String employerContribution;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public EsiDetails() {
    }

	
    public EsiDetails(CustomerDetails customerDetails, CompanyDetails companyDetails, int countryId, Date transactionDate, int sequenceId, int uniqueId, String isActive) {
        this.customerDetails = customerDetails;
        this.companyDetails = companyDetails;
        this.countryId = countryId;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.uniqueId = uniqueId;
        this.isActive = isActive;
    }
    public EsiDetails(CustomerDetails customerDetails, CompanyDetails companyDetails, int countryId, Date transactionDate, int sequenceId, int uniqueId, String isActive, String earningSalaryLimit, String employeeContribution, String employerContribution, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.countryId = countryId;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.uniqueId = uniqueId;
       this.isActive = isActive;
       this.earningSalaryLimit = earningSalaryLimit;
       this.employeeContribution = employeeContribution;
       this.employerContribution = employerContribution;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     public EsiDetails(Integer esiId2) {
    	 this.esiId = esiId2;
		// TODO Auto-generated constructor stub
	}


	@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Esi_Id", unique=true, nullable=false)
    public Integer getEsiId() {
        return this.esiId;
    }
    
    public void setEsiId(Integer esiId) {
        this.esiId = esiId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Unique_Id", nullable=false)
    public int getUniqueId() {
        return this.uniqueId;
    }
    
    public void setUniqueId(int uniqueId) {
        this.uniqueId = uniqueId;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Earning_Salary_Limit", length=45)
    public String getEarningSalaryLimit() {
        return this.earningSalaryLimit;
    }
    
    public void setEarningSalaryLimit(String earningSalaryLimit) {
        this.earningSalaryLimit = earningSalaryLimit;
    }

    
    @Column(name="Employee_Contribution", length=45)
    public String getEmployeeContribution() {
        return this.employeeContribution;
    }
    
    public void setEmployeeContribution(String employeeContribution) {
        this.employeeContribution = employeeContribution;
    }

    
    @Column(name="Employer_Contribution", length=45)
    public String getEmployerContribution() {
        return this.employerContribution;
    }
    
    public void setEmployerContribution(String employerContribution) {
        this.employerContribution = employerContribution;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_Date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


