package com.Ntranga.core.CLMS.entities;
// Generated 3 Nov, 2016 11:49:50 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EsiSlabDetails generated by hbm2java
 */
@Entity
@Table(name="esi_slab_details")
public class EsiSlabDetails  implements java.io.Serializable {


     private Integer esiSlabId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private int esiUniqueId;
     private int sequenceId;
     private Date transactionDate;
     private String contributionStartMonth;
     private Integer contributionStartMonthYear;
     private String contributionEndMonth;
     private Integer contributionEndMonthYear;
     private String benefitStartMonth;
     private Integer benefitStartMonthYear;
     private String benefitEndMonth;
     private Integer benefitEndMonthYear;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;
     private EsiDetails esiDetails;

    public EsiSlabDetails() {
    }

	
    public EsiSlabDetails(CustomerDetails customerDetails, CompanyDetails companyDetails, int esiUniqueId, int sequenceId, Date transactionDate) {
        this.customerDetails = customerDetails;
        this.companyDetails = companyDetails;
        this.esiUniqueId = esiUniqueId;
        this.sequenceId = sequenceId;
        this.transactionDate = transactionDate;
    }
    public EsiSlabDetails(CustomerDetails customerDetails, CompanyDetails companyDetails, int esiUniqueId, int sequenceId, Date transactionDate, String contributionStartMonth, Integer contributionStartMonthYear, String contributionEndMonth, Integer contributionEndMonthYear, String benefitStartMonth, Integer benefitStartMonthYear, String benefitEndMonth, Integer benefitEndMonthYear, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.esiUniqueId = esiUniqueId;
       this.sequenceId = sequenceId;
       this.transactionDate = transactionDate;
       this.contributionStartMonth = contributionStartMonth;
       this.contributionStartMonthYear = contributionStartMonthYear;
       this.contributionEndMonth = contributionEndMonth;
       this.contributionEndMonthYear = contributionEndMonthYear;
       this.benefitStartMonth = benefitStartMonth;
       this.benefitStartMonthYear = benefitStartMonthYear;
       this.benefitEndMonth = benefitEndMonth;
       this.benefitEndMonthYear = benefitEndMonthYear;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Esi_Slab_Id", unique=true, nullable=false)
    public Integer getEsiSlabId() {
        return this.esiSlabId;
    }
    
    public void setEsiSlabId(Integer esiSlabId) {
        this.esiSlabId = esiSlabId;
    }
    
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Esi_Id", nullable=false)
    public EsiDetails getEsiDetails() {
        return this.esiDetails;
    }
    
    public void setEsiDetails(EsiDetails esiDetails) {
        this.esiDetails = esiDetails;
    }
    
    

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Esi_Unique_Id", nullable=false)
    public int getEsiUniqueId() {
        return this.esiUniqueId;
    }
    
    public void setEsiUniqueId(int esiUniqueId) {
        this.esiUniqueId = esiUniqueId;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Contribution_Start_Month", length=45)
    public String getContributionStartMonth() {
        return this.contributionStartMonth;
    }
    
    public void setContributionStartMonth(String contributionStartMonth) {
        this.contributionStartMonth = contributionStartMonth;
    }

    
    @Column(name="Contribution_Start_Month_Year")
    public Integer getContributionStartMonthYear() {
        return this.contributionStartMonthYear;
    }
    
    public void setContributionStartMonthYear(Integer contributionStartMonthYear) {
        this.contributionStartMonthYear = contributionStartMonthYear;
    }

    
    @Column(name="Contribution_End_Month", length=45)
    public String getContributionEndMonth() {
        return this.contributionEndMonth;
    }
    
    public void setContributionEndMonth(String contributionEndMonth) {
        this.contributionEndMonth = contributionEndMonth;
    }

    
    @Column(name="Contribution_End_Month_Year")
    public Integer getContributionEndMonthYear() {
        return this.contributionEndMonthYear;
    }
    
    public void setContributionEndMonthYear(Integer contributionEndMonthYear) {
        this.contributionEndMonthYear = contributionEndMonthYear;
    }

    
    @Column(name="Benefit_Start_Month", length=45)
    public String getBenefitStartMonth() {
        return this.benefitStartMonth;
    }
    
    public void setBenefitStartMonth(String benefitStartMonth) {
        this.benefitStartMonth = benefitStartMonth;
    }

    
    @Column(name="Benefit_Start_Month_Year")
    public Integer getBenefitStartMonthYear() {
        return this.benefitStartMonthYear;
    }
    
    public void setBenefitStartMonthYear(Integer benefitStartMonthYear) {
        this.benefitStartMonthYear = benefitStartMonthYear;
    }

    
    @Column(name="Benefit_End_Month", length=45)
    public String getBenefitEndMonth() {
        return this.benefitEndMonth;
    }
    
    public void setBenefitEndMonth(String benefitEndMonth) {
        this.benefitEndMonth = benefitEndMonth;
    }

    
    @Column(name="Benefit_End_Month_Year")
    public Integer getBenefitEndMonthYear() {
        return this.benefitEndMonthYear;
    }
    
    public void setBenefitEndMonthYear(Integer benefitEndMonthYear) {
        this.benefitEndMonthYear = benefitEndMonthYear;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


