package com.Ntranga.core.CLMS.entities;
// Generated Jun 6, 2016 10:44:14 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MContactType generated by hbm2java
 */
@Entity
@Table(name="m_contact_type"
    
)
public class MContactType  implements java.io.Serializable {


     private Integer contactTypeId;
     private String contactTypeName;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Set<CustomerContact> customerContacts = new HashSet<CustomerContact>(0);
     private Set<CompanyContact> companyContacts = new HashSet<CompanyContact>(0);

    public MContactType() {
    }

	
    public MContactType(String contactTypeName, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.contactTypeName = contactTypeName;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public MContactType(String contactTypeName, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<CustomerContact> customerContacts, Set<CompanyContact> companyContacts) {
       this.contactTypeName = contactTypeName;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.customerContacts = customerContacts;
       this.companyContacts = companyContacts;
    }
   
     public MContactType(Integer contactTypeId) {
    	 this.contactTypeId = contactTypeId;
	}
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Contact_Type_Id", unique=true, nullable=false)
    public Integer getContactTypeId() {
        return this.contactTypeId;
    }
    
    public void setContactTypeId(Integer contactTypeId) {
        this.contactTypeId = contactTypeId;
    }

    
    @Column(name="Contact_Type_Name", nullable=false, length=45)
    public String getContactTypeName() {
        return this.contactTypeName;
    }
    
    public void setContactTypeName(String contactTypeName) {
        this.contactTypeName = contactTypeName;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MContactType")
    public Set<CustomerContact> getCustomerContacts() {
        return this.customerContacts;
    }
    
    public void setCustomerContacts(Set<CustomerContact> customerContacts) {
        this.customerContacts = customerContacts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MContactType")
    public Set<CompanyContact> getCompanyContacts() {
        return this.companyContacts;
    }
    
    public void setCompanyContacts(Set<CompanyContact> companyContacts) {
        this.companyContacts = companyContacts;
    }




}


