package com.Ntranga.core.CLMS.entities;
// Generated 13 Jun, 2016 1:21:47 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MCountry generated by hbm2java
 */
@Entity
@Table(name="m_country"
    
)
public class MCountry  implements java.io.Serializable {


     private Integer countryId;
     private String countryName;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private String countryCode;
     private Set<MState> MStates = new HashSet<MState>(0);

    public MCountry() {
    }

    public MCountry(Integer countryId) {
    	this.countryId = countryId;
    }
    
    public MCountry(int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public MCountry(String countryName, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, String countryCode, Set<MState> MStates) {
       this.countryName = countryName;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.countryCode = countryCode;
       this.MStates = MStates;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Country_Id", unique=true, nullable=false)
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="Country_Name", length=45)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="Country_Code", length=45)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MCountry")
    public Set<MState> getMStates() {
        return this.MStates;
    }
    
    public void setMStates(Set<MState> MStates) {
        this.MStates = MStates;
    }




}


