package com.Ntranga.core.CLMS.entities;
// Generated Jan 9, 2017 2:21:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MScreenActions generated by hbm2java
 */
@Entity
@Table(name = "m_screen_actions")
public class MScreenActions implements java.io.Serializable {

	private Integer masterScreenActionId;
	private String actionName;
	private String actionDesc;
	private String isActive;
	private int createdBy;
	private Date createdDate;
	private int modifiedBy;
	private Date modifiedDate;
	private Set<ScreenActionsMapping> screenActionsMappings = new HashSet<ScreenActionsMapping>(0);

	public MScreenActions() {
	}

	public MScreenActions(String actionName, String isActive, int createdBy, Date createdDate, int modifiedBy,
			Date modifiedDate) {
		this.actionName = actionName;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}

	public MScreenActions(String actionName, String actionDesc, String isActive, int createdBy, Date createdDate,
			int modifiedBy, Date modifiedDate, Set<ScreenActionsMapping> screenActionsMappings) {
		this.actionName = actionName;
		this.actionDesc = actionDesc;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.screenActionsMappings = screenActionsMappings;
	}

	public MScreenActions(Integer masterScreenActionId) {
		this.masterScreenActionId = masterScreenActionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "master_screen_action_id", unique = true, nullable = false)
	public Integer getMasterScreenActionId() {
		return this.masterScreenActionId;
	}

	public void setMasterScreenActionId(Integer masterScreenActionId) {
		this.masterScreenActionId = masterScreenActionId;
	}

	@Column(name = "action_name", nullable = false, length = 100)
	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	@Column(name = "action_desc", length = 250)
	public String getActionDesc() {
		return this.actionDesc;
	}

	public void setActionDesc(String actionDesc) {
		this.actionDesc = actionDesc;
	}

	@Column(name = "is_active", nullable = false, length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by", nullable = false)
	public int getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(int modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", nullable = false, length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MScreenActions")
	public Set<ScreenActionsMapping> getScreenActionsMappings() {
		return this.screenActionsMappings;
	}

	public void setScreenActionsMappings(Set<ScreenActionsMapping> screenActionsMappings) {
		this.screenActionsMappings = screenActionsMappings;
	}

}
