package com.Ntranga.core.CLMS.entities;
// Generated Jun 6, 2016 10:44:14 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MSector generated by hbm2java
 */
@Entity
@Table(name="m_sector"
    
)
public class MSector  implements java.io.Serializable {


     private Integer sectorId;
     private MIndustry MIndustry;
     private String sectorName;
     private String sectorDescription;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public MSector() {
    }

    public MSector(MIndustry MIndustry, String sectorName, String sectorDescription, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.MIndustry = MIndustry;
       this.sectorName = sectorName;
       this.sectorDescription = sectorDescription;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Sector_Id", unique=true, nullable=false)
    public Integer getSectorId() {
        return this.sectorId;
    }
    
    public void setSectorId(Integer sectorId) {
        this.sectorId = sectorId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Industry_Id")
    public MIndustry getMIndustry() {
        return this.MIndustry;
    }
    
    public void setMIndustry(MIndustry MIndustry) {
        this.MIndustry = MIndustry;
    }

    
    @Column(name="Sector_Name", length=45)
    public String getSectorName() {
        return this.sectorName;
    }
    
    public void setSectorName(String sectorName) {
        this.sectorName = sectorName;
    }

    
    @Column(name="Sector_Description", length=45)
    public String getSectorDescription() {
        return this.sectorDescription;
    }
    
    public void setSectorDescription(String sectorDescription) {
        this.sectorDescription = sectorDescription;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }


}


