package com.Ntranga.core.CLMS.entities;
// Generated Jun 6, 2016 10:44:14 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MState generated by hbm2java
 */
@Entity
@Table(name="m_state"
    
)
public class MState  implements java.io.Serializable {


	private Integer stateId;
    private MCountry MCountry;
    private String stateName;
    private int createdBy;
    private Date createdDate;
    private int modifiedBy;
    private Date modifiedDate;
    private Set<MCity> MCities = new HashSet<MCity>(0);

	public MState() {
	}
	
	public MState(Integer stateId) {
	    	this.stateId = stateId;
	}
	
    public MState(int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public MState(MCountry MCountry, String stateName, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<MCity> MCities) {
       this.MCountry = MCountry;
       this.stateName = stateName;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.MCities = MCities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="State_Id", unique=true, nullable=false)
    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Country_Id")
    public MCountry getMCountry() {
        return this.MCountry;
    }
    
    public void setMCountry(MCountry MCountry) {
        this.MCountry = MCountry;
    }

    
    @Column(name="State_Name", length=45)
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="MState")
    public Set<MCity> getMCities() {
        return this.MCities;
    }
    
    public void setMCities(Set<MCity> MCities) {
        this.MCities = MCities;
    }



}


