package com.Ntranga.core.CLMS.entities;
// Generated Jun 6, 2016 10:44:14 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MUsers generated by hbm2java
 */
@Entity
@Table(name="m_users"
    
)
public class MUsers  implements java.io.Serializable {


     private Integer userId;
     private MRoles MRoles;
     private String userName;
     private String password;
     private String isActive;

    public MUsers() {
    }

    public MUsers(MRoles MRoles, String userName, String password, String isActive) {
       this.MRoles = MRoles;
       this.userName = userName;
       this.password = password;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public MRoles getMRoles() {
        return this.MRoles;
    }
    
    public void setMRoles(MRoles MRoles) {
        this.MRoles = MRoles;
    }

    
    @Column(name="user_name", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="is_active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }



}


