package com.Ntranga.core.CLMS.entities;
// Generated Jun 17, 2016 10:42:43 AM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WageRatesForOT generated by hbm2java
 */
@Entity
@Table(name="Ot_Round_Off_Rules"
    
)
public class OtRoundOffRules implements Serializable {
	
	private Integer otRoundOffRulesId;
	private DefineOverTimeControlDetailsInfo defineOverTimeControlDetailsInfo;
	private String fromMinutes;
    private String toMinutes;
    private String roundOffToMinutes;
    private Integer createdBy;
    private Date createdDate;
    private Integer modifiedBy;
    private Date modifiedDate;
    
	public OtRoundOffRules() {
		
	}
	
	public OtRoundOffRules(Integer otRoundOffRulesId) {
		this.otRoundOffRulesId = otRoundOffRulesId;
	}
	    

	
@Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="Ot_Round_Off_Rules_Id", unique=true, nullable=false)
	public Integer getOtRoundOffRulesId() {
		return otRoundOffRulesId;
	}
	
	public void setOtRoundOffRulesId(Integer otRoundOffRulesId) {
		this.otRoundOffRulesId = otRoundOffRulesId;
	}
	
	 @Column(name="From_Minutes", nullable=false)
	public String getFromMinutes() {
		return fromMinutes;
	}
	
	public void setFromMinutes(String fromMinutes) {
		this.fromMinutes = fromMinutes;
	}
	
	 @Column(name="To_Minutes", nullable=false)
	public String getToMinutes() {
		return toMinutes;
	}
	
	public void setToMinutes(String toMinutes) {
		this.toMinutes = toMinutes;
	}
	
	 @Column(name="Round_Off_To_Minutes", nullable=false)
	public String getRoundOffToMinutes() {
		return roundOffToMinutes;
	}
	
	public void setRoundOffToMinutes(String roundOffToMinutes) {
		this.roundOffToMinutes = roundOffToMinutes;
	}
	
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Define_OverTime_Details_InfoId", nullable=false)
	public DefineOverTimeControlDetailsInfo getDefineOverTimeControlDetailsInfo() {
		return defineOverTimeControlDetailsInfo;
	}
	public void setDefineOverTimeControlDetailsInfo(DefineOverTimeControlDetailsInfo defineOverTimeControlDetailsInfo) {
		this.defineOverTimeControlDetailsInfo = defineOverTimeControlDetailsInfo;
	}
	
	@Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    
    

}
