package com.Ntranga.core.CLMS.entities;
// Generated Jan 9, 2017 2:21:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermissionsGroup generated by hbm2java
 */
@Entity
@Table(name = "permissions_group")
public class PermissionsGroup implements java.io.Serializable {

	private Integer permissionsGroupId;
	private String permissionsGroupName;
	private String permissionsGroupDesc;
	private String isActive;
	private Integer createdBy;
	private Date createdDate;
	private Integer modifiedBy;
	private Date modifiedDate;
	private Set<ScreenPermissionsGroupMapping> screenPermissionsGroupMappings = new HashSet<ScreenPermissionsGroupMapping>(
			0);

	public PermissionsGroup() {
	}

	public PermissionsGroup(String permissionsGroupName, String isActive) {
		this.permissionsGroupName = permissionsGroupName;
		this.isActive = isActive;
	}

	public PermissionsGroup(String permissionsGroupName, String permissionsGroupDesc, String isActive,
			Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate,
			Set<ScreenPermissionsGroupMapping> screenPermissionsGroupMappings) {
		this.permissionsGroupName = permissionsGroupName;
		this.permissionsGroupDesc = permissionsGroupDesc;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.screenPermissionsGroupMappings = screenPermissionsGroupMappings;
	}

	public PermissionsGroup(Integer permissionsGroupId) {
		this.permissionsGroupId = permissionsGroupId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "permissions_group_id", unique = true, nullable = false)
	public Integer getPermissionsGroupId() {
		return this.permissionsGroupId;
	}

	public void setPermissionsGroupId(Integer permissionsGroupId) {
		this.permissionsGroupId = permissionsGroupId;
	}

	@Column(name = "permissions_group_name", nullable = false, length = 100)
	public String getPermissionsGroupName() {
		return this.permissionsGroupName;
	}

	public void setPermissionsGroupName(String permissionsGroupName) {
		this.permissionsGroupName = permissionsGroupName;
	}

	@Column(name = "permissions_group_desc", length = 250)
	public String getPermissionsGroupDesc() {
		return this.permissionsGroupDesc;
	}

	public void setPermissionsGroupDesc(String permissionsGroupDesc) {
		this.permissionsGroupDesc = permissionsGroupDesc;
	}

	@Column(name = "is_active", nullable = false, length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permissionsGroup")
	public Set<ScreenPermissionsGroupMapping> getScreenPermissionsGroupMappings() {
		return this.screenPermissionsGroupMappings;
	}

	public void setScreenPermissionsGroupMappings(Set<ScreenPermissionsGroupMapping> screenPermissionsGroupMappings) {
		this.screenPermissionsGroupMappings = screenPermissionsGroupMappings;
	}

}
