package com.Ntranga.core.CLMS.entities;
// Generated Jan 9, 2017 2:26:37 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ScreenPermissionsGroupMapping generated by hbm2java
 */
@Entity
@Table(name = "screen_permissions_group_mapping")
public class ScreenPermissionsGroupMapping implements java.io.Serializable {

	private Integer screenPermissionsGroupMappingId;
	private PermissionsGroup permissionsGroup;
	private ScreenActionsMapping screenActionsMapping;
	private String isActive;
	
	public ScreenPermissionsGroupMapping() {
	}

	public ScreenPermissionsGroupMapping(PermissionsGroup permissionsGroup, ScreenActionsMapping screenActionsMapping) {
		this.permissionsGroup = permissionsGroup;
		this.screenActionsMapping = screenActionsMapping;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "screen_permissions_group_mapping_id", unique = true, nullable = false)
	public Integer getScreenPermissionsGroupMappingId() {
		return this.screenPermissionsGroupMappingId;
	}

	public void setScreenPermissionsGroupMappingId(Integer screenPermissionsGroupMappingId) {
		this.screenPermissionsGroupMappingId = screenPermissionsGroupMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permissions_group_id", nullable = false)
	public PermissionsGroup getPermissionsGroup() {
		return this.permissionsGroup;
	}

	public void setPermissionsGroup(PermissionsGroup permissionsGroup) {
		this.permissionsGroup = permissionsGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screen_action_mapping_id", nullable = false)
	public ScreenActionsMapping getScreenActionsMapping() {
		return this.screenActionsMapping;
	}

	public void setScreenActionsMapping(ScreenActionsMapping screenActionsMapping) {
		this.screenActionsMapping = screenActionsMapping;
	}
	@Column(name = "is_active", length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}
}
