package com.Ntranga.core.CLMS.entities;
// Generated Jan 9, 2017 2:21:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScreensList generated by hbm2java
 */
@Entity
@Table(name = "screens_list")
public class ScreensList implements java.io.Serializable {

	private Integer screenId;
	private String screenName;
	private String groupName;
	private String isActive;
	private int createdBy;
	private Date createdDate;
	private int modifiedBy;
	private Date modifiedDate;
	private Set<ScreenActionsMapping> screenActionsMappings = new HashSet<ScreenActionsMapping>(0);

	public ScreensList() {
	}

	public ScreensList(String screenName, String groupName, int createdBy, Date createdDate, int modifiedBy,
			Date modifiedDate) {
		this.screenName = screenName;
		this.groupName = groupName;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}

	public ScreensList(String screenName, String groupName, String isActive, int createdBy, Date createdDate,
			int modifiedBy, Date modifiedDate, Set<ScreenActionsMapping> screenActionsMappings) {
		this.screenName = screenName;
		this.groupName = groupName;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.screenActionsMappings = screenActionsMappings;
	}

	public ScreensList(Integer screenId) {
		this.screenId = screenId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "screen_id", unique = true, nullable = false)
	public Integer getScreenId() {
		return this.screenId;
	}

	public void setScreenId(Integer screenId) {
		this.screenId = screenId;
	}

	@Column(name = "screen_name", nullable = false, length = 100)
	public String getScreenName() {
		return this.screenName;
	}

	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}

	@Column(name = "group_name", nullable = false, length = 100)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "is_active", length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "modified_by", nullable = false)
	public int getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(int modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_date", nullable = false, length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "screensList")
	public Set<ScreenActionsMapping> getScreenActionsMappings() {
		return this.screenActionsMappings;
	}

	public void setScreenActionsMappings(Set<ScreenActionsMapping> screenActionsMappings) {
		this.screenActionsMappings = screenActionsMappings;
	}

}
