package com.Ntranga.core.CLMS.entities;
// Generated Jan 9, 2017 2:26:37 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ScreenActionsMapping generated by hbm2java
 */
@Entity
@Table(name = "screen_actions_mapping")
public class ScreenActionsMapping implements java.io.Serializable {

	private Integer screenActionMappingId;
	private MScreenActions MScreenActions;
	private ScreensList screensList;
	private String isActive;
	private Set<ScreenPermissionsGroupMapping> screenPermissionsGroupMappings = new HashSet<ScreenPermissionsGroupMapping>(
			0);

	public ScreenActionsMapping() {
	}

	public ScreenActionsMapping(MScreenActions MScreenActions, ScreensList screensList) {
		this.MScreenActions = MScreenActions;
		this.screensList = screensList;
	}

	public ScreenActionsMapping(MScreenActions MScreenActions, ScreensList screensList,
			Set<ScreenPermissionsGroupMapping> screenPermissionsGroupMappings) {
		this.MScreenActions = MScreenActions;
		this.screensList = screensList;
		this.screenPermissionsGroupMappings = screenPermissionsGroupMappings;
	}

	public ScreenActionsMapping(Integer screenActionMappingId) {
		this.screenActionMappingId = screenActionMappingId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "screen_action_mapping_id", unique = true, nullable = false)
	public Integer getScreenActionMappingId() {
		return this.screenActionMappingId;
	}

	public void setScreenActionMappingId(Integer screenActionMappingId) {
		this.screenActionMappingId = screenActionMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "master_screen_action_id", nullable = false)
	public MScreenActions getMScreenActions() {
		return this.MScreenActions;
	}

	public void setMScreenActions(MScreenActions MScreenActions) {
		this.MScreenActions = MScreenActions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screen_id", nullable = false)
	public ScreensList getScreensList() {
		return this.screensList;
	}

	public void setScreensList(ScreensList screensList) {
		this.screensList = screensList;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "screenActionsMapping")
	public Set<ScreenPermissionsGroupMapping> getScreenPermissionsGroupMappings() {
		return this.screenPermissionsGroupMappings;
	}

	public void setScreenPermissionsGroupMappings(Set<ScreenPermissionsGroupMapping> screenPermissionsGroupMappings) {
		this.screenPermissionsGroupMappings = screenPermissionsGroupMappings;
	}
	@Column(name = "is_active", length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

}
