package com.Ntranga.core.CLMS.entities;
// Generated Jul 8, 2016 9:09:45 AM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShiftsDefine generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="shifts_define" )
public class ShiftsDefine  implements java.io.Serializable {

     private Integer shiftDefineId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private LocationDetails locationDetails;
 	 private PlantDetails plantDetails;
     private int countryId;
     private String shiftCode;
     private Date transactionDate;
     private Integer sequenceId;
     private String isActive;
     private String shiftName;
     private String shiftColor;
     private String startTime;
     private String endTime;
     private String unpaidBreak;
     private String totalHours;
     private String offShift;
     private String halfDayShift;
     private String shiftAllowance;
     private String flexibleShift;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;
     private String isNextDay;
     
    public ShiftsDefine() {
    }

	
    public ShiftsDefine(CustomerDetails customerDetails, CompanyDetails companyDetails, int countryId, Date transactionDate) {
        this.customerDetails = customerDetails;
        this.companyDetails = companyDetails;
        this.countryId = countryId;
        this.transactionDate = transactionDate;
    }
    public ShiftsDefine(CustomerDetails customerDetails, CompanyDetails companyDetails, int countryId, String shiftCode, Date transactionDate, Integer sequenceId, String isActive, String shiftName, String shiftColor, String startTime, String endTime, String unpaidBreak, String totalHours, String offShift, String halfDayShift, String shiftAllowance, String flexibleShift, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate, String isNextDay) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.countryId = countryId;
       this.shiftCode = shiftCode;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.isActive = isActive;
       this.shiftName = shiftName;
       this.shiftColor = shiftColor;
       this.startTime = startTime;
       this.endTime = endTime;
       this.unpaidBreak = unpaidBreak;
       this.totalHours = totalHours;
       this.offShift = offShift;
       this.halfDayShift = halfDayShift;
       this.shiftAllowance = shiftAllowance;
       this.flexibleShift = flexibleShift;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.isNextDay = isNextDay;
    }
   
     public ShiftsDefine(Integer shiftDefineId) {
		this.shiftDefineId = shiftDefineId;
	}


	@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="shift_Define_Id", unique=true, nullable=false)
    public Integer getShiftDefineId() {
        return this.shiftDefineId;
    }
    
    public void setShiftDefineId(Integer shiftDefineId) {
        this.shiftDefineId = shiftDefineId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="Shift_Code", length=20)
    public String getShiftCode() {
        return this.shiftCode;
    }
    
    public void setShiftCode(String shiftCode) {
        this.shiftCode = shiftCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id")
    public Integer getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Is_Active", length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Shift_Name", length=45)
    public String getShiftName() {
        return this.shiftName;
    }
    
    public void setShiftName(String shiftName) {
        this.shiftName = shiftName;
    }

    
    @Column(name="Shift_Color", length=25)
    public String getShiftColor() {
        return this.shiftColor;
    }
    
    public void setShiftColor(String shiftColor) {
        this.shiftColor = shiftColor;
    }

    
    @Column(name="Start_Time", length=25)
    public String getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    
    @Column(name="End_Time", length=25)
    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="Unpaid_Break", length=25)
    public String getUnpaidBreak() {
        return this.unpaidBreak;
    }
    
    public void setUnpaidBreak(String unpaidBreak) {
        this.unpaidBreak = unpaidBreak;
    }

    
    @Column(name="Total_Hours", length=25)
    public String getTotalHours() {
        return this.totalHours;
    }
    
    public void setTotalHours(String totalHours) {
        this.totalHours = totalHours;
    }

    
    @Column(name="OFF_Shift", length=2)
    public String getOffShift() {
        return this.offShift;
    }
    
    public void setOffShift(String offShift) {
        this.offShift = offShift;
    }

    
    @Column(name="Half_Day_Shift", length=2)
    public String getHalfDayShift() {
        return this.halfDayShift;
    }
    
    public void setHalfDayShift(String halfDayShift) {
        this.halfDayShift = halfDayShift;
    }

    
    @Column(name="Shift_Allowance", length=2)
    public String getShiftAllowance() {
        return this.shiftAllowance;
    }
    
    public void setShiftAllowance(String shiftAllowance) {
        this.shiftAllowance = shiftAllowance;
    }

    
    @Column(name="Flexible_Shift", length=2)
    public String getFlexibleShift() {
        return this.flexibleShift;
    }
    
    public void setFlexibleShift(String flexibleShift) {
        this.flexibleShift = flexibleShift;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Created_Date", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Modified_Date", length=10)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="Plant_Id")	
	public PlantDetails getPlantDetails() {
		return plantDetails;
	}

	public void setPlantDetails(PlantDetails plantDetails) {
		this.plantDetails = plantDetails;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="Location_Id")
	public LocationDetails getLocationDetails() {
		return locationDetails;
	}

	public void setLocationDetails(LocationDetails locationDetails) {
		this.locationDetails = locationDetails;
	}

	@Column(name="Is_Next_Day", length = 2)
	public String getIsNextDay() {
		return isNextDay;
	}

	public void setIsNextDay(String isNextDay) {
		this.isNextDay = isNextDay;
	}

}


