package com.Ntranga.core.CLMS.entities;
// Generated 25 Jul, 2016 12:05:41 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeRulesDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="time_rules_details"
  
)
public class TimeRulesDetails  implements java.io.Serializable {


     private Integer timeRuleId;
     private String timeRuleCode;
     private int customerId;
     private int companyId;
     private int countryId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Set<TimeRuleBufferTime> timeRuleBufferTimes = new HashSet<TimeRuleBufferTime>(0);
     private Set<TimeRulesDetailsInfo> timeRulesDetailsInfos = new HashSet<TimeRulesDetailsInfo>(0);
     private Set<TimeRuleWorkDayStatus> timeRuleWorkDayStatuses = new HashSet<TimeRuleWorkDayStatus>(0);

    public TimeRulesDetails() {
    }
    
    public TimeRulesDetails(Integer timeRuleId) {
    	this.timeRuleId = timeRuleId;
    }
	
    public TimeRulesDetails(String timeRuleCode, int customerId, int companyId, int countryId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.timeRuleCode = timeRuleCode;
        this.customerId = customerId;
        this.companyId = companyId;
        this.countryId = countryId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public TimeRulesDetails(String timeRuleCode, int customerId, int companyId, int countryId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<TimeRuleBufferTime> timeRuleBufferTimes, Set<TimeRulesDetailsInfo> timeRulesDetailsInfos, Set<TimeRuleWorkDayStatus> timeRuleWorkDayStatuses) {
       this.timeRuleCode = timeRuleCode;
       this.customerId = customerId;
       this.companyId = companyId;
       this.countryId = countryId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.timeRuleBufferTimes = timeRuleBufferTimes;
       this.timeRulesDetailsInfos = timeRulesDetailsInfos;
       this.timeRuleWorkDayStatuses = timeRuleWorkDayStatuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Time_Rule_Id", unique=true, nullable=false)
    public Integer getTimeRuleId() {
        return this.timeRuleId;
    }
    
    public void setTimeRuleId(Integer timeRuleId) {
        this.timeRuleId = timeRuleId;
    }

    
    @Column(name="Time_Rule_Code", nullable=false, length=45)
    public String getTimeRuleCode() {
        return this.timeRuleCode;
    }
    
    public void setTimeRuleCode(String timeRuleCode) {
        this.timeRuleCode = timeRuleCode;
    }

    
    @Column(name="Customer_Id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Company_Id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="timeRulesDetails")
    public Set<TimeRuleBufferTime> getTimeRuleBufferTimes() {
        return this.timeRuleBufferTimes;
    }
    
    public void setTimeRuleBufferTimes(Set<TimeRuleBufferTime> timeRuleBufferTimes) {
        this.timeRuleBufferTimes = timeRuleBufferTimes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="timeRulesDetails")
    public Set<TimeRulesDetailsInfo> getTimeRulesDetailsInfos() {
        return this.timeRulesDetailsInfos;
    }
    
    public void setTimeRulesDetailsInfos(Set<TimeRulesDetailsInfo> timeRulesDetailsInfos) {
        this.timeRulesDetailsInfos = timeRulesDetailsInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="timeRulesDetails")
    public Set<TimeRuleWorkDayStatus> getTimeRuleWorkDayStatuses() {
        return this.timeRuleWorkDayStatuses;
    }
    
    public void setTimeRuleWorkDayStatuses(Set<TimeRuleWorkDayStatus> timeRuleWorkDayStatuses) {
        this.timeRuleWorkDayStatuses = timeRuleWorkDayStatuses;
    }




}


