package com.Ntranga.core.CLMS.entities;
// Generated 25 Jul, 2016 12:05:41 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeRulesDetailsInfo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="time_rules_details_info"
 
)
public class TimeRulesDetailsInfo  implements java.io.Serializable {


     private Integer timeRulesInfoId;
     private TimeRulesDetails timeRulesDetails;
     private int customerId;
     private int companyId;
     private int countryId;
     private Date transactionDate;
     private int sequenceId;
     private String isActive;
     private String timeRulesDescription;
     private String weekStartDay;
     private String weekEndDay;
     private String followFirstInLastOut;
     private Integer hoursDay;
     private Integer hoursWeek;
     private String minimumDays;
     private String maximumDays;
     private String showWo;
     private String showPh;
     private String showLeaves;
     private String showOd;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public TimeRulesDetailsInfo() {
    }

    public TimeRulesDetailsInfo(Integer timeRulesInfoId) {
    	this.timeRulesInfoId = timeRulesInfoId;
    }
	
    public TimeRulesDetailsInfo(TimeRulesDetails timeRulesDetails, int customerId, int companyId, int countryId, Date transactionDate, int sequenceId, String timeRulesDescription, String weekStartDay, String weekEndDay, String followFirstInLastOut, Integer hoursDay, Integer hoursWeek, String minimumDays, String maximumDays, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.timeRulesDetails = timeRulesDetails;
        this.customerId = customerId;
        this.companyId = companyId;
        this.countryId = countryId;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.timeRulesDescription = timeRulesDescription;
        this.weekStartDay = weekStartDay;
        this.weekEndDay = weekEndDay;
        this.followFirstInLastOut = followFirstInLastOut;
        this.hoursDay = hoursDay;
        this.hoursWeek = hoursWeek;
        this.minimumDays = minimumDays;
        this.maximumDays = maximumDays;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public TimeRulesDetailsInfo(TimeRulesDetails timeRulesDetails, int customerId, int companyId, int countryId, Date transactionDate, int sequenceId, String isActive, String timeRulesDescription, String weekStartDay, String weekEndDay, String followFirstInLastOut, Integer hoursDay, Integer hoursWeek, String minimumDays, String maximumDays, String showWo, String showPh, String showLeaves, String showOd, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.timeRulesDetails = timeRulesDetails;
       this.customerId = customerId;
       this.companyId = companyId;
       this.countryId = countryId;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.isActive = isActive;
       this.timeRulesDescription = timeRulesDescription;
       this.weekStartDay = weekStartDay;
       this.weekEndDay = weekEndDay;
       this.followFirstInLastOut = followFirstInLastOut;
       this.hoursDay = hoursDay;
       this.hoursWeek = hoursWeek;
       this.minimumDays = minimumDays;
       this.maximumDays = maximumDays;
       this.showWo = showWo;
       this.showPh = showPh;
       this.showLeaves = showLeaves;
       this.showOd = showOd;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Time_Rules_Info_Id", unique=true, nullable=false)
    public Integer getTimeRulesInfoId() {
        return this.timeRulesInfoId;
    }
    
    public void setTimeRulesInfoId(Integer timeRulesInfoId) {
        this.timeRulesInfoId = timeRulesInfoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Time_Rules_Id", nullable=false)
    public TimeRulesDetails getTimeRulesDetails() {
        return this.timeRulesDetails;
    }
    
    public void setTimeRulesDetails(TimeRulesDetails timeRulesDetails) {
        this.timeRulesDetails = timeRulesDetails;
    }

    
    @Column(name="Customer_Id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Company_Id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Is_Active", length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Time_Rules_Description", nullable=false, length=100)
    public String getTimeRulesDescription() {
        return this.timeRulesDescription;
    }
    
    public void setTimeRulesDescription(String timeRulesDescription) {
        this.timeRulesDescription = timeRulesDescription;
    }

    
    @Column(name="Week_Start_Day", nullable=false, length=45)
    public String getWeekStartDay() {
        return this.weekStartDay;
    }
    
    public void setWeekStartDay(String weekStartDay) {
        this.weekStartDay = weekStartDay;
    }

    
    @Column(name="Week_End_Day", nullable=false, length=45)
    public String getWeekEndDay() {
        return this.weekEndDay;
    }
    
    public void setWeekEndDay(String weekEndDay) {
        this.weekEndDay = weekEndDay;
    }

    
    @Column(name="Follow_First_In_Last_Out", nullable=false, length=2)
    public String getFollowFirstInLastOut() {
        return this.followFirstInLastOut;
    }
    
    public void setFollowFirstInLastOut(String followFirstInLastOut) {
        this.followFirstInLastOut = followFirstInLastOut;
    }


    @Column(name="Hours_Day", nullable=false)
    public Integer getHoursDay() {
        return this.hoursDay;
    }
    
    public void setHoursDay(Integer hoursDay) {
        this.hoursDay = hoursDay;
    }


    @Column(name="Hours_Week", nullable=false)
    public Integer getHoursWeek() {
        return this.hoursWeek;
    }
    
    public void setHoursWeek(Integer hoursWeek) {
        this.hoursWeek = hoursWeek;
    }

    
    @Column(name="Minimum_Days", nullable=false, length=45)
    public String getMinimumDays() {
        return this.minimumDays;
    }
    
    public void setMinimumDays(String minimumDays) {
        this.minimumDays = minimumDays;
    }

    
    @Column(name="Maximum_Days", nullable=false, length=45)
    public String getMaximumDays() {
        return this.maximumDays;
    }
    
    public void setMaximumDays(String maximumDays) {
        this.maximumDays = maximumDays;
    }

    
    @Column(name="Show_WO", length=45)
    public String getShowWo() {
        return this.showWo;
    }
    
    public void setShowWo(String showWo) {
        this.showWo = showWo;
    }

    
    @Column(name="Show_PH", length=45)
    public String getShowPh() {
        return this.showPh;
    }
    
    public void setShowPh(String showPh) {
        this.showPh = showPh;
    }

    
    @Column(name="Show_Leaves", length=45)
    public String getShowLeaves() {
        return this.showLeaves;
    }
    
    public void setShowLeaves(String showLeaves) {
        this.showLeaves = showLeaves;
    }

    
    @Column(name="Show_OD", length=45)
    public String getShowOd() {
        return this.showOd;
    }
    
    public void setShowOd(String showOd) {
        this.showOd = showOd;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


