package com.Ntranga.core.CLMS.entities;
// Generated 25 Jul, 2016 12:05:41 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeRuleWorkDayStatus generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="time_rule_work_day_status"
   
)
public class TimeRuleWorkDayStatus  implements java.io.Serializable {


     private Integer dayStatusId;
     private TimeRulesDetails timeRulesDetails;
     private String fromHours;
     private String toHours;
     private String statusDescription;
     private String statusCode;
     private String isActive;
     private int customerId;
     private int companyId;
     private Date transactionDate;
     private int sequenceId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public TimeRuleWorkDayStatus() {
    }

    public TimeRuleWorkDayStatus(TimeRulesDetails timeRulesDetails, String fromHours, String toHours, String statusDescription, String statusCode, String isActive, int customerId, int companyId, Date transactionDate, int sequenceId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.timeRulesDetails = timeRulesDetails;
       this.fromHours = fromHours;
       this.toHours = toHours;
       this.statusDescription = statusDescription;
       this.statusCode = statusCode;
       this.isActive = isActive;
       this.customerId = customerId;
       this.companyId = companyId;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Day_Status_Id", unique=true, nullable=false)
    public Integer getDayStatusId() {
        return this.dayStatusId;
    }
    
    public void setDayStatusId(Integer dayStatusId) {
        this.dayStatusId = dayStatusId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Time_Rule_Id", nullable=false)
    public TimeRulesDetails getTimeRulesDetails() {
        return this.timeRulesDetails;
    }
    
    public void setTimeRulesDetails(TimeRulesDetails timeRulesDetails) {
        this.timeRulesDetails = timeRulesDetails;
    }

    
    @Column(name="From_Hours", nullable=false, length=45)
    public String getFromHours() {
        return this.fromHours;
    }
    
    public void setFromHours(String fromHours) {
        this.fromHours = fromHours;
    }

    
    @Column(name="To_Hours", nullable=false, length=45)
    public String getToHours() {
        return this.toHours;
    }
    
    public void setToHours(String toHours) {
        this.toHours = toHours;
    }

    
    @Column(name="Status_Description", nullable=false, length=45)
    public String getStatusDescription() {
        return this.statusDescription;
    }
    
    public void setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
    }

    
    @Column(name="Status_Code", nullable=false, length=45)
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Customer_Id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Company_Id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


