package com.Ntranga.core.CLMS.entities;
// Generated 25 Jul, 2016 12:05:41 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TimeRuleBufferTime generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="time_rule_buffer_time"
)
public class TimeRuleBufferTime  implements java.io.Serializable {


     private Integer bufferTimeId;
     private TimeRulesDetails timeRulesDetails;
     private int customerId;
     private int companyId;
     private String timeEvent;
     private int bufferTime;
     private String penality;
     private Integer exemptedOccurrence;
     private Integer greaterExemptedOccurrence;
     private String fromHours;
     private String toHours;
     private Date transactionDate;
     private int sequenceId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private String isActive;

    public TimeRuleBufferTime() {
    }

    public TimeRuleBufferTime(TimeRulesDetails timeRulesDetails, int customerId, int companyId, String timeEvent, 
    							int bufferTime,  String penality, Integer exemptedOccurrence, Integer greaterExemptedOccurrence,
    							String fromHours, String toHours, Date transactionDate, int sequenceId,
    							int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, String isActive) {
       this.timeRulesDetails = timeRulesDetails;
       this.customerId = customerId;
       this.companyId = companyId;
       this.timeEvent = timeEvent;
       this.bufferTime = bufferTime;
       this.penality = penality;
       this.exemptedOccurrence = exemptedOccurrence;
       this.greaterExemptedOccurrence = greaterExemptedOccurrence;
       this.fromHours = fromHours;
       this.toHours = toHours;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Buffer_Time_Id", unique=true, nullable=false)
    public Integer getBufferTimeId() {
        return this.bufferTimeId;
    }
    
    public void setBufferTimeId(Integer bufferTimeId) {
        this.bufferTimeId = bufferTimeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Time_Rule_Id", nullable=false)
    public TimeRulesDetails getTimeRulesDetails() {
        return this.timeRulesDetails;
    }
    
    public void setTimeRulesDetails(TimeRulesDetails timeRulesDetails) {
        this.timeRulesDetails = timeRulesDetails;
    }

    
    @Column(name="Customer_Id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Company_Id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="Time_Event", nullable=false, length=45)
    public String getTimeEvent() {
        return this.timeEvent;
    }
    
    public void setTimeEvent(String timeEvent) {
        this.timeEvent = timeEvent;
    }

    
    @Column(name="Buffer_Time", nullable=false)
    public int getBufferTime() {
        return this.bufferTime;
    }
    
    public void setBufferTime(int bufferTime) {
        this.bufferTime = bufferTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
	public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

	@Column(name="Penality", length= 20)
	public String getPenality() {
		return penality;
	}

	public void setPenality(String penality) {
		this.penality = penality;
	}

	@Column(name="Exempted_Occurrence")
    public Integer getExemptedOccurrence() {
		return exemptedOccurrence;
	}

	public void setExemptedOccurrence(Integer exemptedOccurrence) {
		this.exemptedOccurrence = exemptedOccurrence;
	}

	@Column(name="Greater_Exempted_Occurrence")
	public Integer getGreaterExemptedOccurrence() {
		return greaterExemptedOccurrence;
	}

	public void setGreaterExemptedOccurrence(Integer greaterExemptedOccurrence) {
		this.greaterExemptedOccurrence = greaterExemptedOccurrence;
	}

	@Column(name="From_Hours", length = 6)
	public String getFromHours() {
		return fromHours;
	}

	public void setFromHours(String fromHours) {
		this.fromHours = fromHours;
	}

	@Column(name="To_Hours", length = 6)
	public String getToHours() {
		return toHours;
	}

	public void setToHours(String toHours) {
		this.toHours = toHours;
	}

	@Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }




}


