package com.Ntranga.core.CLMS.entities;
// Generated Feb 8, 2017 10:47:13 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLoginInfo generated by hbm2java
 */
@Entity
@Table(name = "user_login_info")
public class UserLoginInfo implements java.io.Serializable {

	private Integer userLoginInfo;
	private Integer userId;
	private Date loggedInTime;

	public UserLoginInfo() {
	}

	public UserLoginInfo(Integer userId, Date loggedInTime) {
		this.userId = userId;
		this.loggedInTime = loggedInTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_login_info", unique = true, nullable = false)
	public Integer getUserLoginInfo() {
		return this.userLoginInfo;
	}

	public void setUserLoginInfo(Integer userLoginInfo) {
		this.userLoginInfo = userLoginInfo;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logged_in_time", length = 19)
	public Date getLoggedInTime() {
		return this.loggedInTime;
	}

	public void setLoggedInTime(Date loggedInTime) {
		this.loggedInTime = loggedInTime;
	}

}
