package com.Ntranga.core.CLMS.entities;
// Generated Jun 27, 2016 3:48:14 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorBranches generated by hbm2java
 */
@Entity
@Table(name="vendor_branches"
    
)
public class VendorBranches  implements java.io.Serializable {


     private Integer vendorBranchId;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private CompanyDetails companyDetails;
     private String branchCode;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Set<VendorBranchDetailsInfo> vendorBranchDetailsInfos = new HashSet<VendorBranchDetailsInfo>(0);    

    public VendorBranches() {
    }

    public VendorBranches(Integer vendorBranchId) {
        this.vendorBranchId = vendorBranchId;
    }
	
    public VendorBranches(CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, String branchCode, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.customerDetails = customerDetails;
        this.vendorDetails = vendorDetails;
        this.companyDetails = companyDetails;
        this.branchCode = branchCode;
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public VendorBranches(CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, String branchCode, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<VendorBranchDetailsInfo> vendorBranchDetailsInfos) {
       this.customerDetails = customerDetails;
       this.vendorDetails = vendorDetails;
       this.companyDetails = companyDetails;
       this.branchCode = branchCode;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.vendorBranchDetailsInfos = vendorBranchDetailsInfos;
     
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Vendor_Branch_Id", unique=true, nullable=false)
    public Integer getVendorBranchId() {
        return this.vendorBranchId;
    }
    
    public void setVendorBranchId(Integer vendorBranchId) {
        this.vendorBranchId = vendorBranchId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Branch_Code", nullable=false, length=45)
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendorBranches")
    public Set<VendorBranchDetailsInfo> getVendorBranchDetailsInfos() {
        return this.vendorBranchDetailsInfos;
    }
    
    public void setVendorBranchDetailsInfos(Set<VendorBranchDetailsInfo> vendorBranchDetailsInfos) {
        this.vendorBranchDetailsInfos = vendorBranchDetailsInfos;
    }




}


