package com.Ntranga.core.CLMS.entities;
// Generated 4 Jul, 2016 3:41:29 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorBankDetails generated by hbm2java
 */
@Entity
@Table(name="vendor_bank_details"  
)
public class VendorBankDetails  implements java.io.Serializable {


     private Integer vendorBankId;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private CompanyDetails companyDetails;
     private LocationDetails locationDetails;
     private String bankCode;
     private Date transactionDate;
     private int sequenceId;
     private String bankName;
     private String accountHolderName;
     private String accountNumber;
     private String branch;
     private String ifscCode;
     private String micrCode;
     private String phoneNumber;
     private String addressLine1;
     private String addressLine2;
     private String addressLine3;
     private Integer country;
     private Integer state;
     private String city;
     private Integer pincode;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private String isActive;
     private int uniqueId;
     private String bankCity;
     private Integer companyCountry;

    public VendorBankDetails() {
    }

	
    public VendorBankDetails(CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, LocationDetails locationDetails, Date transactionDate, int sequenceId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.customerDetails = customerDetails;
        this.vendorDetails = vendorDetails;
        this.companyDetails = companyDetails;
        this.locationDetails = locationDetails;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public VendorBankDetails(CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, LocationDetails locationDetails, String bankCode, Date transactionDate, int sequenceId, String bankName, String accountHolderName, String accountNumber, String branch, String ifscCode, String micrCode, String phoneNumber, String addressLine1, String addressLine2, String addressLine3, Integer country, Integer state, String city, Integer pincode, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, String isActive) {
       this.customerDetails = customerDetails;
       this.vendorDetails = vendorDetails;
       this.companyDetails = companyDetails;
       this.locationDetails = locationDetails;
       this.bankCode = bankCode;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.bankName = bankName;
       this.accountHolderName = accountHolderName;
       this.accountNumber = accountNumber;
       this.branch = branch;
       this.ifscCode = ifscCode;
       this.micrCode = micrCode;
       this.phoneNumber = phoneNumber;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.country = country;
       this.state = state;
       this.city = city;
       this.pincode = pincode;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Vendor_Bank_Id", unique=true, nullable=false)
    public Integer getVendorBankId() {
        return this.vendorBankId;
    }
    
    public void setVendorBankId(Integer vendorBankId) {
        this.vendorBankId = vendorBankId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Location_Id", nullable=false)
    public LocationDetails getLocationDetails() {
        return this.locationDetails;
    }
    
    public void setLocationDetails(LocationDetails locationDetails) {
        this.locationDetails = locationDetails;
    }

    
    @Column(name="Bank_Code", length=45)
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }
    
    
    
    
    
    
    @Column(name="Bank_City", length=45)
    public String getBankCity() {
		return bankCity;
	}


	public void setBankCity(String bankCity) {
		this.bankCity = bankCity;
	}


	@Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Bank_Name", length=45)
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    
    @Column(name="Account_Holder_Name", length=45)
    public String getAccountHolderName() {
        return this.accountHolderName;
    }
    
    public void setAccountHolderName(String accountHolderName) {
        this.accountHolderName = accountHolderName;
    }

    
    @Column(name="Account_Number", length=45)
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    
    @Column(name="Branch", length=45)
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }

    
    @Column(name="IFSC_Code", length=45)
    public String getIfscCode() {
        return this.ifscCode;
    }
    
    public void setIfscCode(String ifscCode) {
        this.ifscCode = ifscCode;
    }

    
    @Column(name="MICR_Code", length=45)
    public String getMicrCode() {
        return this.micrCode;
    }
    
    public void setMicrCode(String micrCode) {
        this.micrCode = micrCode;
    }

    
    @Column(name="Phone_Number", length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="Address_Line1", length=45)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="Address_Line2", length=45)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="Address_Line3", length=45)
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }

    
    @Column(name="Country")
    public Integer getCountry() {
        return this.country;
    }
    
    public void setCountry(Integer country) {
        this.country = country;
    }

    
    @Column(name="State")
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

    
    @Column(name="City", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Pincode")
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }

    
    
    @Column(name="Company_Country")
    public Integer getCompanyCountry() {
		return companyCountry;
	}


	public void setCompanyCountry(Integer companyCountry) {
		this.companyCountry = companyCountry;
	}


	@Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    
    @Column(name="Is_Active", length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    @Column(name="Unique_id")
	public int getUniqueId() {
		return uniqueId;
	}


	public void setUniqueId(int uniqueId) {
		this.uniqueId = uniqueId;
	}




}


