package com.Ntranga.core.CLMS.entities;
// Generated 27 Jun, 2016 12:39:35 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorIndustrySubindustryDetails generated by hbm2java
 */
@Entity
@Table(name="vendor_industry_subindustry_details"
    
)
public class VendorIndustrySubindustryDetails  implements java.io.Serializable {


     private Integer vendorIndustrySubIndustryDetailsId;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private CompanyDetails companyDetails;
     private Date transactionDate;
     private int sequenceId;
     private int industryId;
     private int subIndustryId;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public VendorIndustrySubindustryDetails() {
    }

    public VendorIndustrySubindustryDetails(CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, Date transactionDate, int sequenceId, int industryId, int subIndustryId, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.customerDetails = customerDetails;
       this.vendorDetails = vendorDetails;
       this.companyDetails = companyDetails;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.industryId = industryId;
       this.subIndustryId = subIndustryId;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
    
    public VendorIndustrySubindustryDetails(CustomerDetails customerDetails ,CompanyDetails companyDetails,  VendorDetails vendorDetails, int industryId, int subIndustryId, Date transactionDate, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate,String isActive,int sequenceId) {
       this.customerDetails =customerDetails;
       this.companyDetails =companyDetails;
    	this.vendorDetails = vendorDetails;        
        this.industryId = industryId;
        this.subIndustryId = subIndustryId;
        this.transactionDate = transactionDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;       
        this.sequenceId=sequenceId;
        this.isActive =isActive;
     }
    
    
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Vendor_Industry_SubIndustry_Details_Id", unique=true, nullable=false)
    public Integer getVendorIndustrySubIndustryDetailsId() {
        return this.vendorIndustrySubIndustryDetailsId;
    }
    
    public void setVendorIndustrySubIndustryDetailsId(Integer vendorIndustrySubIndustryDetailsId) {
        this.vendorIndustrySubIndustryDetailsId = vendorIndustrySubIndustryDetailsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Industry_Id", nullable=false)
    public int getIndustryId() {
        return this.industryId;
    }
    
    public void setIndustryId(int industryId) {
        this.industryId = industryId;
    }

    
    @Column(name="SubIndustry_Id", nullable=false)
    public int getSubIndustryId() {
        return this.subIndustryId;
    }
    
    public void setSubIndustryId(int subIndustryId) {
        this.subIndustryId = subIndustryId;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


