package com.Ntranga.core.CLMS.entities;
// Generated Jun 27, 2016 3:48:14 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorBranchDetailsInfo generated by hbm2java
 */
@Entity
@Table(name="vendor_branch_details_info"
    
)
public class VendorBranchDetailsInfo  implements java.io.Serializable {


     private Integer vendorBranchDetailsInfoId;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private VendorBranches vendorBranches;
     private CompanyDetails companyDetails;
     private String branchCode;
     private Date transactionDate;
     private Integer sequenceId;
     private String locationName;
     private String contactPerson;
     private String designation;
     private String mobile;
     private String phoneNumber;
     private String extension;
     private String faxNumber;
     private String email;
     //private Integer workType;
     private String pfAccountNumber;
     private Date pfRegistrationDate;
     private Date pfStartDate;
     private Integer pfType;
     private String pfCircle;
     private String esiAccountNumber;
     private Date esiRegistrationDate;
     private Date esiStartDate;
     private String isProfessionalTaxApplicable;
     private String address1;
     private String address2;
     private String address3;
     private Integer country;
     private Integer state;
     private String city;
     private Integer pincode;
     private String isActive;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;
     
     private String natureOfWork;

    public VendorBranchDetailsInfo() {
    }

	
    public VendorBranchDetailsInfo(CustomerDetails customerDetails, VendorDetails vendorDetails,String natureOfWork, VendorBranches vendorBranches, CompanyDetails companyDetails, String branchCode, Date transactionDate, Integer sequenceId, String locationName, String contactPerson, String designation, String mobile, Integer workType, String pfAccountNumber, Date pfRegistrationDate, Integer pfType, String pfCircle, String isProfessionalTaxApplicable, String address1, Integer country, Integer state, String city, Integer pincode, String isActive, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
        this.customerDetails = customerDetails;
        this.vendorDetails = vendorDetails;
        this.vendorBranches = vendorBranches;
        this.companyDetails = companyDetails;
        this.branchCode = branchCode;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.locationName = locationName;
        this.contactPerson = contactPerson;
        this.designation = designation;
        this.mobile = mobile;
        //this.workType = workType;
        this.pfAccountNumber = pfAccountNumber;
        this.pfRegistrationDate = pfRegistrationDate;
        this.pfType = pfType;
        this.pfCircle = pfCircle;
        this.isProfessionalTaxApplicable = isProfessionalTaxApplicable;
        this.address1 = address1;
        this.country = country;
        this.state = state;
        this.city = city;
        this.pincode = pincode;
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.setNatureOfWork(natureOfWork);
    }
    public VendorBranchDetailsInfo(CustomerDetails customerDetails, VendorDetails vendorDetails, String natureOfWork,VendorBranches vendorBranches, CompanyDetails companyDetails, String branchCode, Date transactionDate, Integer sequenceId, String locationName, String contactPerson, String designation, String mobile, String phoneNumber, String extension, String faxNumber, String email, Integer workType, String pfAccountNumber, Date pfRegistrationDate, Date pfStartDate, Integer pfType, String pfCircle, String esiAccountNumber, Date esiRegistrationDate, Date esiStartDate, String isProfessionalTaxApplicable, String address1, String address2, String address3, Integer country, Integer state, String city, Integer pincode, String isActive, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.customerDetails = customerDetails;
       this.vendorDetails = vendorDetails;
       this.vendorBranches = vendorBranches;
       this.companyDetails = companyDetails;
       this.branchCode = branchCode;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.locationName = locationName;
       this.contactPerson = contactPerson;
       this.designation = designation;
       this.mobile = mobile;
       this.phoneNumber = phoneNumber;
       this.extension = extension;
       this.faxNumber = faxNumber;
       this.email = email;
      // this.workType = workType;
       this.pfAccountNumber = pfAccountNumber;
       this.pfRegistrationDate = pfRegistrationDate;
       this.pfStartDate = pfStartDate;
       this.pfType = pfType;
       this.pfCircle = pfCircle;
       this.esiAccountNumber = esiAccountNumber;
       this.esiRegistrationDate = esiRegistrationDate;
       this.esiStartDate = esiStartDate;
       this.isProfessionalTaxApplicable = isProfessionalTaxApplicable;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.country = country;
       this.state = state;
       this.city = city;
       this.pincode = pincode;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.setNatureOfWork(natureOfWork);
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Vendor_Branch_Details_Info_Id", unique=true, nullable=false)
    public Integer getVendorBranchDetailsInfoId() {
        return this.vendorBranchDetailsInfoId;
    }
    
    public void setVendorBranchDetailsInfoId(Integer vendorBranchDetailsInfoId) {
        this.vendorBranchDetailsInfoId = vendorBranchDetailsInfoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Branch_Id", nullable=false)
    public VendorBranches getVendorBranches() {
        return this.vendorBranches;
    }
    
    public void setVendorBranches(VendorBranches vendorBranches) {
        this.vendorBranches = vendorBranches;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Branch_Code", length=45)
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public Integer getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Location_Name", length=100)
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    
    @Column(name="Contact_Person",  length=50)
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    
    @Column(name="Designation", length=50)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="Mobile", nullable=false, length=15)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="Phone_Number", length=15)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="Extension", length=15)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }

    
    @Column(name="FAX_Number", length=15)
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    
    @Column(name="Email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    /*@Column(name="Work_Type", nullable=false)
    public Integer getWorkType() {
        return this.workType;
    }
    
    public void setWorkType(Integer workType) {
        this.workType = workType;
    }*/

    
    @Column(name="PF_Account_Number",  length=25)
    public String getPfAccountNumber() {
        return this.pfAccountNumber;
    }
    
    public void setPfAccountNumber(String pfAccountNumber) {
        this.pfAccountNumber = pfAccountNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PF_Registration_Date",  length=10)
    public Date getPfRegistrationDate() {
        return this.pfRegistrationDate;
    }
    
    public void setPfRegistrationDate(Date pfRegistrationDate) {
        this.pfRegistrationDate = pfRegistrationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PF_Start_Date", length=10)
    public Date getPfStartDate() {
        return this.pfStartDate;
    }
    
    public void setPfStartDate(Date pfStartDate) {
        this.pfStartDate = pfStartDate;
    }

    
    @Column(name="PF_Type")
    public Integer getPfType() {
        return this.pfType;
    }
    
    public void setPfType(Integer pfType) {
        this.pfType = pfType;
    }

    
    @Column(name="PF_Circle", length=50)
    public String getPfCircle() {
        return this.pfCircle;
    }
    
    public void setPfCircle(String pfCircle) {
        this.pfCircle = pfCircle;
    }

    
    @Column(name="ESI_Account_Number", length=25)
    public String getEsiAccountNumber() {
        return this.esiAccountNumber;
    }
    
    public void setEsiAccountNumber(String esiAccountNumber) {
        this.esiAccountNumber = esiAccountNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ESI_Registration_Date", length=10)
    public Date getEsiRegistrationDate() {
        return this.esiRegistrationDate;
    }
    
    public void setEsiRegistrationDate(Date esiRegistrationDate) {
        this.esiRegistrationDate = esiRegistrationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ESI_Start_Date", length=10)
    public Date getEsiStartDate() {
        return this.esiStartDate;
    }
    
    public void setEsiStartDate(Date esiStartDate) {
        this.esiStartDate = esiStartDate;
    }

    
    @Column(name="IS_Professional_Tax_Applicable", length=2)
    public String getIsProfessionalTaxApplicable() {
        return this.isProfessionalTaxApplicable;
    }
    
    public void setIsProfessionalTaxApplicable(String isProfessionalTaxApplicable) {
        this.isProfessionalTaxApplicable = isProfessionalTaxApplicable;
    }

    
    @Column(name="Address_1", nullable=false, length=45)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="Address_2", length=45)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="Address_3", length=45)
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    
    @Column(name="Country", nullable = false)
    public Integer getCountry() {
        return this.country;
    }
    
    public void setCountry(Integer country) {
        this.country = country;
    }

    
    @Column(name="State")
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

    
    @Column(name="City")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Pincode")
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name="Nature_Of_Work", length = 45)
	public String getNatureOfWork() {
		return natureOfWork;
	}


	public void setNatureOfWork(String natureOfWork) {
		this.natureOfWork = natureOfWork;
	}




}


