package com.Ntranga.core.CLMS.entities;
// Generated 22 Jun, 2016 4:22:24 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorDetails generated by hbm2java
 */
@Entity
@Table(name="vendor_details"
    
)
public class VendorDetails  implements java.io.Serializable {


     private Integer vendorId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private String vendorStatus;
     private String vendorCode;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Set<VendorDetailsInfo> vendorDetailsInfos = new HashSet<VendorDetailsInfo>(0);

    public VendorDetails() {
    }

    public VendorDetails(Integer vendorId) {
    	this.vendorId = vendorId;
    }
	
    public VendorDetails(String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public VendorDetails(CustomerDetails customerDetails, CompanyDetails companyDetails, String vendorStatus, String vendorCode, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<VendorDetailsInfo> vendorDetailsInfos) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.vendorCode = vendorCode;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.vendorDetailsInfos = vendorDetailsInfos;
       this.vendorStatus = vendorStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Vendor_Id", unique=true, nullable=false)
    public Integer getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id")
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id")
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Vendor_Code", length=45)
    public String getVendorCode() {
        return this.vendorCode;
    }
    
    public void setVendorCode(String vendorCode) {
        this.vendorCode = vendorCode;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendorDetails")
    public Set<VendorDetailsInfo> getVendorDetailsInfos() {
        return this.vendorDetailsInfos;
    }
    
    public void setVendorDetailsInfos(Set<VendorDetailsInfo> vendorDetailsInfos) {
        this.vendorDetailsInfos = vendorDetailsInfos;
    }

    @Column(name="Vendor_Status", nullable=false, length=15)
    public String getVendorStatus() {
        return this.vendorStatus;
    }
    
    public void setVendorStatus(String vendorStatus) {
        this.vendorStatus = vendorStatus;
    }


}


