package com.Ntranga.core.CLMS.entities;
// Generated 22 Jun, 2016 4:22:24 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorDetailsInfo generated by hbm2java
 */
@Entity
@Table(name="vendor_details_info"
    
)
public class VendorDetailsInfo  implements java.io.Serializable {


     private Integer vendorDetailsInfoId;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private CompanyDetails companyDetails;
     private LocationDetails locationDetails;
     private Date transactionDate;
     private Integer sequenceId;
     private String vendorName;
     private Integer vendorTypeId;
     private String telephoneNumber;
     private String faxNumber;
     private String email;     
     private String website;
     private String natureOfWork;
     private String directorOwnerProprietorName;
     private Integer modeOfPaymentId;
     private Integer paymentFrequencyId;
     private Integer companyTypeId;
     private Integer registeredUnderId;
     private String registrationNumber;
     private Date registrationDate;
     private String panNumber;
     private String serviceRegistrationNumber;
     private String vatNumber;
     private String cstNumber;
     private String tanNumber;
     private String lstNumber;
     private Integer employeeStrength;
     private Double lastYearSalesTurnover;
     private String currencyIn;
     private String securityDepositDetails;
     private String discounts;
     private String address1;
     private String address2;
     private String address3;
     private Integer country;
     private Integer state;
     private String city;
     private Integer pincode;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Integer companyCountry;
     private String vendorStatus;
     private Date statusDate;
     private String reasonForStatusChange;
     private Date vendorRegistrationDate;

    public VendorDetailsInfo() {
    }

	
    public VendorDetailsInfo(String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public VendorDetailsInfo(CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, LocationDetails locationDetails, Date transactionDate, Integer sequenceId, String vendorName, Integer vendorTypeId, String telephoneNumber, String faxNumber, String email, String website, Integer modeOfPaymentId, Integer paymentFrequencyId, Integer companyTypeId, Integer registeredUnderId, String registrationNumber, Date registrationDate, String panNumber, String serviceRegistrationNumber, String vatNumber, String cstNumber, String tanNumber, String lstNumber, Integer employeeStrength, Double lastYearSalesTurnover, String currencyIn, String securityDepositDetails, String discounts, String address1, String address2, String address3, Integer country, Integer state, String city, Integer pincode, String isActive, String vendorStatus,  int createdBy, Date createdDate, int modifiedBy, Date modifiedDate,
    		Date statusDate, String reasonForStatusChange, Date vendorRegistrationDate) {
       this.customerDetails = customerDetails;
       this.vendorDetails = vendorDetails;
       this.companyDetails = companyDetails;
       this.locationDetails = locationDetails;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.vendorName = vendorName;
       this.vendorTypeId = vendorTypeId;
       this.telephoneNumber = telephoneNumber;
       this.faxNumber = faxNumber;
       this.email = email;
       this.website = website;
       this.modeOfPaymentId = modeOfPaymentId;
       this.paymentFrequencyId = paymentFrequencyId;
       this.companyTypeId = companyTypeId;
       this.registeredUnderId = registeredUnderId;
       this.registrationNumber = registrationNumber;
       this.registrationDate = registrationDate;
       this.panNumber = panNumber;
       this.serviceRegistrationNumber = serviceRegistrationNumber;
       this.vatNumber = vatNumber;
       this.cstNumber = cstNumber;
       this.tanNumber = tanNumber;
       this.lstNumber = lstNumber;
       this.employeeStrength = employeeStrength;
       this.lastYearSalesTurnover = lastYearSalesTurnover;
       this.currencyIn = currencyIn;
       this.securityDepositDetails = securityDepositDetails;
       this.discounts = discounts;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.country = country;
       this.state = state;
       this.city = city;
       this.pincode = pincode;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.vendorStatus = vendorStatus;
       this.statusDate = statusDate;
       this.reasonForStatusChange = reasonForStatusChange;
       this.vendorRegistrationDate = vendorRegistrationDate;
    }
   
  


	@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Vendor_Details_Info_Id", unique=true, nullable=false)
    public Integer getVendorDetailsInfoId() {
        return this.vendorDetailsInfoId;
    }
    
    public void setVendorDetailsInfoId(Integer vendorDetailsInfoId) {
        this.vendorDetailsInfoId = vendorDetailsInfoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Location_Id", nullable=false)
    public LocationDetails getLocationDetails() {
        return this.locationDetails;
    }
    
    public void setLocationDetails(LocationDetails locationDetails) {
        this.locationDetails = locationDetails;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", length=10, nullable=false)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public Integer getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Vendor_Name", length=45, nullable=false)
    public String getVendorName() {
        return this.vendorName;
    }
    
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    @Column(name="Nature_Of_Work", length=45)
    public String getNatureOfWork() {
		return natureOfWork;
	}


	public void setNatureOfWork(String natureOfWork) {
		this.natureOfWork = natureOfWork;
	}

	@Column(name="Director_Owner_Proprietor_Name", length=45)
	public String getDirectorOwnerProprietorName() {
		return directorOwnerProprietorName;
	}


	public void setDirectorOwnerProprietorName(String directorOwnerProprietorName) {
		this.directorOwnerProprietorName = directorOwnerProprietorName;
	}


	@Column(name="Vendor_Type_Id", nullable=false)
    public Integer getVendorTypeId() {
        return this.vendorTypeId;
    }
    
    public void setVendorTypeId(Integer vendorTypeId) {
        this.vendorTypeId = vendorTypeId;
    }

    
    @Column(name="Telephone_Number", length=45)
    public String getTelephoneNumber() {
        return this.telephoneNumber;
    }
    
    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    
    @Column(name="FAX_Number", length=45)
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    
    @Column(name="Email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Website", length=45)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }

    
    @Column(name="Mode_Of_Payment_Id")
    public Integer getModeOfPaymentId() {
        return this.modeOfPaymentId;
    }
    
    public void setModeOfPaymentId(Integer modeOfPaymentId) {
        this.modeOfPaymentId = modeOfPaymentId;
    }

    
    @Column(name="Payment_Frequency_Id")
    public Integer getPaymentFrequencyId() {
        return this.paymentFrequencyId;
    }
    
    public void setPaymentFrequencyId(Integer paymentFrequencyId) {
        this.paymentFrequencyId = paymentFrequencyId;
    }

    
    @Column(name="Company_Type_Id", nullable=false)
    public Integer getCompanyTypeId() {
        return this.companyTypeId;
    }
    
    public void setCompanyTypeId(Integer companyTypeId) {
        this.companyTypeId = companyTypeId;
    }

    
    @Column(name="Registered_Under_Id", nullable=false)
    public Integer getRegisteredUnderId() {
        return this.registeredUnderId;
    }
    
    public void setRegisteredUnderId(Integer registeredUnderId) {
        this.registeredUnderId = registeredUnderId;
    }

    
    @Column(name="Registration_Number", length=45, nullable=false)
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Registration_Date", length=10, nullable=false)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    
    @Column(name="PAN_Number", length=20)
    public String getPanNumber() {
        return this.panNumber;
    }
    
    public void setPanNumber(String panNumber) {
        this.panNumber = panNumber;
    }

    
    @Column(name="Service_Registration_Number", length=45)
    public String getServiceRegistrationNumber() {
        return this.serviceRegistrationNumber;
    }
    
    public void setServiceRegistrationNumber(String serviceRegistrationNumber) {
        this.serviceRegistrationNumber = serviceRegistrationNumber;
    }

    
    @Column(name="VAT_Number", length=45)
    public String getVatNumber() {
        return this.vatNumber;
    }
    
    public void setVatNumber(String vatNumber) {
        this.vatNumber = vatNumber;
    }

    
    @Column(name="CST_Number", length=45)
    public String getCstNumber() {
        return this.cstNumber;
    }
    
    public void setCstNumber(String cstNumber) {
        this.cstNumber = cstNumber;
    }

    
    @Column(name="TAN_Number", length=45)
    public String getTanNumber() {
        return this.tanNumber;
    }
    
    public void setTanNumber(String tanNumber) {
        this.tanNumber = tanNumber;
    }

    
    @Column(name="LST_Number", length=45)
    public String getLstNumber() {
        return this.lstNumber;
    }
    
    public void setLstNumber(String lstNumber) {
        this.lstNumber = lstNumber;
    }

    
    @Column(name="Employee_Strength")
    public Integer getEmployeeStrength() {
        return this.employeeStrength;
    }
    
    public void setEmployeeStrength(Integer employeeStrength) {
        this.employeeStrength = employeeStrength;
    }

    
    @Column(name="Last_Year_Sales_Turnover", precision=22, scale=0)
    public Double getLastYearSalesTurnover() {
        return this.lastYearSalesTurnover;
    }
    
    public void setLastYearSalesTurnover(Double lastYearSalesTurnover) {
        this.lastYearSalesTurnover = lastYearSalesTurnover;
    }

    
    @Column(name="Currency_In", length=45)
    public String getCurrencyIn() {
        return this.currencyIn;
    }
    
    public void setCurrencyIn(String currencyIn) {
        this.currencyIn = currencyIn;
    }

    
    @Column(name="Security_Deposit_Details", length=200)
    public String getSecurityDepositDetails() {
        return this.securityDepositDetails;
    }
    
    public void setSecurityDepositDetails(String securityDepositDetails) {
        this.securityDepositDetails = securityDepositDetails;
    }

    
    @Column(name="Discounts", length=200)
    public String getDiscounts() {
        return this.discounts;
    }
    
    public void setDiscounts(String discounts) {
        this.discounts = discounts;
    }

    
    @Column(name="Address_1", length=45, nullable=false)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="Address_2", length=45)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="Address_3", length=45)
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    
    @Column(name="Country", nullable=false)
    public Integer getCountry() {
        return this.country;
    }
    
    public void setCountry(Integer country) {
        this.country = country;
    }

    
    @Column(name="State")
    public Integer getState() {
        return this.state;
    }
    
    
    @Column(name="Company_Country")
    public Integer getCompanyCountry() {
		return companyCountry;
	}


	public void setCompanyCountry(Integer companyCountry) {
		this.companyCountry = companyCountry;
	}


	public void setState(Integer state) {
        this.state = state;
    }

    
    @Column(name="City", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Pincode", nullable=false)
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }

    
    @Column(name="Is_Active",  length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name="Vendor_Status",  length=20)
    public String getVendorStatus() {
        return this.vendorStatus;
    }
    
    public void setVendorStatus(String vendorStatus) {
        this.vendorStatus = vendorStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Status_Date", length=19)
    public Date getStatusDate() {
        return statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }
    
    @Column(name="Reason_For_Status_Change",  length=45)
    public String getReasonForStatusChange() {
        return reasonForStatusChange;
    }
    
    public void setReasonForStatusChange(String reasonForStatusChange) {
        this.reasonForStatusChange = reasonForStatusChange;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Vendor_Registration_Date", length=19)
    public Date getVendorRegistrationDate() {
        return vendorRegistrationDate;
    }
    
    public void setVendorRegistrationDate(Date vendorRegistrationDate) {
        this.vendorRegistrationDate = vendorRegistrationDate;
    }
}


