package com.Ntranga.core.CLMS.entities;
// Generated 23 Jan, 2017 12:03:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VerificationTypesSetup generated by hbm2java
 */
@Entity
@Table(name="verification_types_setup"   
)
public class VerificationTypesSetup  implements java.io.Serializable {


     private Integer verificationTypesSetupId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private int countryId;
     private Date transactionDate;
     private char isActive;
     private String verificationType;
     private String verificationFrequency;
     private Date createdDate;
     private int createdBy;
     private int modifiedBy;
     private Date modifiedDate;
     private char isMandatory;

    public VerificationTypesSetup() {
    }

    public VerificationTypesSetup(CustomerDetails customerDetails, CompanyDetails companyDetails, int countryId, Date transactionDate, char isActive, String verificationType, String verificationFrequency, Date createdDate, int createdBy, int modifiedBy, Date modifiedDate) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.countryId = countryId;
       this.transactionDate = transactionDate;
       this.isActive = isActive;
       this.verificationType = verificationType;
       this.verificationFrequency = verificationFrequency;
       this.createdDate = createdDate;
       this.createdBy = createdBy;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Verification_Types_Setup_Id", unique=true, nullable=false)
    public Integer getVerificationTypesSetupId() {
        return this.verificationTypesSetupId;
    }
    
    public void setVerificationTypesSetupId(Integer verificationTypesSetupId) {
        this.verificationTypesSetupId = verificationTypesSetupId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Is_Active", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }
    
    
    

    @Column(name="Is_Mandatory", nullable=false, length=1)
    public char getIsMandatory() {
		return isMandatory;
	}

	public void setIsMandatory(char isMandatory) {
		this.isMandatory = isMandatory;
	}

	@Column(name="Verification_Type", nullable=false, length=50)
    public String getVerificationType() {
        return this.verificationType;
    }
    
    public void setVerificationType(String verificationType) {
        this.verificationType = verificationType;
    }

    
    @Column(name="Verification_Frequency", nullable=false, length=50)
    public String getVerificationFrequency() {
        return this.verificationFrequency;
    }
    
    public void setVerificationFrequency(String verificationFrequency) {
        this.verificationFrequency = verificationFrequency;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

   
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


