package com.Ntranga.core.CLMS.entities;
// Generated 10 Aug, 2016 10:51:23 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WageScaleDetails generated by hbm2java
 */
@Entity
@Table(name="wage_scale_details" 
)
public class WageScaleDetails  implements java.io.Serializable {


     private Integer wageScaleId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private String wageScaleCode;
     private String wageScaleName;
     private Date transactionDate;
     private int sequenceId;
     private int countryId;
     private int locationId;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Set<WageScaleWorkSkills> wageScaleWorkSkillses = new HashSet<WageScaleWorkSkills>(0);

    public WageScaleDetails() {
    }

	
    public WageScaleDetails(CustomerDetails customerDetails, CompanyDetails companyDetails, String wageScaleCode, String wageScaleName, Date transactionDate, int sequenceId, int countryId, int locationId, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.customerDetails = customerDetails;
        this.companyDetails = companyDetails;
        this.wageScaleCode = wageScaleCode;
        this.wageScaleName = wageScaleName;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.countryId = countryId;
        this.locationId = locationId;
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public WageScaleDetails(CustomerDetails customerDetails, CompanyDetails companyDetails, String wageScaleCode, String wageScaleName, Date transactionDate, int sequenceId, int countryId, int locationId, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<WageScaleWorkSkills> wageScaleWorkSkillses) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.wageScaleCode = wageScaleCode;
       this.wageScaleName = wageScaleName;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.countryId = countryId;
       this.locationId = locationId;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.wageScaleWorkSkillses = wageScaleWorkSkillses;
    }
   
     public WageScaleDetails(Integer wageScaleId2) {
		// TODO Auto-generated constructor stub
    	 this.wageScaleId= wageScaleId2;
	}


	@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Wage_Scale_Id", unique=true, nullable=false)
    public Integer getWageScaleId() {
        return this.wageScaleId;
    }
    
    public void setWageScaleId(Integer wageScaleId) {
        this.wageScaleId = wageScaleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Wage_Scale_Code", nullable=false, length=45)
    public String getWageScaleCode() {
        return this.wageScaleCode;
    }
    
    public void setWageScaleCode(String wageScaleCode) {
        this.wageScaleCode = wageScaleCode;
    }

    
    @Column(name="Wage_Scale_Name", nullable=false, length=45)
    public String getWageScaleName() {
        return this.wageScaleName;
    }
    
    public void setWageScaleName(String wageScaleName) {
        this.wageScaleName = wageScaleName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="Location_Id", nullable=false)
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wageScaleDetails")
    public Set<WageScaleWorkSkills> getWageScaleWorkSkillses() {
        return this.wageScaleWorkSkillses;
    }
    
    public void setWageScaleWorkSkillses(Set<WageScaleWorkSkills> wageScaleWorkSkillses) {
        this.wageScaleWorkSkillses = wageScaleWorkSkillses;
    }




}


