package com.Ntranga.core.CLMS.entities;
// Generated 10 Aug, 2016 10:51:23 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WageScaleWorkSkills generated by hbm2java
 */
@Entity
@Table(name="wage_scale_work_skills"   
)
public class WageScaleWorkSkills  implements java.io.Serializable {


     private Integer wageScaleWorkSkillId;
     private WageScaleDetails wageScaleDetails;
     private int customerId;
     private int companyId;
     private String workSkll;
     private int wageFrom;
     private int wageTo;
     private String currency;
     private String frequency;
     private String isActive;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public WageScaleWorkSkills() {
    }

    public WageScaleWorkSkills(WageScaleDetails wageScaleDetails, int customerId, int companyId, String workSkll, int wageFrom, int wageTo, String currency, String frequency, String isActive, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.wageScaleDetails = wageScaleDetails;
       this.customerId = customerId;
       this.companyId = companyId;
       this.workSkll = workSkll;
       this.wageFrom = wageFrom;
       this.wageTo = wageTo;
       this.currency = currency;
       this.frequency = frequency;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Wage_Scale_Work_Skill_Id", unique=true, nullable=false)
    public Integer getWageScaleWorkSkillId() {
        return this.wageScaleWorkSkillId;
    }
    
    public void setWageScaleWorkSkillId(Integer wageScaleWorkSkillId) {
        this.wageScaleWorkSkillId = wageScaleWorkSkillId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wage_Scale_Id", nullable=false)
    public WageScaleDetails getWageScaleDetails() {
        return this.wageScaleDetails;
    }
    
    public void setWageScaleDetails(WageScaleDetails wageScaleDetails) {
        this.wageScaleDetails = wageScaleDetails;
    }

    
    @Column(name="Customer_Id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Company_Id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="Work_Skll", nullable=false, length=45)
    public String getWorkSkll() {
        return this.workSkll;
    }
    
    public void setWorkSkll(String workSkll) {
        this.workSkll = workSkll;
    }

    
    @Column(name="WageFrom", nullable=false)
    public int getWageFrom() {
        return this.wageFrom;
    }
    
    public void setWageFrom(int wageFrom) {
        this.wageFrom = wageFrom;
    }

    
    @Column(name="WageTo", nullable=false)
    public int getWageTo() {
        return this.wageTo;
    }
    
    public void setWageTo(int wageTo) {
        this.wageTo = wageTo;
    }

    
    @Column(name="Currency", nullable=false, length=45)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    
    @Column(name="Frequency", nullable=false, length=45)
    public String getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


