package com.Ntranga.core.CLMS.entities;
// Generated Sep 1, 2016 4:27:03 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WageCalculator generated by hbm2java
 */
@Entity
@Table(name="wage_calculator" )
public class WageCalculator  implements java.io.Serializable {


    private Integer wageCalculatorId;
	private CustomerDetails customerDetails;    
    private CompanyDetails companyDetails;
    private VendorDetails vendorDetails;
    private WorkerDetails workerDetails;
    private Date transactionDate;
    private Integer sequenceId;
    private Integer atYear;
    private Integer atMonth;
    private Integer payableDays;
    private Double  overTimeHours;
    private Double  dailyRatePerDay;
    private Double  baseRatePerDay;
    private Double  overTimeRatePerHour;
    private Double  additionalAllowance;
    private Double  oneTimeEarnings;
    private Double  totalEarnings;
    private Double  pf;
    private Double  esi;
    private Double  lwf;
    private Double  pt;
    private Double  advance;
    private Double  damageOrLoss;
    private Double  fines;
    private Double  totalDeductions;
    private Double  grossSalaray;
    private Double  netSalary;
    private Integer createdBy;
    private Date createdDate;
    private Integer modifiedBy;
    private Date modifiedDate;
    
    
    
    @Id @GeneratedValue(strategy=IDENTITY)  
    @Column(name="Wage_Calculator_Id", unique=true, nullable=false)
    public Integer getWageCalculatorId() {
        return this.wageCalculatorId;
    }    
    public void setWageCalculatorId(Integer wageCalculatorId) {
        this.wageCalculatorId = wageCalculatorId;
    }
		
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }
    
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }
    
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_id", nullable=false)
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }
    
    
    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_id", nullable=false)
    public Integer getSequenceId() {
        return this.sequenceId;
    }    
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }    
	
	@Column(name="At_Year", nullable=false)
	public Integer getAtYear() {
		return atYear;
	}
	public void setAtYear(Integer atYear) {
		this.atYear = atYear;
	}
	
	@Column(name="At_Month", nullable=false)
	public Integer getAtMonth() {
		return atMonth;
	}
	public void setAtMonth(Integer atMonth) {
		this.atMonth = atMonth;
	}
	
	@Column(name="Payable_Days", nullable=false)
	public Integer getPayableDays() {
		return payableDays;
	}
	public void setPayableDays(Integer payableDays) {
		this.payableDays = payableDays;
	}
	
	@Column(name="Over_Time_Hours", precision=22, scale=0)
	public Double getOverTimeHours() {
		return overTimeHours;
	}
	public void setOverTimeHours(Double overTimeHours) {
		this.overTimeHours = overTimeHours;
	}
	
	@Column(name="Daily_Rate_Per_Day", precision=22, scale=0)
	public Double getDailyRatePerDay() {
		return dailyRatePerDay;
	}
	public void setDailyRatePerDay(Double dailyRatePerDay) {
		this.dailyRatePerDay = dailyRatePerDay;
	}
	
	@Column(name="Base_Rate_Per_Day", precision=22, scale=0)
	public Double getBaseRatePerDay() {
		return baseRatePerDay;
	}
	public void setBaseRatePerDay(Double baseRatePerDay) {
		this.baseRatePerDay = baseRatePerDay;
	}
	
	@Column(name="Over_Time_Rate_Per_Hour", precision=22, scale=0)
	public Double getOverTimeRatePerHour() {
		return overTimeRatePerHour;
	}
	public void setOverTimeRatePerHour(Double overTimeRatePerHour) {
		this.overTimeRatePerHour = overTimeRatePerHour;
	}
	
	@Column(name="Additional_Allowance", precision=22, scale=0)
	public Double getAdditionalAllowance() {
		return additionalAllowance;
	}
	public void setAdditionalAllowance(Double additionalAllowance) {
		this.additionalAllowance = additionalAllowance;
	}
	
	@Column(name="One_Time_Earnings", precision=22, scale=0)
	public Double getOneTimeEarnings() {
		return oneTimeEarnings;
	}
	public void setOneTimeEarnings(Double oneTimeEarnings) {
		this.oneTimeEarnings = oneTimeEarnings;
	}
	
	@Column(name="Total_Earnings", precision=22, scale=0)
	public Double getTotalEarnings() {
		return totalEarnings;
	}
	public void setTotalEarnings(Double totalEarnings) {
		this.totalEarnings = totalEarnings;
	}
	
	@Column(name="Pf", precision=22, scale=0)
	public Double getPf() {
		return pf;
	}
	public void setPf(Double pf) {
		this.pf = pf;
	}
	
	@Column(name="Esi", precision=22, scale=0)
	public Double getEsi() {
		return esi;
	}
	public void setEsi(Double esi) {
		this.esi = esi;
	}
	
	@Column(name="Lwf", precision=22, scale=0)
	public Double getLwf() {
		return lwf;
	}
	public void setLwf(Double lwf) {
		this.lwf = lwf;
	}
	
	@Column(name="Pt", precision=22, scale=0)
	public Double getPt() {
		return pt;
	}
	public void setPt(Double pt) {
		this.pt = pt;
	}
	
	@Column(name="Advance", precision=22, scale=0)
	public Double getAdvance() {
		return advance;
	}
	public void setAdvance(Double advance) {
		this.advance = advance;
	}
	
	@Column(name="Damage_Or_Loss", precision=22, scale=0)
	public Double getDamageOrLoss() {
		return damageOrLoss;
	}
	public void setDamageOrLoss(Double damageOrLoss) {
		this.damageOrLoss = damageOrLoss;
	}
	
	@Column(name="Fines", precision=22, scale=0)
	public Double getFines() {
		return fines;
	}
	public void setFines(Double fines) {
		this.fines = fines;
	}
	
	@Column(name="Total_Deductions", precision=22, scale=0)
	public Double getTotalDeductions() {
		return totalDeductions;
	}
	public void setTotalDeductions(Double totalDeductions) {
		this.totalDeductions = totalDeductions;
	}
	
	@Column(name="Gross_Salaray", precision=22, scale=0)
	public Double getGrossSalaray() {
		return grossSalaray;
	}
	public void setGrossSalaray(Double grossSalaray) {
		this.grossSalaray = grossSalaray;
	}
	
	@Column(name="Net_Salary", precision=22, scale=0)
	public Double getNetSalary() {
		return netSalary;
	}
	public void setNetSalary(Double netSalary) {
		this.netSalary = netSalary;
	}
    
	@Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date",  length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    
	
}
