package com.Ntranga.core.CLMS.entities;
// Generated Jun 17, 2016 10:42:43 AM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WageRatesForOT generated by hbm2java
 */
@Entity
@Table(name="Wage_Rates_For_OT"
    
)
public class WageRatesForOT implements Serializable {
	
	private Integer wageRateForOTId;
	private DefineOverTimeControlDetailsInfo defineOverTimeControlDetailsInfo;
	private String workedOn;
    private String regularRates;
    private String otRates;
    private int createdBy;
    private Date createdDate;
    private int modifiedBy;
    private Date modifiedDate;
    
	public WageRatesForOT() {
		
	}
	
	public WageRatesForOT(Integer wageRateForOTId) {
		this.wageRateForOTId = wageRateForOTId;
	}
	    
	public WageRatesForOT(Integer wageRateForOTId, DefineOverTimeControlDetailsInfo defineOverTimeControlDetailsInfo,
			String workedOn, String regularRates, String otRates, int createdBy, Date createdDate, int modifiedBy,
			Date modifiedDate) {
		this.wageRateForOTId = wageRateForOTId;
		this.defineOverTimeControlDetailsInfo = defineOverTimeControlDetailsInfo;
		this.workedOn = workedOn;
		this.regularRates = regularRates;
		this.otRates = otRates;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}
	
@Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="Wage_Rate_For_OT_Id", unique=true, nullable=false)
	public Integer getWageRateForOTId() {
		return wageRateForOTId;
	}
	public void setWageRateForOTId(Integer wageRateForOTId) {
		this.wageRateForOTId = wageRateForOTId;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Define_OverTime_Details_InfoId", nullable=false)
	public DefineOverTimeControlDetailsInfo getDefineOverTimeControlDetailsInfo() {
		return defineOverTimeControlDetailsInfo;
	}
	public void setDefineOverTimeControlDetailsInfo(DefineOverTimeControlDetailsInfo defineOverTimeControlDetailsInfo) {
		this.defineOverTimeControlDetailsInfo = defineOverTimeControlDetailsInfo;
	}
	
	@Column(name="OverTime_Control_Name", length=45)
	public String getWorkedOn() {
		return workedOn;
	}
	public void setWorkedOn(String workedOn) {
		this.workedOn = workedOn;
	}
	
	@Column(name="Regular_Rates", length=45)
	public String getRegularRates() {
		return regularRates;
	}
	public void setRegularRates(String regularRates) {
		this.regularRates = regularRates;
	}
	
	@Column(name="Ot_Rates", length=45)
	public String getOtRates() {
		return otRates;
	}
	public void setOtRates(String otRates) {
		this.otRates = otRates;
	}
	
	@Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    
    

}
