package com.Ntranga.core.CLMS.entities;
// Generated Jul 17, 2016 4:55:33 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkJobDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="work_job_details")
public class WorkJobDetails  implements java.io.Serializable {

	private Integer workJobDetailsId;
     private WorkerDetails workerDetails;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private CompanyDetails companyDetails;
     private Date transactionDate;
     private Integer sequenceId;
     //private String isActive;
    // private String reasonForChange;
     private String jobType;
     private String workSkill;
     private Integer jobName;
     //private Date workStartDate;
     private LocationDetails locationDetails;
     private Integer plantDetails;
     private Integer departmentId;
     private Integer sectionDetails;
     private Integer workAreaDetails;
     private Integer wageRateDetails;
     //private Integer departmentId;
     //private Integer locationId;
     //private Integer plantId;
     private Integer reportingManager;
     private Integer workOrderId;
     //private Integer cardType;
     private String vendorSupervisorName;
     private String contactNo;
     private String pfNumber;
     private String esiNumber;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public WorkJobDetails() {
    }

	
    public WorkJobDetails(WorkerDetails workerDetails, CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, Date transactionDate, Integer reportingManager, Integer sequenceId, String jobType, String workSkill, Integer jobName, Integer departmentId,  Integer workOrderId, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
        this.workerDetails = workerDetails;
        this.customerDetails = customerDetails;
        this.vendorDetails = vendorDetails;
        this.companyDetails = companyDetails;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        //this.isActive = isActive;
        //this.reasonForChange = reasonForChange;
        this.jobType = jobType;
        this.workSkill = workSkill;
        this.jobName = jobName;
       // this.workStartDate = workStartDate;
        this.departmentId = departmentId;
        this.reportingManager = reportingManager;
        this.workOrderId = workOrderId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    
    public WorkJobDetails(Integer workJobDetailsId, WorkerDetails workerDetails, CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails,
			Date transactionDate, Integer sequenceId, String jobType, String workSkill, Integer jobName,
			LocationDetails locationDetails, Integer plantDetails, Integer departmentId,
			Integer sectionDetails, Integer workAreaDetails, Integer wageRateDetails, Integer workOrderId, String vendorSupervisorName,
			String contactNo, String pfNumber, String esiNumber, Integer createdBy, Date createdDate, Integer modifiedBy,Date modifiedDate) {
		this.workJobDetailsId = workJobDetailsId;
		this.workerDetails = workerDetails;
		this.customerDetails = customerDetails;
		this.vendorDetails = vendorDetails;
		this.companyDetails = companyDetails;
		this.transactionDate = transactionDate;
		this.sequenceId = sequenceId;
		this.jobType = jobType;
		this.workSkill = workSkill;
		this.jobName = jobName;
		//this.workStartDate = workStartDate;
		this.locationDetails = locationDetails;
		this.plantDetails = plantDetails;
		this.departmentId = departmentId;
		this.sectionDetails = sectionDetails;
		this.workAreaDetails = workAreaDetails;
		this.wageRateDetails = wageRateDetails;
		this.workOrderId = workOrderId;
		this.vendorSupervisorName = vendorSupervisorName;
		this.contactNo = contactNo;
		this.pfNumber = pfNumber;
		this.esiNumber = esiNumber;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}


	@Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="Work_Job_Details_Id", unique=true, nullable=false)
    public Integer getWorkJobDetailsId() {
        return this.workJobDetailsId;
    }
    
    public void setWorkJobDetailsId(Integer workJobDetailsId) {
        this.workJobDetailsId = workJobDetailsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_Id", nullable=false)
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id", nullable=false)
    public Integer getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    /*@Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }*/

    
    /*@Column(name="Reason_For_Change", length=100)
    public String getReasonForChange() {
        return this.reasonForChange;
    }
    
    public void setReasonForChange(String reasonForChange) {
        this.reasonForChange = reasonForChange;
    }*/

    
    @Column(name="Job_Type", length=50)
    public String getJobType() {
        return this.jobType;
    }
    
    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    
    @Column(name="Work_Skill",  length=50)
    public String getWorkSkill() {
        return this.workSkill;
    }
    
    public void setWorkSkill(String workSkill) {
        this.workSkill = workSkill;
    }

    
    @Column(name="Job_Name")
    public Integer getJobName() {
        return this.jobName;
    }
    
    public void setJobName(Integer jobName) {
        this.jobName = jobName;
    }

    /*@Temporal(TemporalType.DATE)
    @Column(name="Work_Start_Date", nullable=false, length=10)
    public Date getWorkStartDate() {
        return this.workStartDate;
    }
    
    public void setWorkStartDate(Date workStartDate) {
        this.workStartDate = workStartDate;
    }*/

@ManyToOne(fetch=FetchType.LAZY)    
    @JoinColumn(name="Location_Id")
    public LocationDetails getLocationDetails() {
        return locationDetails;
    }
    
    public void setLocationDetails(LocationDetails locationDetails) {
        this.locationDetails = locationDetails;
    }

    @Column(name="Plant_Id")
    public Integer getPlantDetails() {
        return plantDetails;
    }
    
    public void setPlantDetails(Integer plantDetails) {
        this.plantDetails= plantDetails;
    }
 
    @Column(name="Department_Id")
    public Integer getDepartmentId() {
        return departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

 
    @Column(name="Section_Id")
    public Integer getSectionDetails() {
        return sectionDetails;
    }
    
    public void setSectionDetails(Integer sectionDetails) {
        this.sectionDetails = sectionDetails;
    }
    
    

    @Column(name="Work_Area_Id")
    public Integer getWorkAreaDetails() {
        return workAreaDetails;
    }
    
   public void setWorkAreaDetails(Integer workAreaDetails) {
        this.workAreaDetails = workAreaDetails;

   }

  /* @Column(name="Department_Id")
   public Integer getDepartmentId() {
    		return departmentId;
    	}
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name="Location_Id")
	public Integer getLocationId() {
		return locationId;
	}


	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}


	@Column(name="Department", nullable=false)
    public String getDepartment() {
        return this.department;

    }*/
    
    @Column(name="Wage_Rate_Id")
    public Integer getWageRateDetails() {
        return wageRateDetails;
    }
    
    public void setWageRateDetails(Integer wageRateDetails) {
        this.wageRateDetails = wageRateDetails;
    }

    
    @Column(name="Work_Order_Id")
    public Integer getWorkOrderId() {
        return workOrderId;
    }
    
    public void setWorkOrderId(Integer workOrderId) {
        this.workOrderId = workOrderId;
    }

    
    @Column(name="Reporting_Manager")
    public Integer getReportingManager() {
        return this.reportingManager;
    }
    
    public void setReportingManager(Integer reportingManager) {
        this.reportingManager = reportingManager;
    }
    
   /* @Column(name="Card_Type")
    public Integer getCardType() {
        return this.cardType;
    }
    
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }*/
    
    @Column(name="Vendor_Supervisor_Name",  length=50)
    public String getVendorSupervisorName() {
		return vendorSupervisorName;
	}


	public void setVendorSupervisorName(String vendorSupervisorName) {
		this.vendorSupervisorName = vendorSupervisorName;
	}

	@Column(name="Contact_Number", length=15)
	public String getContactNo() {
		return contactNo;
	}


	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}


	@Column(name="PF_Number", length=45)
    public String getPfNumber() {
        return this.pfNumber;
    }
    
    public void setPfNumber(String pfNumber) {
        this.pfNumber = pfNumber;
    }

    
    @Column(name="ESI_Number", length=45)
    public String getEsiNumber() {
        return this.esiNumber;
    }
    
    public void setEsiNumber(String esiNumber) {
        this.esiNumber = esiNumber;
    }

    
    @Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

}


