package com.Ntranga.core.CLMS.entities;
// Generated Jul 20, 2016 6:08:14 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkorderResponsibilities generated by hbm2java
 */
@Entity
@Table(name="workorder_responsibilities"
   
)
public class WorkorderResponsibilities  implements java.io.Serializable {


     private Integer responsibleId;
     private WorkrorderDetail workrorderDetail;
     private WorkorderDetailInfo workorderDetailInfo;
     private String characteristics;
     private String responsibilityTakenBy;
     private Integer companyShare;
     private Integer vendorShare;
     private String additionalInfo;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public WorkorderResponsibilities() {
    }

	
    public WorkorderResponsibilities(WorkrorderDetail workrorderDetail, WorkorderDetailInfo workorderDetailInfo) {
        this.workrorderDetail = workrorderDetail;
        this.workorderDetailInfo = workorderDetailInfo;
    }
    public WorkorderResponsibilities(WorkrorderDetail workrorderDetail, WorkorderDetailInfo workorderDetailInfo, String characteristics, String responsibilityTakenBy, Integer companyShare, Integer vendorShare, String additionalInfo, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.workrorderDetail = workrorderDetail;
       this.workorderDetailInfo = workorderDetailInfo;
       this.characteristics = characteristics;
       this.responsibilityTakenBy = responsibilityTakenBy;
       this.companyShare = companyShare;
       this.vendorShare = vendorShare;
       this.additionalInfo = additionalInfo;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Responsible_Id", unique=true, nullable=false)
    public Integer getResponsibleId() {
        return this.responsibleId;
    }
    
    public void setResponsibleId(Integer responsibleId) {
        this.responsibleId = responsibleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WorkOrder_id", nullable=false)
    public WorkrorderDetail getWorkrorderDetail() {
        return this.workrorderDetail;
    }
    
    public void setWorkrorderDetail(WorkrorderDetail workrorderDetail) {
        this.workrorderDetail = workrorderDetail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WorkOrder_Info_id", nullable=false)
    public WorkorderDetailInfo getWorkorderDetailInfo() {
        return this.workorderDetailInfo;
    }
    
    public void setWorkorderDetailInfo(WorkorderDetailInfo workorderDetailInfo) {
        this.workorderDetailInfo = workorderDetailInfo;
    }

    
    @Column(name="Characteristics", length=100)
    public String getCharacteristics() {
        return this.characteristics;
    }
    
    public void setCharacteristics(String characteristics) {
        this.characteristics = characteristics;
    }

    
    @Column(name="Responsibility_Taken_By", length=50)
    public String getResponsibilityTakenBy() {
        return this.responsibilityTakenBy;
    }
    
    public void setResponsibilityTakenBy(String responsibilityTakenBy) {
        this.responsibilityTakenBy = responsibilityTakenBy;
    }

    
    @Column(name="Company_Share")
    public Integer getCompanyShare() {
        return this.companyShare;
    }
    
    public void setCompanyShare(Integer companyShare) {
        this.companyShare = companyShare;
    }

    
    @Column(name="Vendor_Share")
    public Integer getVendorShare() {
        return this.vendorShare;
    }
    
    public void setVendorShare(Integer vendorShare) {
        this.vendorShare = vendorShare;
    }

    
    @Column(name="Additional_Info", length=100)
    public String getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Created_Date", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Modified_Date", length=10)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


