package com.Ntranga.core.CLMS.entities;
// Generated Jul 17, 2016 4:55:33 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkJobDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="worker_medical_examination")
public class WorkerMedicalExamination  implements java.io.Serializable {

	private Integer medicalExaminationId;
     private WorkerDetails workerDetails;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private CompanyDetails companyDetails;
     private Integer countryId;
     private String height;
     private String weight;
     private String pulse;
     private String bloodPressure;
     private String hearing;
     private String colorBlindness;
     private String eyeVision;
     private String r;
    private String bloodGroup;
    private String respiratorySystem;
    
    private String ansAutonomousNervesSystem;
    private String liverOrSpleen;
    private String pastHistory;
    private String anyOperationDoneInPast;
    private String oeema;
    private String cunosis;
    private String jaundice;
    private String medicalOfficerComment;
    private String anyOtherPhysicalDisability;
    private String medicallyFit;
    private Date reviewDate;
    private String signatureOfDoctor;
    private String filePath;
    private String fileName;
    private String weightType;
    private String heightType;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public WorkerMedicalExamination() {
    }

	
    public WorkerMedicalExamination(WorkerDetails workerDetails, CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, Date transactionDate, Integer reportingManager, Integer sequenceId, String jobType, String workSkill, Integer jobName, Integer departmentId,  Integer workOrderId, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
        this.workerDetails = workerDetails;
        this.customerDetails = customerDetails;
        this.vendorDetails = vendorDetails;
        this.companyDetails = companyDetails;    
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    
   


	@Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="Medical_Examination_Id", unique=true, nullable=false)
    public Integer getMedicalExaminationId() {
		return medicalExaminationId;
	}


	public void setMedicalExaminationId(Integer medicalExaminationId) {
		this.medicalExaminationId = medicalExaminationId;
	}
	
	
	
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_Id", nullable=false)
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    



	public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

  

   

    
    @Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name="Height")
	public String getHeight() {
		return height;
	}


	public void setHeight(String height) {
		this.height = height;
	}

	  @Column(name="Weight")
	public String getWeight() {
		return weight;
	}


	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name="Pulse")
	public String getPulse() {
		return pulse;
	}


	public void setPulse(String pulse) {
		this.pulse = pulse;
	}

	@Column(name="Blood_Pressure")
	public String getBloodPressure() {
		return bloodPressure;
	}


	public void setBloodPressure(String bloodPressure) {
		this.bloodPressure = bloodPressure;
	}

	@Column(name="Hearing")
	public String getHearing() {
		return hearing;
	}


	public void setHearing(String hearing) {
		this.hearing = hearing;
	}

	@Column(name="Color_Blindness")
	public String getColorBlindness() {
		return colorBlindness;
	}


	public void setColorBlindness(String colorBlindness) {
		this.colorBlindness = colorBlindness;
	}

	@Column(name="Eye_Vision")
	public String getEyeVision() {
		return eyeVision;
	}


	public void setEyeVision(String eyeVision) {
		this.eyeVision = eyeVision;
	}

	@Column(name="R")
	public String getR() {
		return r;
	}


	public void setR(String r) {
		this.r = r;
	}

	@Column(name="Blood_Group")
	public String getBloodGroup() {
		return bloodGroup;
	}


	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name="Respiratory_System")
	public String getRespiratorySystem() {
		return respiratorySystem;
	}


	public void setRespiratorySystem(String respiratorySystem) {
		this.respiratorySystem = respiratorySystem;
	}

	@Column(name="Ans_Autonomous_Nerves_System")
	public String getAnsAutonomousNervesSystem() {
		return ansAutonomousNervesSystem;
	}


	public void setAnsAutonomousNervesSystem(String ansAutonomousNervesSystem) {
		this.ansAutonomousNervesSystem = ansAutonomousNervesSystem;
	}

	@Column(name="Liver_Or_Spleen")
	public String getLiverOrSpleen() {
		return liverOrSpleen;
	}


	public void setLiverOrSpleen(String liverOrSpleen) {
		this.liverOrSpleen = liverOrSpleen;
	}

	@Column(name="PastHistory")
	public String getPastHistory() {
		return pastHistory;
	}


	public void setPastHistory(String pastHistory) {
		this.pastHistory = pastHistory;
	}

	@Column(name="Any_Operation_Done_In_Past")
	public String getAnyOperationDoneInPast() {
		return anyOperationDoneInPast;
	}


	public void setAnyOperationDoneInPast(String anyOperationDoneInPast) {
		this.anyOperationDoneInPast = anyOperationDoneInPast;
	}

	@Column(name="oeema")
	public String getOeema() {
		return oeema;
	}


	public void setOeema(String oeema) {
		this.oeema = oeema;
	}

	@Column(name="Cunosis")
	public String getCunosis() {
		return cunosis;
	}


	public void setCunosis(String cunosis) {
		this.cunosis = cunosis;
	}

	@Column(name="Jaundice")
	public String getJaundice() {
		return jaundice;
	}


	public void setJaundice(String jaundice) {
		this.jaundice = jaundice;
	}

	@Column(name="Medical_Officer_Comment")
	public String getMedicalOfficerComment() {
		return medicalOfficerComment;
	}


	public void setMedicalOfficerComment(String medicalOfficerComment) {
		this.medicalOfficerComment = medicalOfficerComment;
	}

	@Column(name="Any_Other_Physical_Disability")
	public String getAnyOtherPhysicalDisability() {
		return anyOtherPhysicalDisability;
	}


	public void setAnyOtherPhysicalDisability(String anyOtherPhysicalDisability) {
		this.anyOtherPhysicalDisability = anyOtherPhysicalDisability;
	}

	@Column(name="Medically_Fit")
	public String getMedicallyFit() {
		return medicallyFit;
	}


	public void setMedicallyFit(String medicallyFit) {
		this.medicallyFit = medicallyFit;
	}



	@Column(name="Review_Date")
	public Date getReviewDate() {
		return reviewDate;
	}


	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	@Column(name="Signature_Of_Doctor")
	public String getSignatureOfDoctor() {
		return signatureOfDoctor;
	}


	public void setSignatureOfDoctor(String signatureOfDoctor) {
		this.signatureOfDoctor = signatureOfDoctor;
	}

	@Column(name="File_Path")
	public String getFilePath() {
		return filePath;
	}


	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	 @Column(name="Country_Id", nullable=false)
	public Integer getCountryId() {
		return countryId;
	}


	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	@Column(name="File_Name")
	public String getFileName() {
		return fileName;
	}


	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name="Weight_Type")
	public String getWeightType() {
		return weightType;
	}


	public void setWeightType(String weightType) {
		this.weightType = weightType;
	}

	@Column(name="Height_Type")
	public String getHeightType() {
		return heightType;
	}


	public void setHeightType(String heightType) {
		this.heightType = heightType;
	}
    
    
    
    
    

}


