package com.Ntranga.core.CLMS.entities;
// Generated Jul 19, 2016 5:52:35 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkrorderDetail generated by hbm2java
 */
@Entity
@Table(name="workrorder_detail"    
)
public class WorkrorderDetail  implements java.io.Serializable {


     private Integer workOrderId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private String workOrderCode;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Set<WorkorderDetailInfo> workorderDetailInfos = new HashSet<WorkorderDetailInfo>(0);

    public WorkrorderDetail() {
    }

	
    public WorkrorderDetail(CustomerDetails customerDetails, CompanyDetails companyDetails, String workOrderCode, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.customerDetails = customerDetails;
        this.companyDetails = companyDetails;
        this.workOrderCode = workOrderCode;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public WorkrorderDetail(CustomerDetails customerDetails, CompanyDetails companyDetails, String workOrderCode, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<WorkorderDetailInfo> workorderDetailInfos) {
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.workOrderCode = workOrderCode;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.workorderDetailInfos = workorderDetailInfos;
    }
   
     public WorkrorderDetail(Integer workOrderId) {
        this.workOrderId = workOrderId;
    }


	@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="WorkOrder_id", unique=true, nullable=false)
    public Integer getWorkOrderId() {
        return this.workOrderId;
    }
    
    public void setWorkOrderId(Integer workOrderId) {
        this.workOrderId = workOrderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="WorkOrder_Code", nullable=false, length=20)
    public String getWorkOrderCode() {
        return this.workOrderCode;
    }
    
    public void setWorkOrderCode(String workOrderCode) {
        this.workOrderCode = workOrderCode;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="workrorderDetail")
    public Set<WorkorderDetailInfo> getWorkorderDetailInfos() {
        return this.workorderDetailInfos;
    }
    
    public void setWorkorderDetailInfos(Set<WorkorderDetailInfo> workorderDetailInfos) {
        this.workorderDetailInfos = workorderDetailInfos;
    }




}


