package com.Ntranga.core.CLMS.entities;
// Generated 20 Jul, 2016 1:01:39 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerCertificationDetails generated by hbm2java
 */
@Entity
@Table(name="worker_certification_details"   
)
public class WorkerCertificationDetails  implements java.io.Serializable {


     private Integer workerCertificateId;
     private WorkerDetails workerDetails;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private CompanyDetails companyDetails;
     private String certificateName;
     private String issuingAuthority;
     private String validity;
     private Date validFrom;
     private Date validTo;
     private byte[] certificate;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private String filePath;

    public WorkerCertificationDetails() {
    }

	
    public WorkerCertificationDetails(WorkerDetails workerDetails, CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.workerDetails = workerDetails;
        this.customerDetails = customerDetails;
        this.vendorDetails = vendorDetails;
        this.companyDetails = companyDetails;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public WorkerCertificationDetails(WorkerDetails workerDetails, CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, String certificateName, String issuingAuthority, String validiy, Date validFrom, Date validTo, byte[] certificate, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.workerDetails = workerDetails;
       this.customerDetails = customerDetails;
       this.vendorDetails = vendorDetails;
       this.companyDetails = companyDetails;
       this.certificateName = certificateName;
       this.issuingAuthority = issuingAuthority;
       this.validity = validiy;
       this.validFrom = validFrom;
       this.validTo = validTo;
       this.certificate = certificate;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Worker_Certificate_Id", unique=true, nullable=false)
    public Integer getWorkerCertificateId() {
        return this.workerCertificateId;
    }
    
    public void setWorkerCertificateId(Integer workerCertificateId) {
        this.workerCertificateId = workerCertificateId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_Id", nullable=false)
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Certificate_Name", length=45)
    public String getCertificateName() {
        return this.certificateName;
    }
    
    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName;
    }

    
    @Column(name="Issuing_Authority", length=45)
    public String getIssuingAuthority() {
        return this.issuingAuthority;
    }
    
    public void setIssuingAuthority(String issuingAuthority) {
        this.issuingAuthority = issuingAuthority;
    }

    
    @Column(name="Validity", length=45)
    public String getValidity() {
        return this.validity;
    }
    
    public void setValidity(String validity) {
        this.validity = validity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Valid_From", length=10)
    public Date getValidFrom() {
        return this.validFrom;
    }
    
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Valid_To", length=10)
    public Date getValidTo() {
        return this.validTo;
    }
    
    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    
    @Column(name="Certificate")
    public byte[] getCertificate() {
        return this.certificate;
    }
    
    public void setCertificate(byte[] certificate) {
        this.certificate = certificate;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name="File_Path", nullable=false, length=255)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }


}


