package com.Ntranga.core.CLMS.entities;
// Generated 18 Aug, 2016 7:24:50 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerVerificationStatus generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="worker_verification_status"   
)
public class WorkerVerificationStatus  implements java.io.Serializable {


     private Integer verificationId;
     private WorkerDetails workerDetails;
     private int customerId;
     private int companyId;
     private int vendorId;
     private String verificationType;
     private String isCleared;
     private String comments;
     private String fileName;
     private String location;
     //private String isValidated;
    // private String badgeGenerationStatus;
     private String verificationStatus;
     private int countryId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private String status;

    public WorkerVerificationStatus() {
    }

	
    public WorkerVerificationStatus(WorkerDetails workerDetails, int customerId, int companyId, int vendorId, int countryId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.workerDetails = workerDetails;
        this.customerId = customerId;
        this.companyId = companyId;
        this.vendorId = vendorId;
        this.countryId = countryId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public WorkerVerificationStatus(WorkerDetails workerDetails, int customerId, int companyId, int vendorId, String status, String verificationType, String isCleared, String comments, String fileName, String location,  String verificationStatus, int countryId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.workerDetails = workerDetails;
       this.customerId = customerId;
       this.companyId = companyId;
       this.vendorId = vendorId;
       this.verificationType = verificationType;
       this.isCleared = isCleared;
       this.comments = comments;
       this.fileName = fileName;
       this.location = location;
       this.verificationStatus = verificationStatus;
       this.countryId = countryId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Verification_Id", unique=true, nullable=false)
    public Integer getVerificationId() {
        return this.verificationId;
    }
    
    public void setVerificationId(Integer verificationId) {
        this.verificationId = verificationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_Id", nullable=false)
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

    
    @Column(name="Customer_Id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Company_Id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="Vendor_Id", nullable=false)
    public int getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(int vendorId) {
        this.vendorId = vendorId;
    }

    
    @Column(name="Verification_Type", length=45)
    public String getVerificationType() {
        return this.verificationType;
    }
    
    public void setVerificationType(String verificationType) {
        this.verificationType = verificationType;
    }

    
    @Column(name="IsCleared", length=4)
    public String getIsCleared() {
        return this.isCleared;
    }
    
    public void setIsCleared(String isCleared) {
        this.isCleared = isCleared;
    }

    
    @Column(name="Comments", length=200)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="File_Name", length=100)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="Location", length=300)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    /*@Column(name="IsValidated", length=4)
    public String getIsValidated() {
        return this.isValidated;
    }
    
    public void setIsValidated(String isValidated) {
        this.isValidated = isValidated;
    }
*/
    
    @Column(name="Verification_Status", length=15)
    public String getVerificationStatus() {
        return this.verificationStatus;
    }
    
    public void setVerificationStatus(String verificationStatus) {
        this.verificationStatus = verificationStatus;
    }
    
    @Column(name="Status", length=15)
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="Country_Id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


