package com.Ntranga.core.CLMS.entities;
// Generated 16 Jul, 2016 7:27:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerNomineeDetails generated by hbm2java
 */
@Entity
@Table(name="worker_nominee_details"
)
public class WorkerNomineeDetails  implements java.io.Serializable {


     private Integer workerNomineeId;
     private WorkerDetails workerDetails;
     private int customerId;
     private int companyId;
     private String memberName;
     private String relationship;
     private Date dateOfBirth;
     private Character gender;
     private String address;
     private String guardianDetails;
     private Integer percentageShareInPF;
     private Integer ageYears;
     private Integer ageMonths;
     
     
    
     private String phoneNumber;
     private String selectAsNominee;
     private String isMinor;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;

    public WorkerNomineeDetails() {
    }

	
    public WorkerNomineeDetails(WorkerDetails workerDetails, int customerId, int companyId, String memberName, String relationship, String selectAsNominee, String isMinor, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate,Integer ageYears,Integer ageMonths) {
        this.workerDetails = workerDetails;
        this.customerId = customerId;
        this.companyId = companyId;
        this.memberName = memberName;
        this.relationship = relationship;
        this.selectAsNominee = selectAsNominee;
        this.isMinor = isMinor;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.ageYears=ageYears;
        this.ageMonths=ageMonths;
    }
    public WorkerNomineeDetails(WorkerDetails workerDetails, int customerId, int companyId, String memberName, String relationship, Date dateOfBirth, Character gender, String address, String phoneNumber, String selectAsNominee, String isMinor, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.workerDetails = workerDetails;
       this.customerId = customerId;
       this.companyId = companyId;
       this.memberName = memberName;
       this.relationship = relationship;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.address =address;
       this.phoneNumber = phoneNumber;
       this.selectAsNominee = selectAsNominee;
       this.isMinor = isMinor;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Worker_nominee_id", unique=true, nullable=false)
    public Integer getWorkerNomineeId() {
        return this.workerNomineeId;
    }
    
    public void setWorkerNomineeId(Integer workerNomineeId) {
        this.workerNomineeId = workerNomineeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_id", nullable=false)
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

    
    @Column(name="customer_id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="company_id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="Member_name", nullable=false, length=50)
    public String getMemberName() {
        return this.memberName;
    }
    
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    
    @Column(name="Relationship", nullable=false, length=50)
    public String getRelationship() {
        return this.relationship;
    }
    
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_of_birth", length=19)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="Gender", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

    
   

    @Column(name="Address", length=500)
    public String getAddress() {
		return address;
	}


	public void setAddress(String address) {
		this.address = address;
	}


	@Column(name="Phone_number", length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="Select_As_Nominee", nullable=false, length=2)
    public String getSelectAsNominee() {
        return this.selectAsNominee;
    }
    
    public void setSelectAsNominee(String selectAsNominee) {
        this.selectAsNominee = selectAsNominee;
    }

    
    @Column(name="IsMinor", nullable=false, length=2)
    public String getIsMinor() {
        return this.isMinor;
    }
    
    public void setIsMinor(String isMinor) {
        this.isMinor = isMinor;
    }
    
    
  // 

    @Column(name="Guardian_Details", length=100)
    public String getGuardianDetails() {
		return guardianDetails;
	}


	public void setGuardianDetails(String guardianDetails) {
		this.guardianDetails = guardianDetails;
	}

	
	


	@Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
	
	public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    
	 @Column(name="Percentage_Share_In_PF")
    public Integer getPercentageShareInPF() {
		return percentageShareInPF;
	}


	public void setPercentageShareInPF(Integer percentageShareInPF) {
		this.percentageShareInPF = percentageShareInPF;
	}


	

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }



   
    

    @Column(name="ageMonths")
	public Integer getAgeMonths() {
		return ageMonths;
	}
    public void setAgeMonths(Integer ageMonths) {
		this.ageMonths = ageMonths;
	}

    @Column(name="ageYears")
	public Integer getAgeYears() {
		return ageYears;
	}


	public void setAgeYears(Integer ageYears) {
		this.ageYears = ageYears;
	}


	
    
    
    
    

}


