package com.Ntranga.core.CLMS.entities;
// Generated Jul 19, 2016 5:52:35 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkorderDetailInfo generated by hbm2java
 */
@Entity
@Table(name="workorder_detail_info"    
)
public class WorkorderDetailInfo  implements java.io.Serializable {


     private Integer workOrderInfoId;
     private WorkrorderDetail workrorderDetail;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private Integer country;
     private Date transactionDate;
     private Integer sequenceId;
     private String isActive;
     private String workOrderName;
     private LocationDetails locationDetails;
     private DepartmentDetails departmentDetails;
     private PlantDetails plantDetails;
     private Integer totalHeadCount;
     private Date workPeriodFrom;
     private Date workPeriodTo;
     private String natureOfWork;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public WorkorderDetailInfo() {
    }

    public WorkorderDetailInfo(Integer workOrderInfoId) {
        this.workOrderInfoId = workOrderInfoId;
    }
    
    
    public WorkorderDetailInfo(String isActive, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
        this.isActive = isActive;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public WorkorderDetailInfo(WorkrorderDetail workrorderDetail, CustomerDetails customerDetails, CompanyDetails companyDetails, Integer country, Date transactionDate, Integer sequenceId, String isActive, String workOrderName, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.workrorderDetail = workrorderDetail;
       this.customerDetails = customerDetails;
       this.companyDetails = companyDetails;
       this.country = country;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.isActive = isActive;
       this.workOrderName = workOrderName;
      
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="WorkOrder_Info_id", unique=true, nullable=false)
    public Integer getWorkOrderInfoId() {
        return this.workOrderInfoId;
    }
    
    public void setWorkOrderInfoId(Integer workOrderInfoId) {
        this.workOrderInfoId = workOrderInfoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WorkOrder_id")
    public WorkrorderDetail getWorkrorderDetail() {
        return this.workrorderDetail;
    }
    
    public void setWorkrorderDetail(WorkrorderDetail workrorderDetail) {
        this.workrorderDetail = workrorderDetail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id")
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id")
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Country")
    public Integer getCountry() {
        return this.country;
    }
    
    public void setCountry(Integer country) {
        this.country = country;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_Id")
    public Integer getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Work_Order_Name", length=100)
    public String getWorkOrderName() {
        return this.workOrderName;
    }
    
    public void setWorkOrderName(String workOrderName) {
        this.workOrderName = workOrderName;
    }

    
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Location_Id")
    public LocationDetails getLocationDetails() {
		return locationDetails;
	}

	public void setLocationDetails(LocationDetails locationDetails) {
		this.locationDetails = locationDetails;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Department_Id")
	public DepartmentDetails getDepartmentDetails() {
		return departmentDetails;
	}

	public void setDepartmentDetails(DepartmentDetails departmentDetails) {
		this.departmentDetails = departmentDetails;
	}
	
	
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Plant_Id")
	public PlantDetails getPlantDetails() {
		return plantDetails;
	}

	public void setPlantDetails(PlantDetails plantDetails) {
		this.plantDetails = plantDetails;
	}

	@Column(name="Total_Head_Count", length=11)
    public Integer getTotalHeadCount() {
		return totalHeadCount;
	}

	public void setTotalHeadCount(Integer totalHeadCount) {
		this.totalHeadCount = totalHeadCount;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="Work_Period_From", length=10)
	public Date getWorkPeriodFrom() {
		return workPeriodFrom;
	}

	public void setWorkPeriodFrom(Date workPeriodFrom) {
		this.workPeriodFrom = workPeriodFrom;
	}

	@Temporal(TemporalType.DATE)
    @Column(name="Work_Period_To", length=10)
	public Date getWorkPeriodTo() {
		return workPeriodTo;
	}

	public void setWorkPeriodTo(Date workPeriodTo) {
		this.workPeriodTo = workPeriodTo;
	}

	@Column(name="Nature_Of_Work", length=100)
	public String getNatureOfWork() {
		return natureOfWork;
	}

	public void setNatureOfWork(String natureOfWork) {
		this.natureOfWork = natureOfWork;
	}

	@Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


