package com.Ntranga.core.CLMS.entities;
// Generated 16 Jul, 2016 7:27:01 PM by Hibernate Tools 3.6.0


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerAddress generated by hbm2java
 */
@Entity
@Table(name="worker_address"
)
public class WorkerAddress  implements java.io.Serializable {


     private Integer workerAddressId;
     private WorkerDetails workerDetails;
     private String addressType;
     private int customerId;
     private int companyId;
     private Date transactionDate;
     private int sequenceId;
     private String addressLine1;
     private String addressLine2;
     private String addressLine3;
     private Integer countryId;
     private Integer stateId;
     private String city;
     private Integer pinCode;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private String isSameAddress;

    public WorkerAddress() {
    }

	
    public WorkerAddress(WorkerDetails workerDetails, String addressType, int customerId, int companyId, Date transactionDate, int sequenceId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.workerDetails = workerDetails;
        this.addressType = addressType;
        this.customerId = customerId;
        this.companyId = companyId;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public WorkerAddress(WorkerDetails workerDetails, String addressType, int customerId, int companyId, Date transactionDate, int sequenceId, String addressLine1, String addressLine2, String addressLine3, Integer countryId, Integer stateId, String city, Integer pinCode, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, String isSameAddress) {
       this.workerDetails = workerDetails;
       this.addressType = addressType;
       this.customerId = customerId;
       this.companyId = companyId;
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.countryId = countryId;
       this.stateId = stateId;
       this.city = city;
       this.pinCode = pinCode;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.isSameAddress = isSameAddress;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Worker_Address_id", unique=true, nullable=false)
    public Integer getWorkerAddressId() {
        return this.workerAddressId;
    }
    
    public void setWorkerAddressId(Integer workerAddressId) {
        this.workerAddressId = workerAddressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_Id", nullable=false)
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

    
    @Column(name="Address_Type", nullable=false, length=20)
    public String getAddressType() {
        return this.addressType;
    }
    
    public void setAddressType(String addressType) {
        this.addressType = addressType;
    }

    
    @Column(name="customer_id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="company_id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=19)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Address_line1", length=50)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="Address_line2", length=50)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="Address_line3", length=50)
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }

    
    @Column(name="Country_id")
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="State_id")
    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    
    @Column(name="City", length=20)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Pin_code")
    public Integer getPinCode() {
        return this.pinCode;
    }
    
    public void setPinCode(Integer pinCode) {
        this.pinCode = pinCode;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name="Is_Same_Address",  length=5)
	public String getIsSameAddress() {
		return isSameAddress;
	}


	public void setIsSameAddress(String isSameAddress) {
		this.isSameAddress = isSameAddress;
	}




}


