package com.Ntranga.core.CLMS.entities;
// Generated Jul 20, 2016 6:08:14 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkorderManpowerDetails generated by hbm2java
 */
@Entity
@Table(name="workorder_manpower_details"
    
)
public class WorkorderManpowerDetails  implements java.io.Serializable {


     private Integer workOrderManpowerReqId;
     private WorkrorderDetail workrorderDetail;
     private WorkorderDetailInfo workorderDetailInfo;
     private String workSkillId;
     private Integer jobCodeId;
     private Integer headCount;
     private Date fromDate;
     private Date toDate;
     private Integer duration;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public WorkorderManpowerDetails() {
    }

    public WorkorderManpowerDetails(WorkrorderDetail workrorderDetail, WorkorderDetailInfo workorderDetailInfo, String workSkillId, Integer jobCodeId, Integer headCount, Date fromDate, Date toDate,  Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.workrorderDetail = workrorderDetail;
       this.workorderDetailInfo = workorderDetailInfo;
       this.workSkillId = workSkillId;
       this.jobCodeId = jobCodeId;
       this.headCount = headCount;
       this.fromDate = fromDate;
       this.toDate = toDate;      
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="WorkOrder_Manpower_Req_id", unique=true, nullable=false)
    public Integer getWorkOrderManpowerReqId() {
        return this.workOrderManpowerReqId;
    }
    
    public void setWorkOrderManpowerReqId(Integer workOrderManpowerReqId) {
        this.workOrderManpowerReqId = workOrderManpowerReqId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WorkOrder_id", nullable=false)
    public WorkrorderDetail getWorkrorderDetail() {
        return this.workrorderDetail;
    }
    
    public void setWorkrorderDetail(WorkrorderDetail workrorderDetail) {
        this.workrorderDetail = workrorderDetail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WorkOrder_Info_id", nullable=false)
    public WorkorderDetailInfo getWorkorderDetailInfo() {
        return this.workorderDetailInfo;
    }
    
    public void setWorkorderDetailInfo(WorkorderDetailInfo workorderDetailInfo) {
        this.workorderDetailInfo = workorderDetailInfo;
    }

    
    @Column(name="Work_Skill_id", nullable=false, length=50)
    public String getWorkSkillId() {
        return this.workSkillId;
    }
    
    public void setWorkSkillId(String workSkillId) {
        this.workSkillId = workSkillId;
    }

    
    @Column(name="Job_Code_id", nullable=false)
    public Integer getJobCodeId() {
        return this.jobCodeId;
    }
    
    public void setJobCodeId(Integer jobCodeId) {
        this.jobCodeId = jobCodeId;
    }

    
    @Column(name="Head_Count", nullable=false)
    public Integer getHeadCount() {
        return this.headCount;
    }
    
    public void setHeadCount(Integer headCount) {
        this.headCount = headCount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="From_Date", nullable=false, length=10)
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="To_Date", nullable=false, length=10)
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    
    @Column(name="Duration", nullable=false)
    public Integer getDuration() {
		return duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


