package com.Ntranga.core.CLMS.entities;
// Generated Jul 17, 2016 4:55:33 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerDetails generated by hbm2java
 */
@Entity
@Table(name="worker_details"
    
)
public class WorkerDetails  implements java.io.Serializable {


     private Integer workerId;
     private String workerCode;
     private int customerId;
     private int companyId;
     private int countryId;
     private int vendorId;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private Set<WorkJobDetails> workJobDetailses = new HashSet<WorkJobDetails>(0);

    public WorkerDetails() {
    }

	
    public WorkerDetails(String workerCode, int customerId, int companyId, int countryId, int vendorId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.workerCode = workerCode;
        this.customerId = customerId;
        this.companyId = companyId;
        this.countryId = countryId;
        this.vendorId = vendorId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public WorkerDetails(String workerCode, int customerId, int companyId, int countryId, int vendorId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate, Set<WorkJobDetails> workJobDetailses) {
       this.workerCode = workerCode;
       this.customerId = customerId;
       this.companyId = companyId;
       this.countryId = countryId;
       this.vendorId = vendorId;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.workJobDetailses = workJobDetailses;
    }
   
     public WorkerDetails(Integer workerId) {
         this.workerId = workerId;
     }


	@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Worker_id", unique=true, nullable=false)
    public Integer getWorkerId() {
        return this.workerId;
    }
    
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    
    @Column(name="Worker_code", nullable=false, length=20)
    public String getWorkerCode() {
        return this.workerCode;
    }
    
    public void setWorkerCode(String workerCode) {
        this.workerCode = workerCode;
    }

    
    @Column(name="Customer_id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Company_id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="Country_id", nullable=false)
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="vendor_id", nullable=false)
    public int getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(int vendorId) {
        this.vendorId = vendorId;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="workerDetails")
    public Set<WorkJobDetails> getWorkJobDetailses() {
        return this.workJobDetailses;
    }
    
    public void setWorkJobDetailses(Set<WorkJobDetails> workJobDetailses) {
        this.workJobDetailses = workJobDetailses;
    }




}


