package com.Ntranga.core.CLMS.entities;
// Generated Jun 27, 2016 3:48:14 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerShiftDetails generated by hbm2java
 */
@Entity
@Table(name="Worker_Shift_Details")
public class WorkerShiftDetails  implements java.io.Serializable {


     private Integer workerShiftDetailsId;
     private CustomerDetails customerDetails;
     private CompanyDetails companyDetails;
     private VendorDetails vendorDetails;
     private WorkerDetails workerDetails;
     private DepartmentDetails departmentDetails ;
     private LocationDetails locationDetails;
 	 private PlantDetails plantDetails;
 	 private SectionDetails sectionDetails;
     private String shiftCode;
     private String workerCode;
     private Date shiftDate;    
     private String isActive;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public WorkerShiftDetails() {
    }

    
	   
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Worker_Shift_Details_Id", unique=true, nullable=false)
     public Integer getWorkerShiftDetailsId() {
 		return workerShiftDetailsId;
 	}
 	public void setWorkerShiftDetailsId(Integer workerShiftDetailsId) {
 		this.workerShiftDetailsId = workerShiftDetailsId;
 	}

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id", nullable=false)
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
	public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id", nullable=false)
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }


@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }
    
    @Column(name="Is_Active", nullable=false, length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="Created_By", nullable=false)
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_id")
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

    @Column(name="Shift_Code", length=25)
	public String getShiftCode() {
		return shiftCode;
	}
	public void setShiftCode(String shiftCode) {
		this.shiftCode = shiftCode;
	}


	@Column(name="Worker_Code", length=25)
	public String getWorkerCode() {
		return workerCode;
	}
	public void setWorkerCode(String workerCode) {
		this.workerCode = workerCode;
	}



	@Temporal(TemporalType.DATE)
    @Column(name="Shift_Date", nullable=false, length=19)
	public Date getShiftDate() {
		return shiftDate;
	}
	public void setShiftDate(Date shiftDate) {
		this.shiftDate = shiftDate;
	}
    
	@ManyToOne(fetch=FetchType.LAZY)
	 @JoinColumn(name="Department_Id")
	public DepartmentDetails getDepartmentDetails() {
		return departmentDetails;
	}

	public void setDepartmentDetails(DepartmentDetails departmentId) {
		this.departmentDetails = departmentId;
	}
    
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="Location_Id")
	public LocationDetails getLocationDetails() {
		return locationDetails;
	}

	public void setLocationDetails(LocationDetails locationDetails) {
		this.locationDetails = locationDetails;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="Plant_Id")	
	public PlantDetails getPlantDetails() {
		return plantDetails;
	}

	public void setPlantDetails(PlantDetails plantDetails) {
		this.plantDetails = plantDetails;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="Section_Id")	
	public SectionDetails getSectionDetails() {
		return sectionDetails;
	}
	
	
	public void setSectionDetails(SectionDetails sectionDetails) {
		this.sectionDetails = sectionDetails;
	}
	
}


