package com.Ntranga.core.CLMS.entities;
// Generated 26 Jul, 2016 12:58:32 PM by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerDetailsInfo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "worker_details_info")
public class WorkerDetailsInfo implements java.io.Serializable {

	private Integer workerInfoId;
	private WorkerDetails workerDetails;
	private int customerId;
	private int companyId;
	private Date transactionDate;
	private int sequenceId;
	private String isActive;
	private String firstName;
	private String middleName;
	private String lastName;
	private String fatherSpouseName;
	private String panNumber;
	private Date dateOfBirth;
	private char gender;
	private String maritalStatus;
	private String bloodGroup;
	private String religion;
	private String phoneNumber;
	private String email;
	private String emergencyContactPerson;
	private String emergencyContactNumber;
	// private String identificationType;
	private int createdBy;
	private Date createdDate;
	private int modifiedBy;
	private Date modifiedDate;
	private String fatherOrSpouse;
	private String age;
	private Date dateOfLeaving;
	private String reasonForStatusChange;
	private Date dateOfJoining;

	private String shiftName;
	private String weeklyOff;

	private String imagePath;
	private String imageName;
	private String acountHolderName;
	private String acountNumber;
	private String bankName;
	private String ifscCode;
	private String branchName;
	private String placeOfBirth;
	private String motherName;
	private String language;
	private String nationality;
	private String education;
	private String domicile;
	

	public WorkerDetailsInfo() {
	}

	public WorkerDetailsInfo(WorkerDetails workerDetails, int customerId, int companyId, Date transactionDate,
			int sequenceId, String isActive, String firstName, String lastName, String panNumber, Date dateOfBirth,
			char gender, String maritalStatus, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
		this.workerDetails = workerDetails;
		this.customerId = customerId;
		this.companyId = companyId;
		this.transactionDate = transactionDate;
		this.sequenceId = sequenceId;
		this.isActive = isActive;
		this.firstName = firstName;
		this.lastName = lastName;
		this.panNumber = panNumber;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.maritalStatus = maritalStatus;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
	}

	public WorkerDetailsInfo(Integer workerInfoId, WorkerDetails workerDetails, int customerId, int companyId,
			Date transactionDate, int sequenceId, String isActive, String firstName, String middleName, String lastName,
			String fatherSpouseName, String panNumber, Date dateOfBirth, char gender, String maritalStatus,
			String bloodGroup, String religion, String phoneNumber, String email, String emergencyContactPerson,
			String emergencyContactNumber, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate,
			String fatherOrSpouse, String age, Date dateOfLeaving, String reasonForStatusChange, Date dateOfJoining,
			String shiftName, String weeklyOff, String imageName, String imagePath) {
		this.workerInfoId = workerInfoId;
		this.workerDetails = workerDetails;
		this.customerId = customerId;
		this.companyId = companyId;
		this.transactionDate = transactionDate;
		this.sequenceId = sequenceId;
		this.isActive = isActive;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.fatherSpouseName = fatherSpouseName;
		this.panNumber = panNumber;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.maritalStatus = maritalStatus;
		this.bloodGroup = bloodGroup;
		this.religion = religion;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.emergencyContactPerson = emergencyContactPerson;
		this.emergencyContactNumber = emergencyContactNumber;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.fatherOrSpouse = fatherOrSpouse;
		this.age = age;
		this.dateOfLeaving = dateOfLeaving;
		this.reasonForStatusChange = reasonForStatusChange;
		this.dateOfJoining = dateOfJoining;
		this.shiftName = shiftName;
		this.weeklyOff = weeklyOff;
		this.imageName = imageName;
		this.imagePath = imagePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Worker_info_id", unique = true, nullable = false)
	public Integer getWorkerInfoId() {
		return this.workerInfoId;
	}

	public void setWorkerInfoId(Integer workerInfoId) {
		this.workerInfoId = workerInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Worker_id", nullable = false)
	public WorkerDetails getWorkerDetails() {
		return this.workerDetails;
	}

	public void setWorkerDetails(WorkerDetails workerDetails) {
		this.workerDetails = workerDetails;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "company_id", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Transaction_Date", nullable = false, length = 10)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "Sequence_id", nullable = false)
	public int getSequenceId() {
		return this.sequenceId;
	}

	public void setSequenceId(int sequenceId) {
		this.sequenceId = sequenceId;
	}

	@Column(name = "Is_Active", nullable = false, length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "First_name", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
		
	
	@Column(name = "Place_of_birth", length = 50)
	public String getPlaceOfBirth() {
		return placeOfBirth;
	}

	public void setPlaceOfBirth(String placeOfBirth) {
		this.placeOfBirth = placeOfBirth;
	}
	
	

	@Column(name = "Middle_name", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "Shift_Name", length = 50)
	public String getShiftName() {
		return shiftName;
	}

	public void setShiftName(String shiftName) {
		this.shiftName = shiftName;
	}

	@Column(name = "Weekly_Off", length = 50)
	public String getWeeklyOff() {
		return weeklyOff;
	}

	public void setWeeklyOff(String weeklyOff) {
		this.weeklyOff = weeklyOff;
	}

	@Column(name = "Last_name", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Father_Spouse_name", length = 50)
	public String getFatherSpouseName() {
		return this.fatherSpouseName;
	}

	public void setFatherSpouseName(String fatherSpouseName) {
		this.fatherSpouseName = fatherSpouseName;
	}

	@Column(name = "PAN_number", nullable = false, length = 50)
	public String getPanNumber() {
		return this.panNumber;
	}

	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_of_birth", nullable = false, length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "Gender", nullable = false, length = 1)
	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	@Column(name = "Marital_Status", nullable = false, length = 20)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "Blood_group", length = 10)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "Religion", length = 20)
	public String getReligion() {
		return this.religion;
	}

	public void setReligion(String religion) {
		this.religion = religion;
	}

	@Column(name = "Phone_number", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "Email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Emergency_contact_person", length = 50)
	public String getEmergencyContactPerson() {
		return this.emergencyContactPerson;
	}

	public void setEmergencyContactPerson(String emergencyContactPerson) {
		this.emergencyContactPerson = emergencyContactPerson;
	}

	@Column(name = "Emergency_contact_number", length = 20)
	public String getEmergencyContactNumber() {
		return this.emergencyContactNumber;
	}

	public void setEmergencyContactNumber(String emergencyContactNumber) {
		this.emergencyContactNumber = emergencyContactNumber;
	}

	@Column(name = "Created_By")
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created_Date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "Modified_By")
	public int getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(int modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Modified_Date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "Father_Or_Spouse", length = 45)
	public String getFatherOrSpouse() {
		return this.fatherOrSpouse;
	}

	public void setFatherOrSpouse(String fatherOrSpouse) {
		this.fatherOrSpouse = fatherOrSpouse;
	}

	@Column(name = "Age", length = 45)
	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_Of_Leaving", length = 10)
	public Date getDateOfLeaving() {
		return dateOfLeaving;
	}

	public void setDateOfLeaving(Date dateOfLeaving) {
		this.dateOfLeaving = dateOfLeaving;
	}

	@Column(name = "Reason_For_Status_Change")
	public String getReasonForStatusChange() {
		return reasonForStatusChange;
	}

	public void setReasonForStatusChange(String reasonForStatusChange) {
		this.reasonForStatusChange = reasonForStatusChange;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_Of_Joining", nullable = true, length = 10)
	public Date getDateOfJoining() {
		return dateOfJoining;
	}

	public void setDateOfJoining(Date dateOfJoining) {
		this.dateOfJoining = dateOfJoining;
	}

	@Column(name = "Image_Path", length = 255)
	public String getImagePath() {
		return imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "Image_Name", length = 100)
	public String getImageName() {
		return imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "Acount_Holder_Name",  length = 50)
	public String getAcountHolderName() {
		return acountHolderName;
	}

	public void setAcountHolderName(String acountHolderName) {
		this.acountHolderName = acountHolderName;
	}

	@Column(name = "Acount_Number", length = 50)
	public String getAccountNumber() {
		return acountNumber;
	}

	public void setAccountNumber(String acountNumber) {
		this.acountNumber = acountNumber;
	}

	@Column(name = "Ifsc_Code", length = 50)
	public String getIfscCode() {
		return ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

	@Column(name = "Bank_Name", length = 50)
	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "Branch_Name", length = 50)
	public String getBranchName() {
		return branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}
	
	
	@Column(name = "Mother_Name", length = 50)
	public String getMotherName() {
		return motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	@Column(name = "language", length = 50)
	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}
	@Column(name = "nationality", length = 50)
	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}
	@Column(name = "education", length = 50)
	public String getEducation() {
		return education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "domicile", length = 50)
	public String getDomicile() {
		return domicile;
	}

	public void setDomicile(String domicile) {
		this.domicile = domicile;
	}
	
	
	

}
