package com.Ntranga.core.CLMS.entities;
// Generated 16 Jul, 2016 7:27:01 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerIdentificationProof generated by hbm2java
 */
@Entity
@Table(name="worker_identification_proof"
)
public class WorkerIdentificationProof  implements java.io.Serializable {

     private Integer workerIdentificationId;
     private WorkerDetails workerDetails;
     private int customerId;
     private int companyId;
     private Date transactionDate;
     private int sequenceId;
     private String identificationType;
     private String filePath;
     private byte[] identificationProofDocument;
     private int createdBy;
     private Date createdDate;
     private int modifiedBy;
     private Date modifiedDate;
     private int countryId;
     private String identificationNumber;

    public WorkerIdentificationProof() {
    }

	
    public WorkerIdentificationProof(WorkerDetails workerDetails, int customerId,  int companyId, Date transactionDate, int sequenceId, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
        this.workerDetails = workerDetails;
        this.customerId = customerId;
        this.companyId = companyId;
        this.transactionDate = transactionDate;
        this.sequenceId = sequenceId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public WorkerIdentificationProof(WorkerDetails workerDetails, int customerId, String filePath, int companyId, Date transactionDate, int sequenceId, String identificationType, byte[] identificationProofDocument, int createdBy, Date createdDate, int modifiedBy, Date modifiedDate) {
       this.workerDetails = workerDetails;
       this.customerId = customerId;
       this.companyId = companyId;
       this.setFilePath(filePath);
       this.transactionDate = transactionDate;
       this.sequenceId = sequenceId;
       this.identificationType = identificationType;
       this.identificationProofDocument = identificationProofDocument;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="worker_identification_id", unique=true, nullable=false)
    public Integer getWorkerIdentificationId() {
        return this.workerIdentificationId;
    }
    
    public void setWorkerIdentificationId(Integer workerIdentificationId) {
        this.workerIdentificationId = workerIdentificationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="worker_id", nullable=false)
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

    
    @Column(name="customer_id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="company_id", nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Transaction_Date", nullable=false, length=19)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="Sequence_id", nullable=false)
    public int getSequenceId() {
        return this.sequenceId;
    }
    
    public void setSequenceId(int sequenceId) {
        this.sequenceId = sequenceId;
    }

    
    @Column(name="Identification_Type")
    public String getIdentificationType() {
        return this.identificationType;
    }
    
    public void setIdentificationType(String identificationType) {
        this.identificationType = identificationType;
    }

    @Column(name="File_Path")
    public String getFilePath() {
		return filePath;
	}


	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	
	
	
	@Column(name="Identification_Number")
	public String getIdentificationNumber() {
		return identificationNumber;
	}


	public void setIdentificationNumber(String identificationNumber) {
		this.identificationNumber = identificationNumber;
	}


	@Column(name="identification_proof_document")
    public byte[] getIdentificationProofDocument() {
        return this.identificationProofDocument;
    }
    
    public void setIdentificationProofDocument(byte[] identificationProofDocument) {
        this.identificationProofDocument = identificationProofDocument;
    }

    
    @Column(name="Created_By", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created_Date", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By", nullable=false)
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Modified_Date", nullable=false, length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name="Country_Id")
	public int getCountryId() {
		return countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}




}


