package com.Ntranga.core.CLMS.entities;
// Generated Jul 22, 2016 4:15:55 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkerBadgeGeneration generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="worker_badge_generation")
public class WorkerBadgeGeneration  implements java.io.Serializable {


     private Integer workerBadgeId;
     private WorkerDetails workerDetails;
     private CustomerDetails customerDetails;
     private VendorDetails vendorDetails;
     private CompanyDetails companyDetails;
     private Integer country;
     private String cardType;
     //private String isActive;
     private String badgeCode;
     private String ppeIssued;
     private String description;
     private Integer createdBy;
     private Date createdDate;
     private Integer modifiedBy;
     private Date modifiedDate;

    public WorkerBadgeGeneration() {
    }

    public WorkerBadgeGeneration(WorkerDetails workerDetails, CustomerDetails customerDetails, VendorDetails vendorDetails, CompanyDetails companyDetails, Integer country, String cardType,  String badgeCode, String ppeIssued, String description, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
       this.workerDetails = workerDetails;
       this.customerDetails = customerDetails;
       this.vendorDetails = vendorDetails;
       this.companyDetails = companyDetails;
       this.country = country;
       this.cardType = cardType;
       this.badgeCode = badgeCode;
       this.ppeIssued = ppeIssued;
       this.description = description;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Worker_Badge_Id", unique=true, nullable=false)
    public Integer getWorkerBadgeId() {
        return this.workerBadgeId;
    }
    
    public void setWorkerBadgeId(Integer workerBadgeId) {
        this.workerBadgeId = workerBadgeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Worker_Id")
    public WorkerDetails getWorkerDetails() {
        return this.workerDetails;
    }
    
    public void setWorkerDetails(WorkerDetails workerDetails) {
        this.workerDetails = workerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customer_Id")
    public CustomerDetails getCustomerDetails() {
        return this.customerDetails;
    }
    
    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Vendor_Id")
    public VendorDetails getVendorDetails() {
        return this.vendorDetails;
    }
    
    public void setVendorDetails(VendorDetails vendorDetails) {
        this.vendorDetails = vendorDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id")
    public CompanyDetails getCompanyDetails() {
        return this.companyDetails;
    }
    
    public void setCompanyDetails(CompanyDetails companyDetails) {
        this.companyDetails = companyDetails;
    }

    
    @Column(name="Country")
    public Integer getCountry() {
        return this.country;
    }
    
    public void setCountry(Integer country) {
        this.country = country;
    }

    
    @Column(name="Card_Type", length=50)
    public String getCardType() {
        return this.cardType;
    }
    
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    
   /* @Column(name="Is_Active", length=2)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
*/
    
    @Column(name="Badge_Code", length=50)
    public String getBadgeCode() {
        return this.badgeCode;
    }
    
    public void setBadgeCode(String badgeCode) {
        this.badgeCode = badgeCode;
    }

    
    @Column(name="PPE_Issued", length=2)
    public String getPpeIssued() {
        return this.ppeIssued;
    }
    
    public void setPpeIssued(String ppeIssued) {
        this.ppeIssued = ppeIssued;
    }

    
    @Column(name="Description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Created_By")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Created_Date", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="Modified_By")
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Modified_Date", length=10)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


